# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_inventory_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    InventoryAudit = apps.get_model('inventory', 'InventoryAudit')

    fallback = _get_fallback_facility(Facility)

    items = list(
        InventoryItem.objects.filter(facility__isnull=True).select_related(
            'created_by__primary_facility',
            'created_by__staff_profile__primary_facility'
        )
    )
    for item in items:
        facility = None
        created_by = item.created_by
        if created_by and getattr(created_by, 'primary_facility_id', None):
            facility = created_by.primary_facility
        else:
            staff = getattr(created_by, 'staff_profile', None) if created_by else None
            if staff and getattr(staff, 'primary_facility_id', None):
                facility = staff.primary_facility
        if not facility and fallback:
            facility = fallback
        if facility:
            item.facility_id = facility.id
    if items:
        InventoryItem.objects.bulk_update(items, ['facility'])

    audits = list(
        InventoryAudit.objects.filter(facility__isnull=True).select_related(
            'created_by__primary_facility',
            'created_by__staff_profile__primary_facility'
        )
    )
    for audit in audits:
        facility = None
        created_by = audit.created_by
        if created_by and getattr(created_by, 'primary_facility_id', None):
            facility = created_by.primary_facility
        else:
            staff = getattr(created_by, 'staff_profile', None) if created_by else None
            if staff and getattr(staff, 'primary_facility_id', None):
                facility = staff.primary_facility
        if not facility and fallback:
            facility = fallback
        if facility:
            audit.facility_id = facility.id
    if audits:
        InventoryAudit.objects.bulk_update(audits, ['facility'])

    if InventoryItem.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "InventoryItem facility backfill incomplete. "
            "Assign primary_facility or set DEFAULT_FACILITY_CODE."
        )
    if InventoryAudit.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "InventoryAudit facility backfill incomplete. "
            "Assign primary_facility or set DEFAULT_FACILITY_CODE."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='inventory_items',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='inventoryaudit',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='inventory_audits',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_inventory_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventoryitem',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='inventory_items',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='inventory_audits',
                to='core.facility',
            ),
        ),
    ]
