# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_stock_movement_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    StockMovement = apps.get_model('inventory', 'StockMovement')

    fallback = _get_fallback_facility(Facility)

    movements = list(
        StockMovement.objects.filter(facility__isnull=True)
        .select_related('item__facility')
    )
    for movement in movements:
        facility = movement.item.facility if movement.item_id else None
        if not facility and fallback:
            facility = fallback
        if facility:
            movement.facility_id = facility.id

    if movements:
        StockMovement.objects.bulk_update(movements, ['facility'])

    if StockMovement.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "StockMovement facility backfill incomplete. "
            "Ensure inventory item facilities or DEFAULT_FACILITY_CODE are set."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('inventory', '0002_facility_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='stock_movements',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_stock_movement_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockmovement',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='stock_movements',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['facility', '-timestamp'], name='inventory_stock_facility_ts_idx'),
        ),
    ]
