# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('inventory', '0003_stock_movement_facility'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_facilit_ac20b0_idx',
            old_name='inventory_stock_facility_ts_idx',
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='facility',
            field=models.ForeignKey(help_text='Facility where this audit was performed', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audits', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this stock movement', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.facility'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['facility', 'is_active'], name='inventory_i_facilit_cfb954_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['facility', 'item_type'], name='inventory_i_facilit_c4936e_idx'),
        ),
    ]
