# Generated by Django 4.2.10 on 2026-01-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('inventory', '0005_facility_scope_suppliers_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_facilit_cfb954_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_facilit_c4936e_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorycategory',
            new_name='inventory_i_facilit_b2fed3_idx',
            old_name='inventory_cat_facility_name_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='inventory_s_facilit_fef59b_idx',
            old_name='inventory_supplier_facility_name_idx',
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this audit', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audits', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this inventory category', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_categories', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this supplier', on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='core.facility'),
        ),
        migrations.AddIndex(
            model_name='inventoryaudit',
            index=models.Index(fields=['facility', '-audit_date'], name='inventory_i_facilit_6481db_idx'),
        ),
    ]
