# Generated by Django 4.2.10 on 2026-01-24 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_session_ip_and_location'),
        ('wards', '0019_alter_admission_consulting_teams_and_more'),
        ('core', '0010_seed_core_singletons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_alter_inventorycategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Quantity reserved for pending orders/transfers')),
                ('reorder_level', models.PositiveIntegerField(blank=True, help_text='Override item reorder level for this location', null=True)),
                ('reorder_quantity', models.PositiveIntegerField(blank=True, help_text='Override item reorder quantity for this location', null=True)),
                ('max_level', models.PositiveIntegerField(blank=True, help_text='Maximum stock level for this location', null=True)),
                ('last_counted_at', models.DateTimeField(blank=True, help_text='Last physical count date', null=True)),
                ('last_movement_at', models.DateTimeField(blank=True, help_text='Last stock movement date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code within facility', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('pharmacy', 'Pharmacy'), ('satellite', 'Satellite Pharmacy'), ('ward_store', 'Ward Store'), ('department_store', 'Department Store'), ('operating_theatre', 'Operating Theatre'), ('emergency', 'Emergency'), ('laboratory', 'Laboratory')], max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('can_receive_external', models.BooleanField(default=False, help_text='Can receive goods from external suppliers (GRN)')),
                ('can_dispense_to_patients', models.BooleanField(default=False, help_text='Can dispense directly to patients')),
                ('allows_controlled_substances', models.BooleanField(default=False, help_text='Authorized to store controlled substances')),
                ('temperature_zone', models.CharField(choices=[('ambient', 'Ambient (15-25°C)'), ('cool', 'Cool (8-15°C)'), ('refrigerated', 'Refrigerated (2-8°C)'), ('frozen', 'Frozen (-20°C or below)')], default='ambient', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['facility', 'name'],
            },
        ),
        migrations.AddField(
            model_name='expirytracker',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expirytracker',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='alternative_suppliers',
            field=models.ManyToManyField(blank=True, help_text='Alternative suppliers for this item', related_name='alternative_items', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='controlled_schedule',
            field=models.CharField(blank=True, help_text='Drug schedule (e.g., Schedule II, III, IV)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A - High Value'), ('B', 'Class B - Medium Value'), ('C', 'Class C - Low Value')], help_text='ABC classification for inventory management', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_controlled_substance',
            field=models.BooleanField(default=False, help_text='Requires special tracking and witness signatures'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=7, help_text='Expected delivery time from order in days'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Default quantity to order when reordering'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_tracker',
            field=models.ForeignKey(blank=True, help_text='Batch/expiry tracker this movement consumed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_movements', to='inventory.expirytracker'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient for dispense movements', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_id',
            field=models.UUIDField(blank=True, help_text='UUID of related object (PO, GRN, Transfer, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, help_text="Type of reference (e.g., 'PO', 'GRN', 'Transfer', 'Prescription')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expirytracker',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to='inventory.stockmovement'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, help_text='DEPRECATED: Use total_stock property instead'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('medication', 'Medication'), ('supply', 'Medical Supply'), ('equipment', 'Equipment'), ('consumable', 'Consumable'), ('surgical', 'Surgical'), ('laboratory', 'Laboratory'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('food', 'Food Service'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit - unique per facility', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Primary/preferred supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('dispense', 'Dispense'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('disposal', 'Disposal'), ('grn_receipt', 'GRN Receipt'), ('internal_issue', 'Internal Issue'), ('wastage', 'Wastage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='new_stock',
            field=models.PositiveIntegerField(help_text='Stock level at source/destination after movement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='previous_stock',
            field=models.PositiveIntegerField(help_text='Stock level at source/destination before movement'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('facility', 'sku')},
        ),
        migrations.AddIndex(
            model_name='expirytracker',
            index=models.Index(fields=['item', 'status', 'expiry_date'], name='inventory_e_item_id_7a7087_idx'),
        ),
        migrations.AddIndex(
            model_name='expirytracker',
            index=models.Index(fields=['batch_number'], name='inventory_e_batch_n_c97de3_idx'),
        ),
        migrations.AddIndex(
            model_name='expirytracker',
            index=models.Index(fields=['expiry_date', 'status'], name='inventory_e_expiry__6bb9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['facility', 'sku'], name='inventory_i_facilit_82ddf8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['facility', 'item_type', 'is_active'], name='inventory_i_facilit_5b6178_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['is_controlled_substance'], name='inventory_i_is_cont_885fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category', 'is_active'], name='inventory_i_categor_83e0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', '-timestamp'], name='inventory_s_item_id_149929_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-timestamp'], name='inventory_s_movemen_fccbb9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_storage_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Associated department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_locations', to='core.department'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this storage location', on_delete=django.db.models.deletion.PROTECT, related_name='storage_locations', to='core.facility'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent location for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_storage_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='ward',
            field=models.ForeignKey(blank=True, help_text='Associated ward for ward stores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_locations', to='wards.ward'),
        ),
        migrations.AddField(
            model_name='locationstock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_stocks', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='locationstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='expirytracker',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Storage location for this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_trackers', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Location stock is moving TO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_movements', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_location',
            field=models.ForeignKey(blank=True, help_text='Location stock is moving FROM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_movements', to='inventory.storagelocation'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['facility', 'location_type', 'is_active'], name='inventory_s_facilit_c1b21f_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['facility', 'code'], name='inventory_s_facilit_ef50e9_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['ward'], name='inventory_s_ward_id_7f1615_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['department'], name='inventory_s_departm_3b5899_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together={('facility', 'code')},
        ),
        migrations.AddIndex(
            model_name='locationstock',
            index=models.Index(fields=['location', 'quantity'], name='inventory_l_locatio_575ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstock',
            index=models.Index(fields=['item', 'location'], name='inventory_l_item_id_706167_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationstock',
            unique_together={('item', 'location')},
        ),
        # Indexes that depend on location fields - must come after fields are added
        migrations.AddIndex(
            model_name='expirytracker',
            index=models.Index(fields=['location', 'status', 'expiry_date'], name='inventory_e_locatio_fa5795_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['source_location', '-timestamp'], name='inventory_s_source__031384_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['destination_location', '-timestamp'], name='inventory_s_destina_669ae3_idx'),
        ),
    ]
