# Generated by Django 4.2.10 on 2026-01-24 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_core_singletons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_add_storage_location_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(help_text='Auto-generated: GRN-FACILITY-YYYYMMDD-NNNN', max_length=50, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier_delivery_note', models.CharField(blank=True, help_text="Supplier's delivery note number", max_length=100, null=True)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_inspection', 'Pending Inspection'), ('inspected', 'Inspected'), ('accepted', 'Accepted'), ('partially_accepted', 'Partially Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('has_quality_issues', models.BooleanField(default=False)),
                ('quality_issue_notes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='core.facility')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_grns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(help_text='Auto-generated: PO-FACILITY-YYYYMMDD-NNNN', max_length=50, unique=True)),
                ('supplier_quote_reference', models.CharField(blank=True, help_text="Supplier's quote/reference number", max_length=100, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent to Supplier'), ('acknowledged', 'Acknowledged by Supplier'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30, COD', max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not shared with supplier)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_location', models.ForeignKey(help_text='Location to receive goods', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_purchase_orders', to='inventory.storagelocation')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(help_text='Auto-generated: REQ-FACILITY-YYYYMMDD-NNNN', max_length=50, unique=True)),
                ('date_required', models.DateField(blank=True, help_text='Date by which items are needed', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to PO'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, help_text='Justification for this requisition', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=False, help_text='True if generated by auto-reorder system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='core.facility')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requisitions', to=settings.AUTH_USER_MODEL)),
                ('requesting_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requisitions', to='core.department')),
                ('requesting_location', models.ForeignKey(blank=True, help_text='Location requesting the items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_approved', models.PositiveIntegerField(blank=True, help_text='May differ from requested after approval review', null=True)),
                ('current_stock_at_request', models.PositiveIntegerField(default=0, help_text='Stock level when requisition was created')),
                ('reorder_level', models.PositiveIntegerField(default=0, help_text='Reorder level at time of request')),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_items', to='inventory.inventoryitem')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_items', to='inventory.supplier')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaserequisition')),
            ],
            options={
                'unique_together': {('requisition', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate as percentage', max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
                ('requisition_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='inventory.purchaserequisitionitem')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='GoodsReceivedNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_accepted', models.PositiveIntegerField(default=0)),
                ('quantity_rejected', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_grn_items', to='inventory.expirytracker')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsreceivednote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='inventory.inventoryitem')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='inventory.purchaseorderitem')),
                ('storage_location', models.ForeignKey(blank=True, help_text='Final storage location for accepted goods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_items', to='inventory.storagelocation')),
            ],
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='receiving_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='inventory.storagelocation'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='inventory_p_facilit_cb7b46_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['requisition_number'], name='inventory_p_requisi_890145_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['requested_by', 'status'], name='inventory_p_request_e37c1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'item')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='inventory_p_facilit_9a033e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='inventory_p_po_numb_319f55_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='inventory_p_supplie_80088d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceivednoteitem',
            unique_together={('grn', 'po_item')},
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['facility', 'status', '-received_at'], name='inventory_g_facilit_d3e6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['grn_number'], name='inventory_g_grn_num_6e1353_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['purchase_order'], name='inventory_g_purchas_6d7b11_idx'),
        ),
    ]
