# Generated by Django 4.2.10 on 2026-01-24 19:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_core_singletons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_add_procurement_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(help_text='Auto-generated: INT-FACILITY-YYYYMMDD-NNNN', max_length=50, unique=True)),
                ('date_required', models.DateField(blank=True, help_text='Date by which items are needed', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('partially_fulfilled', 'Partially Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, help_text='Reason for request', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_internal_requisitions', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_requisitions', to='core.facility')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_internal_requisitions', to=settings.AUTH_USER_MODEL)),
                ('fulfilling_location', models.ForeignKey(help_text='Location that will fulfill the request (usually main store)', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_internal_requisitions', to='inventory.storagelocation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_requisitions', to=settings.AUTH_USER_MODEL)),
                ('requesting_location', models.ForeignKey(help_text='Location requesting items', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_internal_requisitions', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this standing order', max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For weekly frequency', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='For monthly frequency (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated', models.DateTimeField(blank=True, help_text='When the last requisition was generated', null=True)),
                ('next_due', models.DateField(blank=True, help_text='Next scheduled generation date', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_standing_orders', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standing_orders', to='core.facility')),
                ('fulfilling_location', models.ForeignKey(help_text='Location that provides the items', on_delete=django.db.models.deletion.PROTECT, related_name='standing_order_fulfillments', to='inventory.storagelocation')),
                ('requesting_location', models.ForeignKey(help_text='Location that receives the items', on_delete=django.db.models.deletion.PROTECT, related_name='standing_order_requests', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(help_text='Auto-generated: TRF-FACILITY-YYYYMMDD-NNNN', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requires_approval', models.BooleanField(default=True, help_text='Does this transfer require approval?')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for transfer', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_transfers', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_requests', to='core.facility')),
                ('from_location', models.ForeignKey(help_text='Source location', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_requests', to='inventory.storagelocation')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_created', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(help_text='Destination location', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_dispatched', models.PositiveIntegerField(default=0, help_text='Quantity actually dispatched')),
                ('quantity_received', models.PositiveIntegerField(default=0, help_text='Quantity received at destination')),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Specific batch to transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_items', to='inventory.expirytracker')),
                ('dispatch_movement', models.ForeignKey(blank=True, help_text='Stock movement for dispatch (transfer_out)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_dispatch_items', to='inventory.stockmovement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.inventoryitem')),
                ('receipt_movement', models.ForeignKey(blank=True, help_text='Stock movement for receipt (transfer_in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_receipt_items', to='inventory.stockmovement')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransferrequest')),
            ],
        ),
        migrations.CreateModel(
            name='StandingOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Standard quantity to request')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standing_order_items', to='inventory.inventoryitem')),
                ('standing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.standingorder')),
            ],
        ),
        migrations.CreateModel(
            name='InternalRequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_approved', models.PositiveIntegerField(blank=True, help_text='Quantity approved (may differ from requested)', null=True)),
                ('quantity_issued', models.PositiveIntegerField(default=0, help_text='Quantity actually issued')),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch_used', models.ForeignKey(blank=True, help_text='Batch used for fulfillment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_requisition_issues', to='inventory.expirytracker')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_requisition_items', to='inventory.inventoryitem')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.internalrequisition')),
            ],
        ),
        migrations.AddField(
            model_name='internalrequisition',
            name='standing_order',
            field=models.ForeignKey(blank=True, help_text='Standing order that generated this requisition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_requisitions', to='inventory.standingorder'),
        ),
        migrations.AddIndex(
            model_name='stocktransferrequest',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='inventory_s_facilit_64b2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferrequest',
            index=models.Index(fields=['transfer_number'], name='inventory_s_transfe_3a6857_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferrequest',
            index=models.Index(fields=['from_location', 'status'], name='inventory_s_from_lo_99c29e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferrequest',
            index=models.Index(fields=['to_location', 'status'], name='inventory_s_to_loca_6080bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktransferitem',
            unique_together={('transfer', 'item', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='standingorderitem',
            unique_together={('standing_order', 'item')},
        ),
        migrations.AddIndex(
            model_name='standingorder',
            index=models.Index(fields=['facility', 'is_active'], name='inventory_s_facilit_19f939_idx'),
        ),
        migrations.AddIndex(
            model_name='standingorder',
            index=models.Index(fields=['next_due', 'is_active'], name='inventory_s_next_du_c44be5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='internalrequisitionitem',
            unique_together={('requisition', 'item')},
        ),
        migrations.AddIndex(
            model_name='internalrequisition',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='inventory_i_facilit_cdc1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='internalrequisition',
            index=models.Index(fields=['requisition_number'], name='inventory_i_requisi_700d94_idx'),
        ),
        migrations.AddIndex(
            model_name='internalrequisition',
            index=models.Index(fields=['requesting_location', 'status'], name='inventory_i_request_8ee8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='internalrequisition',
            index=models.Index(fields=['fulfilling_location', 'status'], name='inventory_i_fulfill_fa4894_idx'),
        ),
        migrations.AddIndex(
            model_name='internalrequisition',
            index=models.Index(fields=['requested_by', 'status'], name='inventory_i_request_4df469_idx'),
        ),
    ]
