# Generated by Django 4.2.10 on 2026-01-24 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_session_ip_and_location'),
        ('clinical_notes', '0014_rename_clinical_n_facility_visibility_idx_clinical_no_facilit_813fc7_idx_and_more'),
        ('core', '0010_seed_core_singletons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_add_internal_logistics_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledSubstanceRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('running_balance', models.PositiveIntegerField(default=0, help_text='Current balance (source of truth)')),
                ('last_entry_at', models.DateTimeField(blank=True, help_text='Timestamp of last entry', null=True)),
                ('last_audit_at', models.DateTimeField(blank=True, help_text='Timestamp of last physical count', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controlled_registers', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_substance_registers', to='core.facility')),
                ('item', models.ForeignKey(help_text='Controlled substance item', on_delete=django.db.models.deletion.PROTECT, related_name='controlled_substance_registers', to='inventory.inventoryitem')),
                ('location', models.ForeignKey(help_text='Storage location for this register', on_delete=django.db.models.deletion.PROTECT, related_name='controlled_substance_registers', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['location__name', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='ControlledSubstanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('receipt', 'Receipt'), ('dispense', 'Dispense'), ('wastage', 'Wastage'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return', 'Return'), ('disposal', 'Disposal')], max_length=20)),
                ('entry_number', models.PositiveIntegerField(help_text='Sequential number within register')),
                ('quantity', models.PositiveIntegerField()),
                ('balance_before', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('wastage_reason', models.TextField(blank=True, help_text='Reason for wastage (if applicable)', null=True)),
                ('wastage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount wasted (if partial dose)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, help_text='Batch used/received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_substance_entries', to='inventory.expirytracker')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient for dispense operations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_substance_entries', to='users.patientprofile')),
                ('performed_by', models.ForeignKey(help_text='Person who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='controlled_entries_performed', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, help_text='Prescription for dispense operations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_substance_entries', to='clinical_notes.prescription')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inventory.controlledsubstanceregister')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_substance_entries', to='inventory.stockmovement')),
                ('witness', models.ForeignKey(help_text='Witness (must be different from performer)', on_delete=django.db.models.deletion.PROTECT, related_name='controlled_entries_witnessed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ControlledSubstanceDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_balance', models.PositiveIntegerField()),
                ('actual_balance', models.PositiveIntegerField()),
                ('discrepancy', models.IntegerField(help_text='Positive = overage, Negative = shortage')),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='reported', max_length=20)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovered_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inventory.controlledsubstanceregister')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceregister',
            index=models.Index(fields=['facility', 'location'], name='inventory_c_facilit_2399b7_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceregister',
            index=models.Index(fields=['facility', 'item'], name='inventory_c_facilit_ad5bda_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceregister',
            index=models.Index(fields=['location', 'item', 'is_active'], name='inventory_c_locatio_597421_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlledsubstanceregister',
            unique_together={('location', 'item')},
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceentry',
            index=models.Index(fields=['register', '-timestamp'], name='inventory_c_registe_53b161_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceentry',
            index=models.Index(fields=['register', 'entry_number'], name='inventory_c_registe_27be10_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceentry',
            index=models.Index(fields=['performed_by', '-timestamp'], name='inventory_c_perform_ad2a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceentry',
            index=models.Index(fields=['witness', '-timestamp'], name='inventory_c_witness_b65f80_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceentry',
            index=models.Index(fields=['patient', '-timestamp'], name='inventory_c_patient_bf4c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledsubstanceentry',
            index=models.Index(fields=['entry_type', '-timestamp'], name='inventory_c_entry_t_fa2b4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlledsubstanceentry',
            unique_together={('register', 'entry_number')},
        ),
        migrations.AddIndex(
            model_name='controlledsubstancediscrepancy',
            index=models.Index(fields=['register', 'status'], name='inventory_c_registe_98d630_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledsubstancediscrepancy',
            index=models.Index(fields=['status', '-discovered_at'], name='inventory_c_status_b5ac6e_idx'),
        ),
    ]
