# Generated by Django 4.2.10 on 2026-02-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_facilitybillingsettings_default_consultation_service_and_more'),
        ('inventory', '0010_add_controlled_substance_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='billing_service',
            field=models.ForeignKey(blank=True, help_text='Optional link to a billable Service for automatic invoicing/claims.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='billing.service'),
        ),
    ]
