# Generated by Django 4.2.10 on 2025-12-11 17:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wards', '0009_add_ward_staff_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_add_user_patient_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monitoring_interval', models.CharField(blank=True, choices=[('15min', 'Every 15 Minutes'), ('30min', 'Every 30 Minutes'), ('hourly', 'Hourly'), ('2hourly', 'Every 2 Hours'), ('4hourly', 'Every 4 Hours'), ('6hourly', 'Every 6 Hours'), ('8hourly', 'Every 8 Hours'), ('shift', 'Per Shift'), ('daily', 'Daily'), ('custom', 'Custom')], help_text='Override template default interval', max_length=20)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why this chart was ordered')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for recording')),
                ('discontinued_at', models.DateTimeField(blank=True, null=True)),
                ('discontinuation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_assignments', to='wards.admission')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chart_assignments', to=settings.AUTH_USER_MODEL)),
                ('discontinued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discontinued_chart_assignments', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_assignments', to='wards.encounter')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_orders', to='users.practitionerprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_assignments', to='users.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='clipboard-list', max_length=50)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('role', 'Same Role'), ('department', 'Department'), ('facility', 'Facility-Wide')], default='private', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('neurological', 'Neurological'), ('cardiovascular', 'Cardiovascular'), ('respiratory', 'Respiratory'), ('metabolic', 'Metabolic'), ('fluid_balance', 'Fluid Balance'), ('pain', 'Pain Assessment'), ('wound', 'Wound Care'), ('infection', 'Infection Control'), ('nutrition', 'Nutrition'), ('mobility', 'Mobility'), ('safety', 'Safety Assessment'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('default_interval', models.CharField(choices=[('15min', 'Every 15 Minutes'), ('30min', 'Every 30 Minutes'), ('hourly', 'Hourly'), ('2hourly', 'Every 2 Hours'), ('4hourly', 'Every 4 Hours'), ('6hourly', 'Every 6 Hours'), ('8hourly', 'Every 8 Hours'), ('shift', 'Per Shift'), ('daily', 'Daily'), ('custom', 'Custom')], default='hourly', max_length=20)),
                ('display_mode', models.CharField(choices=[('table', 'Table View'), ('grid', 'Grid View'), ('timeline', 'Timeline View')], default='table', max_length=20)),
                ('columns_per_page', models.PositiveSmallIntegerField(default=24, help_text='Number of time columns to display (for table/grid view)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System-provided templates cannot be deleted')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chart_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_chart_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChartField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the field', max_length=100)),
                ('field_key', models.CharField(help_text='Internal key for data storage (snake_case)', max_length=50)),
                ('field_type', models.CharField(choices=[('numeric', 'Numeric'), ('select', 'Single Select'), ('multi_select', 'Multi Select'), ('scale', 'Scale'), ('text', 'Text'), ('textarea', 'Text Area'), ('calculated', 'Calculated'), ('paired', 'Paired Fields'), ('time', 'Time'), ('boolean', 'Yes/No')], max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('group_name', models.CharField(blank=True, help_text='Group related fields together', max_length=100)),
                ('help_text', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('show_when', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='charts.charttemplate')),
            ],
            options={
                'ordering': ['template', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChartEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(default=dict)),
                ('has_critical_values', models.BooleanField(default=False)),
                ('critical_fields', models.JSONField(default=list, help_text='List of field_keys with critical values')),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='charts.chartassignment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chart_entries', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_chart_entries', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_chart_entries', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_entries', to='users.practitionerprofile')),
            ],
            options={
                'verbose_name_plural': 'Chart entries',
                'ordering': ['-observation_datetime'],
            },
        ),
        migrations.AddField(
            model_name='chartassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='charts.charttemplate'),
        ),
        migrations.AddIndex(
            model_name='charttemplate',
            index=models.Index(fields=['visibility', 'is_active'], name='charts_char_visibil_5ed912_idx'),
        ),
        migrations.AddIndex(
            model_name='charttemplate',
            index=models.Index(fields=['category', 'is_active'], name='charts_char_categor_d082cf_idx'),
        ),
        migrations.AddIndex(
            model_name='charttemplate',
            index=models.Index(fields=['created_by', 'visibility'], name='charts_char_created_93f614_idx'),
        ),
        migrations.AddIndex(
            model_name='charttemplate',
            index=models.Index(fields=['name'], name='charts_char_name_b17cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='chartfield',
            index=models.Index(fields=['template', 'display_order'], name='charts_char_templat_64f70a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chartfield',
            unique_together={('template', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='chartentry',
            index=models.Index(fields=['assignment', '-observation_datetime'], name='charts_char_assignm_43bf13_idx'),
        ),
        migrations.AddIndex(
            model_name='chartentry',
            index=models.Index(fields=['assignment', 'is_deleted', '-observation_datetime'], name='charts_char_assignm_54d6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='chartentry',
            index=models.Index(fields=['has_critical_values', '-observation_datetime'], name='charts_char_has_cri_667758_idx'),
        ),
        migrations.AddIndex(
            model_name='chartentry',
            index=models.Index(fields=['recorded_by', '-observation_datetime'], name='charts_char_recorde_d01d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='chartassignment',
            index=models.Index(fields=['patient', 'status'], name='charts_char_patient_c898fc_idx'),
        ),
        migrations.AddIndex(
            model_name='chartassignment',
            index=models.Index(fields=['admission', 'status'], name='charts_char_admissi_3f718d_idx'),
        ),
        migrations.AddIndex(
            model_name='chartassignment',
            index=models.Index(fields=['template', 'status'], name='charts_char_templat_983a15_idx'),
        ),
        migrations.AddIndex(
            model_name='chartassignment',
            index=models.Index(fields=['status', '-created_at'], name='charts_char_status_d7bf87_idx'),
        ),
    ]
