# Generated by Django 4.2.10 on 2026-01-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('charts', '0002_chart_template_facility'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='charttemplate',
            new_name='charts_char_facilit_3ad59f_idx',
            old_name='charts_template_facility_visibility_idx',
        ),
        migrations.AlterField(
            model_name='charttemplate',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this chart template', on_delete=django.db.models.deletion.PROTECT, related_name='chart_templates', to='core.facility'),
        ),
    ]
