# Generated by Django 4.2.29 on 2026-04-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_rename_charts_template_facility_visibility_idx_charts_char_facilit_3ad59f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttemplate',
            name='scope_type',
            field=models.CharField(choices=[('encounter', 'Encounter'), ('admission', 'Admission'), ('patient', 'Patient')], default='patient', help_text='Primary clinical scope for assignments and review context', max_length=20),
        ),
        migrations.AddField(
            model_name='charttemplate',
            name='system_key',
            field=models.CharField(blank=True, default='', help_text='Stable key for seeded system templates', max_length=50),
        ),
        migrations.AlterField(
            model_name='chartfield',
            name='field_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('select', 'Single Select'), ('multi_select', 'Multi Select'), ('scale', 'Scale'), ('text', 'Text'), ('textarea', 'Text Area'), ('calculated', 'Calculated'), ('paired', 'Paired Fields'), ('time', 'Time'), ('boolean', 'Yes/No'), ('body_map', 'Body Map')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='charttemplate',
            index=models.Index(fields=['scope_type', 'is_active'], name='charts_char_scope_t_154bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='charttemplate',
            index=models.Index(fields=['facility', 'system_key'], name='charts_char_facilit_db4e95_idx'),
        ),
    ]
