# Generated by Django 4.2.10 on 2025-04-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplate',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
