# Generated by Django 4.2.10 on 2025-11-25 00:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender'),
        ('clinical_notes', '0002_notetemplate_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral (PO)'), ('iv', 'Intravenous (IV)'), ('im', 'Intramuscular (IM)'), ('sc', 'Subcutaneous (SC)'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('sublingual', 'Sublingual (SL)'), ('rectal', 'Rectal (PR)'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic (Ear)'), ('nasal', 'Nasal'), ('transdermal', 'Transdermal'), ('other', 'Other')], default='oral', max_length=20)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Once Daily'), ('bid', 'Twice Daily (BID)'), ('tid', 'Three Times Daily (TID)'), ('qid', 'Four Times Daily (QID)'), ('q4h', 'Every 4 Hours'), ('q6h', 'Every 6 Hours'), ('q8h', 'Every 8 Hours'), ('q12h', 'Every 12 Hours'), ('qhs', 'At Bedtime (QHS)'), ('prn', 'As Needed (PRN)'), ('stat', 'Immediately (STAT)'), ('weekly', 'Weekly'), ('other', 'Other')], default='daily', max_length=20)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('on_hold', 'On Hold'), ('draft', 'Draft')], default='active', max_length=20)),
                ('encounter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discontinued_at', models.DateTimeField(blank=True, null=True)),
                ('discontinue_reason', models.TextField(blank=True)),
                ('discontinued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discontinued_prescriptions', to='users.practitionerprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.patientprofile')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.practitionerprofile')),
            ],
            options={
                'db_table': 'clinical_prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
