# Generated by Django 4.2.10 on 2025-11-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0005_add_local_encounter_model'),
        ('users', '0004_user_gender'),
        ('clinical_notes', '0003_add_prescription_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteentry',
            name='encounter_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='encounter_id',
        ),
        migrations.AddField(
            model_name='noteentry',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='The clinical encounter/visit during which this note was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_entries', to='wards.encounter'),
        ),
        migrations.AddField(
            model_name='noteentry',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='The patient this note is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='The clinical encounter/visit during which this was prescribed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='wards.encounter'),
        ),
        migrations.AddIndex(
            model_name='noteentry',
            index=models.Index(fields=['patient', '-created_at'], name='clinical_no_patient_a5aac0_idx'),
        ),
        migrations.AddIndex(
            model_name='noteentry',
            index=models.Index(fields=['encounter', '-created_at'], name='clinical_no_encount_e38b78_idx'),
        ),
    ]
