# Generated by Django 4.2.10 on 2025-11-25 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_is_public_to_visibility(apps, schema_editor):
    """
    Data migration to convert existing is_public boolean to visibility field.
    - is_public=True -> visibility='public'
    - is_public=False -> visibility='private'
    """
    NoteTemplate = apps.get_model('clinical_notes', 'NoteTemplate')

    # Update templates where is_public=True to visibility='public'
    NoteTemplate.objects.filter(is_public=True).update(visibility='public')

    # Templates with is_public=False keep default visibility='private'


def reverse_migrate_visibility(apps, schema_editor):
    """
    Reverse migration: Convert visibility back to is_public.
    """
    NoteTemplate = apps.get_model('clinical_notes', 'NoteTemplate')

    # Set is_public=True for all public templates
    NoteTemplate.objects.filter(visibility='public').update(is_public=True)
    NoteTemplate.objects.exclude(visibility='public').update(is_public=False)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical_notes', '0005_require_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplate',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('soap', 'SOAP Notes'), ('progress', 'Progress Notes'), ('procedure', 'Procedure Notes'), ('admission', 'Admission Notes'), ('discharge', 'Discharge Notes'), ('nursing', 'Nursing Notes'), ('consultation', 'Consultation Notes'), ('custom', 'Custom')], default='custom', help_text='Category for organizing templates', max_length=50),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='department',
            field=models.CharField(blank=True, help_text='Department for department-level sharing', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='estimated_steps',
            field=models.PositiveIntegerField(default=3, help_text='Number of steps in the workflow'),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='icon',
            field=models.CharField(default='file-text', help_text='Lucide icon name for UI display', max_length=50),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('role', 'Role'), ('department', 'Department'), ('public', 'Public')], default='private', help_text='Controls who can see and use this template', max_length=20),
        ),
        migrations.AlterField(
            model_name='notetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this template. Null for system templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notetemplate',
            name='is_public',
            field=models.BooleanField(default=False, help_text="DEPRECATED: Use 'visibility' field instead"),
        ),
        migrations.AddIndex(
            model_name='notetemplate',
            index=models.Index(fields=['visibility', 'is_active'], name='clinical_no_visibil_8e9fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='notetemplate',
            index=models.Index(fields=['category', 'is_active'], name='clinical_no_categor_9e02ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notetemplate',
            index=models.Index(fields=['created_by', 'visibility'], name='clinical_no_created_1add3a_idx'),
        ),
        # Data migration: Convert is_public to visibility
        migrations.RunPython(
            migrate_is_public_to_visibility,
            reverse_migrate_visibility,
        ),
    ]
