# Generated by Django 4.2.10 on 2025-11-28 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0006_add_template_visibility_and_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteentry',
            name='copied_from',
            field=models.ForeignKey(blank=True, help_text='Source note this was copied from (for audit trail)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='clinical_notes.noteentry'),
        ),
    ]
