# Generated by Django 4.2.10 on 2025-12-01 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical_notes', '0007_add_copied_from_to_noteentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteEntryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number (1 = first version)')),
                ('data', models.JSONField(help_text='Snapshot of the note data at this version')),
                ('edit_reason', models.CharField(blank=True, help_text='Optional reason for the edit', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(help_text='User who made the edit that created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_edits', to=settings.AUTH_USER_MODEL)),
                ('note_entry', models.ForeignKey(help_text='The note entry this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clinical_notes.noteentry')),
            ],
            options={
                'verbose_name': 'Note Entry Version',
                'verbose_name_plural': 'Note Entry Versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['note_entry', '-version_number'], name='clinical_no_note_en_57bdba_idx'), models.Index(fields=['note_entry', '-created_at'], name='clinical_no_note_en_ca38a8_idx')],
                'unique_together': {('note_entry', 'version_number')},
            },
        ),
    ]
