# Generated by Django 4.2.10 on 2025-12-16 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0010_add_admission_status_index'),
        ('users', '0008_remove_user_user_first_name_gin_idx_and_more'),
        ('clinical_notes', '0008_add_note_entry_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('note', 'Clinical Note'), ('prescription', 'Prescription'), ('vitals', 'Vital Signs'), ('lab', 'Lab Order'), ('referral', 'Referral'), ('fluid', 'Fluid Balance')], db_index=True, max_length=20)),
                ('event_subtype', models.CharField(blank=True, help_text="E.g., 'soap_note', 'admission_note' for notes", max_length=50)),
                ('source_model', models.CharField(help_text="Model name: 'NoteEntry', 'Prescription', etc.", max_length=50)),
                ('source_id', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('content_summary', models.CharField(blank=True, help_text='Short summary for search/preview', max_length=500)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('has_edits', models.BooleanField(default=False)),
                ('version_count', models.PositiveIntegerField(default=0)),
                ('template_id', models.UUIDField(blank=True, null=True)),
                ('template_title', models.CharField(blank=True, max_length=100)),
                ('search_text', models.TextField(blank=True, help_text='Concatenated searchable text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='wards.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='users.patientprofile')),
            ],
            options={
                'db_table': 'clinical_timeline_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', '-timestamp'], name='clinical_ti_patient_f79e1f_idx'), models.Index(fields=['patient', 'event_type', '-timestamp'], name='clinical_ti_patient_1fe0ff_idx'), models.Index(fields=['source_model', 'source_id'], name='clinical_ti_source__205ce7_idx')],
                'unique_together': {('source_model', 'source_id')},
            },
        ),
    ]
