# Generated by Codex on 2025-01-01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('clinical_notes', '0009_timeline_event'),
    ]

    operations = [
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "clinical_rx_patient_status_end_idx "
                "ON clinical_prescriptions (patient_id, status, end_date);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS clinical_rx_patient_status_end_idx;"
            ),
        ),
    ]
