# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_clinical_note_facilities(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    NoteEntry = apps.get_model('clinical_notes', 'NoteEntry')
    NoteEntryVersion = apps.get_model('clinical_notes', 'NoteEntryVersion')
    Prescription = apps.get_model('clinical_notes', 'Prescription')

    fallback = _get_fallback_facility(Facility)

    def _assign_facility(model, queryset, resolver, label):
        items = list(queryset)
        for item in items:
            facility = resolver(item)
            if not facility and fallback:
                facility = fallback
            if facility:
                item.facility_id = facility.id
        if items:
            model.objects.bulk_update(items, ['facility'])
        if model.objects.filter(facility__isnull=True).exists():
            raise RuntimeError(
                f"{label} facility backfill incomplete. "
                "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
            )

    _assign_facility(
        NoteEntry,
        NoteEntry.objects.filter(facility__isnull=True)
        .select_related('encounter__facility', 'patient__facility'),
        lambda obj: (
            obj.encounter.facility
            if obj.encounter_id and getattr(obj.encounter, 'facility_id', None)
            else (obj.patient.facility if obj.patient_id else None)
        ),
        'NoteEntry',
    )

    _assign_facility(
        NoteEntryVersion,
        NoteEntryVersion.objects.filter(facility__isnull=True)
        .select_related('note_entry__facility'),
        lambda obj: obj.note_entry.facility if obj.note_entry_id else None,
        'NoteEntryVersion',
    )

    _assign_facility(
        Prescription,
        Prescription.objects.filter(facility__isnull=True)
        .select_related('encounter__facility', 'patient__facility'),
        lambda obj: (
            obj.encounter.facility
            if obj.encounter_id and getattr(obj.encounter, 'facility_id', None)
            else (obj.patient.facility if obj.patient_id else None)
        ),
        'Prescription',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('encounters', '0002_add_facility_scoping'),
        ('clinical_notes', '0010_prescription_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteentry',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='note_entries',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='noteentryversion',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='note_entry_versions',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='prescription',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='prescriptions',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_clinical_note_facilities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='noteentry',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='note_entries',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='noteentryversion',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='note_entry_versions',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='prescriptions',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='noteentry',
            index=models.Index(fields=['facility', '-created_at'], name='clinical_notes_facility_created_idx'),
        ),
        migrations.AddIndex(
            model_name='noteentryversion',
            index=models.Index(fields=['facility', 'note_entry', '-created_at'], name='clinical_notes_version_facility_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='clinical_rx_facility_status_idx'),
        ),
    ]
