# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('clinical_notes', '0011_facility_scoping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='noteentry',
            new_name='clinical_no_facilit_1d458d_idx',
            old_name='clinical_notes_facility_created_idx',
        ),
        migrations.RenameIndex(
            model_name='noteentryversion',
            new_name='clinical_no_facilit_42c1c0_idx',
            old_name='clinical_notes_version_facility_idx',
        ),
        migrations.RenameIndex(
            model_name='prescription',
            new_name='clinical_pr_facilit_a5eeda_idx',
            old_name='clinical_rx_facility_status_idx',
        ),
        migrations.AlterField(
            model_name='noteentry',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this clinical note', on_delete=django.db.models.deletion.PROTECT, related_name='note_entries', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='noteentryversion',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this note entry version', on_delete=django.db.models.deletion.PROTECT, related_name='note_entry_versions', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this prescription', on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.facility'),
        ),
    ]
