# Generated by Django 4.2.10 on 2026-01-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('clinical_notes', '0013_note_template_facility'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notetemplate',
            new_name='clinical_no_facilit_813fc7_idx',
            old_name='clinical_n_facility_visibility_idx',
        ),
        migrations.AlterField(
            model_name='notetemplate',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this note template', on_delete=django.db.models.deletion.PROTECT, related_name='note_templates', to='core.facility'),
        ),
    ]
