# Generated by Django 4.2.10 on 2026-02-16 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import uuid


def _get_sections(structure):
    if isinstance(structure, dict):
        sections = structure.get('sections', [])
    elif isinstance(structure, list):
        sections = structure
    else:
        sections = []
    return sections if isinstance(sections, list) else []


def _normalize_structure(structure):
    normalized_sections = []
    for section in _get_sections(structure):
        if not isinstance(section, dict):
            continue
        section_name = (section.get('name') or section.get('section') or '').strip()
        if not section_name:
            continue

        normalized_section = {
            'id': section.get('id') or section_name.lower().replace(' ', '_'),
            'name': section_name,
            'type': section.get('type') or 'text',
            'required': bool(section.get('required', False)),
        }

        observation_type = section.get('observationType') or section.get('observation_type')
        if observation_type:
            normalized_section['observationType'] = str(observation_type)

        default_text = section.get('default_text') or section.get('defaultText')
        if default_text:
            normalized_section['default_text'] = str(default_text)

        subsections = section.get('subsections') if isinstance(section.get('subsections'), list) else []
        if subsections:
            normalized_subsections = []
            for subsection in subsections:
                if not isinstance(subsection, dict):
                    continue
                subsection_name = (subsection.get('name') or '').strip()
                if not subsection_name:
                    continue
                normalized_subsection = {
                    'name': subsection_name,
                    'type': subsection.get('type') or 'text',
                    'required': bool(subsection.get('required', False)),
                }
                subsection_observation = subsection.get('observationType') or subsection.get('observation_type')
                if subsection_observation:
                    normalized_subsection['observationType'] = str(subsection_observation)
                subsection_default_text = subsection.get('default_text') or subsection.get('defaultText')
                if subsection_default_text:
                    normalized_subsection['default_text'] = str(subsection_default_text)
                normalized_subsections.append(normalized_subsection)
            if normalized_subsections:
                normalized_section['subsections'] = normalized_subsections

        normalized_sections.append(normalized_section)

    return {
        'schema_version': 2,
        'sections': normalized_sections,
    }


def _infer_mode(structure):
    sections = _get_sections(structure)
    has_default_text = False
    has_structured_or_non_text = False
    for section in sections:
        if not isinstance(section, dict):
            continue
        if section.get('default_text') or section.get('defaultText'):
            has_default_text = True
        section_type = (section.get('type') or 'text').lower()
        if section_type not in {'text', 'textarea'} or section.get('subsections'):
            has_structured_or_non_text = True
        for subsection in section.get('subsections', []) or []:
            if isinstance(subsection, dict) and (subsection.get('default_text') or subsection.get('defaultText')):
                has_default_text = True

    if not has_default_text:
        return 'structured'
    return 'hybrid' if has_structured_or_non_text else 'written'


def backfill_template_revisions(apps, schema_editor):
    NoteTemplate = apps.get_model('clinical_notes', 'NoteTemplate')
    NoteTemplateRevision = apps.get_model('clinical_notes', 'NoteTemplateRevision')
    NoteEntry = apps.get_model('clinical_notes', 'NoteEntry')
    db_alias = schema_editor.connection.alias
    now = timezone.now()

    templates = NoteTemplate.objects.using(db_alias).all().iterator()
    for template in templates:
        normalized_structure = _normalize_structure(template.structure)
        revision = NoteTemplateRevision.objects.using(db_alias).create(
            template_id=template.id,
            facility_id=template.facility_id,
            version=1,
            status='published',
            mode=_infer_mode(normalized_structure),
            content=normalized_structure,
            created_by_id=template.created_by_id,
            published_by_id=template.created_by_id,
            published_at=now,
        )
        NoteTemplate.objects.using(db_alias).filter(id=template.id).update(structure=normalized_structure)
        NoteEntry.objects.using(db_alias).filter(template_id=template.id).update(
            template_revision_id=revision.id,
            template_version=revision.version,
        )


def reverse_backfill_template_revisions(apps, schema_editor):
    NoteEntry = apps.get_model('clinical_notes', 'NoteEntry')
    NoteTemplateRevision = apps.get_model('clinical_notes', 'NoteTemplateRevision')
    db_alias = schema_editor.connection.alias
    NoteEntry.objects.using(db_alias).update(template_revision_id=None, template_version=None)
    NoteTemplateRevision.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_seed_core_singletons'),
        ('clinical_notes', '0014_rename_clinical_n_facility_visibility_idx_clinical_no_facilit_813fc7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplateRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('mode', models.CharField(choices=[('structured', 'Structured'), ('written', 'Written'), ('hybrid', 'Hybrid')], default='structured', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='noteentry',
            name='template_version',
            field=models.PositiveIntegerField(blank=True, help_text='Template revision version used at note creation.', null=True),
        ),
        migrations.AddIndex(
            model_name='noteentry',
            index=models.Index(fields=['facility', 'template', '-created_at'], name='clinical_no_facilit_600963_idx'),
        ),
        migrations.AddField(
            model_name='notetemplaterevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_note_template_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notetemplaterevision',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_template_revisions', to='core.facility'),
        ),
        migrations.AddField(
            model_name='notetemplaterevision',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_note_template_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notetemplaterevision',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_note_template_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notetemplaterevision',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='clinical_notes.notetemplate'),
        ),
        migrations.AddField(
            model_name='noteentry',
            name='template_revision',
            field=models.ForeignKey(blank=True, help_text='Immutable template revision used to initialize this note.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='clinical_notes.notetemplaterevision'),
        ),
        migrations.RunPython(backfill_template_revisions, reverse_backfill_template_revisions),
        migrations.AddIndex(
            model_name='notetemplaterevision',
            index=models.Index(fields=['template', 'status', '-version'], name='clinical_no_templat_3395fd_idx'),
        ),
        migrations.AddIndex(
            model_name='notetemplaterevision',
            index=models.Index(fields=['facility', 'status'], name='clinical_no_facilit_558831_idx'),
        ),
        migrations.AddConstraint(
            model_name='notetemplaterevision',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='clinical_notes_template_revision_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notetemplaterevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('template',), name='clinical_notes_one_published_revision_per_template'),
        ),
    ]
