# Generated by Codex on 2026-03-06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0006_enable_pg_trgm'),
        ('clinical_notes', '0015_notetemplaterevision_noteentry_template_version_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "clinical_timeline_title_trgm_idx "
                "ON clinical_timeline_events USING gin (title gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS clinical_timeline_title_trgm_idx;"
            ),
        ),
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "clinical_timeline_summary_trgm_idx "
                "ON clinical_timeline_events USING gin (content_summary gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS clinical_timeline_summary_trgm_idx;"
            ),
        ),
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "clinical_timeline_search_text_trgm_idx "
                "ON clinical_timeline_events USING gin (search_text gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS clinical_timeline_search_text_trgm_idx;"
            ),
        ),
    ]
