# Generated by Django 4.2.29 on 2026-03-22 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0001_initial'),
        ('clinical_notes', '0016_timeline_event_trigram_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='discharge_case',
            field=models.ForeignKey(blank=True, help_text='Optional discharge case for take-home discharge medications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='discharge.dischargecase'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['discharge_case', 'status'], name='clinical_pr_dischar_8c3a78_idx'),
        ),
    ]
