# Generated by Django 4.2.29 on 2026-04-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0017_prescription_discharge_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('note', 'Clinical Note'), ('prescription', 'Prescription'), ('vitals', 'Vital Signs'), ('lab', 'Lab Order'), ('referral', 'Referral'), ('fluid', 'Fluid Balance'), ('chart', 'Clinical Chart')], db_index=True, max_length=20),
        ),
    ]
