# Generated by Django 4.2.10 on 2025-11-26 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_passwordresettoken'),
        ('wards', '0005_add_local_encounter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_number', models.CharField(help_text='Unique referral identifier (auto-generated)', max_length=20, unique=True)),
                ('referring_department', models.CharField(blank=True, help_text='Department of referring provider', max_length=100)),
                ('referred_to_department', models.CharField(help_text="Target department (e.g., 'Cardiology', 'Orthopedics')", max_length=100)),
                ('referred_to_specialty', models.CharField(help_text='Target specialty', max_length=100)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Acceptance'), ('accepted', 'Accepted'), ('scheduled', 'Appointment Scheduled'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reason', models.TextField(help_text='Primary reason for referral')),
                ('clinical_summary', models.TextField(blank=True, help_text='Relevant clinical history and findings')),
                ('questions_for_specialist', models.TextField(blank=True, help_text='Specific questions or consultation requests')),
                ('specialist_notes', models.TextField(blank=True, help_text="Specialist's notes and findings")),
                ('recommendations', models.TextField(blank=True, help_text="Specialist's recommendations back to referring provider")),
                ('scheduled_appointment_id', models.CharField(blank=True, help_text='Linked appointment ID (can be FHIR Appointment ID or local ID)', max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When referral was submitted', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When specialist accepted the referral', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When consultation/referral was completed', null=True)),
                ('declined_at', models.DateTimeField(blank=True, help_text='When specialist declined the referral', null=True)),
                ('decline_reason', models.TextField(blank=True, help_text='Reason for declining (if applicable)')),
                ('fhir_id', models.CharField(blank=True, help_text='FHIR ServiceRequest resource ID', max_length=100, null=True, unique=True)),
                ('fhir_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, help_text='Encounter during which referral was made', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='encounters.Encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='users.patientprofile')),
                ('referred_to_provider', models.ForeignKey(blank=True, help_text='Specific specialist (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to='users.practitionerprofile')),
                ('referring_provider', models.ForeignKey(help_text='Provider making the referral', on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='users.practitionerprofile')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='referrals_r_patient_fc132b_idx'), models.Index(fields=['referral_number'], name='referrals_r_referra_13ce98_idx'), models.Index(fields=['referring_provider', 'status'], name='referrals_r_referri_3911a6_idx'), models.Index(fields=['referred_to_provider', 'status'], name='referrals_r_referre_c38e8d_idx'), models.Index(fields=['referred_to_department', 'status'], name='referrals_r_referre_d2512c_idx'), models.Index(fields=['urgency', 'status'], name='referrals_r_urgency_5a0648_idx'), models.Index(fields=['submitted_at'], name='referrals_r_submitt_79a83c_idx')],
            },
        ),
    ]
