# Generated by Django 4.2.10 on 2025-11-26 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_wardroundworkflow_dischargeworkflow_and_more'),
        ('wards', '0005_add_local_encounter_model'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='consultation_encounter',
            field=models.ForeignKey(blank=True, help_text='Encounter created for specialist consultation (for OPD referrals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_referrals', to='wards.encounter'),
        ),
        migrations.AddField(
            model_name='referral',
            name='consultation_workflow',
            field=models.ForeignKey(blank=True, help_text='Consultation workflow created for this referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='workflows.clinicalworkflow'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('opd', 'Outpatient')], default='opd', help_text='Type of referral - determines encounter handling', max_length=20),
        ),
    ]
