# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_referral_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    Referral = apps.get_model('referrals', 'Referral')

    fallback = _get_fallback_facility(Facility)

    referrals = list(
        Referral.objects.filter(facility__isnull=True)
        .select_related('patient__facility', 'encounter__facility')
    )

    for referral in referrals:
        facility = None
        if referral.patient_id and getattr(referral.patient, 'facility_id', None):
            facility = referral.patient.facility
        elif referral.encounter_id and getattr(referral.encounter, 'facility_id', None):
            facility = referral.encounter.facility
        if not facility and fallback:
            facility = fallback
        if facility:
            referral.facility_id = facility.id

    if referrals:
        Referral.objects.bulk_update(referrals, ['facility'])

    if Referral.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "Referral facility backfill incomplete. "
            "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('encounters', '0002_add_facility_scoping'),
        ('referrals', '0002_add_referral_consultation_linkage'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='referrals',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_referral_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='referral',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='referrals',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['facility', 'status'], name='referrals_facility_status_idx'),
        ),
    ]
