# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('referrals', '0003_facility_scoping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referral',
            new_name='referrals_r_facilit_c3ded5_idx',
            old_name='referrals_facility_status_idx',
        ),
        migrations.AlterField(
            model_name='referral',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this referral', on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='core.facility'),
        ),
    ]
