# Generated by Django 4.2.10 on 2026-01-17 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_facility_status_fields'),
        ('referrals', '0004_rename_referrals_facility_status_idx_referrals_r_facilit_c3ded5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Acceptance'), ('accepted', 'Accepted'), ('scheduled', 'Appointment Scheduled'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=20)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_notifications', to='core.facility')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_notifications', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='referrals.referral')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='referrals_r_recipie_8507c6_idx'), models.Index(fields=['facility', '-created_at'], name='referrals_r_facilit_9dc310_idx'), models.Index(fields=['event', '-created_at'], name='referrals_r_event_183eab_idx')],
            },
        ),
    ]
