# Generated by Django 4.2.10 on 2026-02-08 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_trigram_indexes_for_patient_search'),
        ('appointments', '0013_appointment_assigned_at_and_more'),
        ('core', '0010_seed_core_singletons'),
        ('organization', '0021_clinic_assignment_timing_clinic_booking_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0005_referralnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSLAEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('threshold_50', '50% Threshold'), ('threshold_75', '75% Threshold'), ('threshold_90', '90% Threshold'), ('breach', 'SLA Breach')], max_length=20)),
                ('consumed_percent', models.PositiveSmallIntegerField(default=0)),
                ('target_hours', models.PositiveIntegerField(default=0)),
                ('remaining_hours', models.IntegerField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_sla_events', to='core.facility')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_events', to='referrals.referral')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicWaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_start_time', models.DateTimeField()),
                ('requested_end_time', models.DateTimeField()),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('deadline_risk', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green'), ('none', 'None')], default='none', max_length=12)),
                ('vulnerability_flag', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('offered', 'Offer Sent'), ('promoted', 'Promoted to Booking'), ('expired', 'Offer Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('source', models.CharField(choices=[('booking', 'Booking Full'), ('referral', 'Referral'), ('manual', 'Manual Entry'), ('walk_in', 'Walk-In')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('wait_started_at', models.DateTimeField(auto_now_add=True)),
                ('offer_sent_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='organization.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinic_waitlist_entries', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_waitlist_entries', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_waitlist_entries', to='users.patientprofile')),
                ('preferred_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_waitlist_entries', to='users.practitionerprofile')),
                ('promoted_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_waitlist_entries', to='appointments.appointment')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='referrals.referral')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clinic_waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['wait_started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referred_to_department', models.CharField(blank=True, default='', help_text='Optional department-specific override. Blank means facility-wide default.', max_length=100)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], max_length=20)),
                ('target_hours', models.PositiveIntegerField(help_text='Target time to first consult in hours.')),
                ('warning_thresholds', models.JSONField(blank=True, default=list, help_text='Percentage thresholds for alerts, e.g. [50, 75, 90].')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referral_sla_policies', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_sla_policies', to='core.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_referral_sla_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['facility_id', 'referred_to_department', 'urgency'],
                'indexes': [models.Index(fields=['facility', 'is_active'], name='referrals_r_facilit_00a40a_idx'), models.Index(fields=['facility', 'urgency', 'is_active'], name='referrals_r_facilit_df9f51_idx'), models.Index(fields=['facility', 'referred_to_department', 'is_active'], name='referrals_r_facilit_481465_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='referralslapolicy',
            constraint=models.UniqueConstraint(fields=('facility', 'referred_to_department', 'urgency'), name='unique_referral_sla_policy_scope'),
        ),
        migrations.AddIndex(
            model_name='referralslaevent',
            index=models.Index(fields=['facility', 'event_type', '-triggered_at'], name='referrals_r_facilit_6ed93a_idx'),
        ),
        migrations.AddIndex(
            model_name='referralslaevent',
            index=models.Index(fields=['referral', '-triggered_at'], name='referrals_r_referra_1e08a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralslaevent',
            constraint=models.UniqueConstraint(fields=('referral', 'event_type'), name='unique_referral_sla_event_once'),
        ),
        migrations.AddIndex(
            model_name='clinicwaitlistentry',
            index=models.Index(fields=['facility', 'status', 'wait_started_at'], name='referrals_c_facilit_8b35ed_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicwaitlistentry',
            index=models.Index(fields=['clinic', 'status', 'wait_started_at'], name='referrals_c_clinic__30eb4d_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicwaitlistentry',
            index=models.Index(fields=['patient', 'status'], name='referrals_c_patient_9ba5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicwaitlistentry',
            index=models.Index(fields=['referral', 'status'], name='referrals_c_referra_d37a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicwaitlistentry',
            index=models.Index(fields=['urgency', 'deadline_risk', 'vulnerability_flag'], name='referrals_c_urgency_7be16a_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicwaitlistentry',
            constraint=models.CheckConstraint(check=models.Q(('requested_start_time__lt', models.F('requested_end_time'))), name='clinic_waitlist_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='clinicwaitlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'offered'])), fields=('clinic', 'patient'), name='unique_active_waitlist_per_clinic_patient'),
        ),
    ]
