# Generated by Django 4.2.29 on 2026-05-02 02:15

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0011_lab_search_trigram_indexes'),
        ('users', '0027_search_index'),
        ('clinical_notes', '0018_alter_timelineevent_event_type'),
        ('encounters', '0012_search_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_feature_entitlement_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('free_text_label', models.CharField(blank=True, help_text='Required when code is null. Flagged for later coding.', max_length=512)),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved'), ('remission', 'In Remission'), ('recurrence', 'Recurrence')], default='active', max_length=20)),
                ('verification_status', models.CharField(choices=[('provisional', 'Provisional'), ('differential', 'Differential'), ('confirmed', 'Confirmed'), ('refuted', 'Refuted'), ('entered-in-error', 'Entered in Error')], default='provisional', max_length=24)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('chronicity', models.CharField(choices=[('acute', 'Acute'), ('chronic', 'Chronic'), ('unspecified', 'Unspecified')], default='unspecified', max_length=16)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('abatement_date', models.DateField(blank=True, null=True)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Free-text clinical note about this problem.')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fhir_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fhir_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved'), ('remission', 'In Remission'), ('recurrence', 'Recurrence')], max_length=20)),
                ('to_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved'), ('remission', 'In Remission'), ('recurrence', 'Recurrence')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_status_events', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='problems.problem')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_links', to='encounters.encounter')),
                ('lab_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_links', to='laboratory.laborder')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_links_created', to=settings.AUTH_USER_MODEL)),
                ('note_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_links', to='clinical_notes.noteentry')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_links', to='clinical_notes.prescription')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('code_system', models.CharField(choices=[('icd10-who', 'WHO ICD-10'), ('icd10-cm', 'ICD-10-CM (US)'), ('icd11', 'WHO ICD-11'), ('snomed', 'SNOMED CT'), ('ghana-quickpick', 'Ghana Quick Pick'), ('local', 'Local / Free Text')], max_length=32)),
                ('display', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('symptom', 'Symptom'), ('finding', 'Clinical Finding'), ('procedure-history', 'Procedure History'), ('social', 'Social'), ('family-history', 'Family History'), ('other', 'Other')], default='diagnosis', max_length=32)),
                ('is_chronic_default', models.BooleanField(default=False, help_text="Hint for UI: pre-select 'chronic' status when this code is picked.")),
                ('is_quick_pick', models.BooleanField(db_index=True, default=False, help_text='Surface at top of search results (Ghana common conditions).')),
                ('quick_pick_rank', models.PositiveSmallIntegerField(default=0, help_text='Lower = higher in quick-pick ordering. Ignored if is_quick_pick is False.')),
                ('parent_code', models.CharField(blank=True, help_text='Parent code in same code_system (for hierarchy navigation).', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('needs_clinical_review', models.BooleanField(default=False, help_text='True for seed entries pending clinician sign-off.')),
                ('source_release', models.CharField(blank=True, help_text="e.g. 'WHO-ICD10-2019' for re-import tracking.", max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code_system', 'code'],
                'indexes': [models.Index(fields=['code_system', 'is_active'], name='problems_pr_code_sy_2142c1_idx'), models.Index(fields=['is_quick_pick', 'quick_pick_rank'], name='problems_pr_is_quic_5329bd_idx'), models.Index(fields=['category', 'is_active'], name='problems_pr_categor_dc9ba2_idx'), django.contrib.postgres.indexes.GinIndex(fields=['display'], name='problem_code_display_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddConstraint(
            model_name='problemcode',
            constraint=models.UniqueConstraint(fields=('code_system', 'code'), name='problems_code_system_code_unique'),
        ),
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='problems.problemcode'),
        ),
        migrations.AddField(
            model_name='problem',
            name='facility',
            field=models.ForeignKey(help_text='Facility where the problem was first recorded.', on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='core.facility'),
        ),
        migrations.AddField(
            model_name='problem',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='problem',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='problemstatusevent',
            index=models.Index(fields=['problem', '-changed_at'], name='problems_pr_problem_32f46d_idx'),
        ),
        migrations.AddIndex(
            model_name='problemlink',
            index=models.Index(fields=['problem', '-linked_at'], name='problems_pr_problem_8cf256_idx'),
        ),
        migrations.AddIndex(
            model_name='problemlink',
            index=models.Index(fields=['note_entry'], name='problems_pr_note_en_e4724a_idx'),
        ),
        migrations.AddIndex(
            model_name='problemlink',
            index=models.Index(fields=['prescription'], name='problems_pr_prescri_10e07f_idx'),
        ),
        migrations.AddIndex(
            model_name='problemlink',
            index=models.Index(fields=['lab_order'], name='problems_pr_lab_ord_b38347_idx'),
        ),
        migrations.AddIndex(
            model_name='problemlink',
            index=models.Index(fields=['encounter'], name='problems_pr_encount_0f3c24_idx'),
        ),
        migrations.AddConstraint(
            model_name='problemlink',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('encounter__isnull', True), ('lab_order__isnull', True), ('note_entry__isnull', False), ('prescription__isnull', True)), models.Q(('encounter__isnull', True), ('lab_order__isnull', True), ('note_entry__isnull', True), ('prescription__isnull', False)), models.Q(('encounter__isnull', True), ('lab_order__isnull', False), ('note_entry__isnull', True), ('prescription__isnull', True)), models.Q(('encounter__isnull', False), ('lab_order__isnull', True), ('note_entry__isnull', True), ('prescription__isnull', True)), _connector='OR'), name='problems_link_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='problemlink',
            constraint=models.UniqueConstraint(condition=models.Q(('note_entry__isnull', False)), fields=('problem', 'note_entry'), name='problems_link_problem_note_unique'),
        ),
        migrations.AddConstraint(
            model_name='problemlink',
            constraint=models.UniqueConstraint(condition=models.Q(('prescription__isnull', False)), fields=('problem', 'prescription'), name='problems_link_problem_rx_unique'),
        ),
        migrations.AddConstraint(
            model_name='problemlink',
            constraint=models.UniqueConstraint(condition=models.Q(('lab_order__isnull', False)), fields=('problem', 'lab_order'), name='problems_link_problem_lab_unique'),
        ),
        migrations.AddConstraint(
            model_name='problemlink',
            constraint=models.UniqueConstraint(condition=models.Q(('encounter__isnull', False)), fields=('problem', 'encounter'), name='problems_link_problem_enc_unique'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['patient', 'clinical_status'], name='problems_pr_patient_8c211f_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['patient', '-recorded_at'], name='problems_pr_patient_a8ae24_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['facility', 'clinical_status'], name='problems_pr_facilit_569cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['code'], name='problems_pr_code_id_039ef7_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.CheckConstraint(check=models.Q(('code__isnull', False), models.Q(('free_text_label', ''), _negated=True), _connector='OR'), name='problems_problem_has_code_or_free_text'),
        ),
    ]
