import Heart from 'lucide-react/dist/esm/icons/heart.js';
import Clock from 'lucide-react/dist/esm/icons/clock.js';
import User from 'lucide-react/dist/esm/icons/user.js';
import Sparkles from 'lucide-react/dist/esm/icons/sparkles.js';
import Loader2 from 'lucide-react/dist/esm/icons/loader-circle.js';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const DEFAULT_EMPTY_ARRAY = [];

import { getShiftOptions } from '@/config/shiftConfig';

/**
 * ClinicalInfoStep - Clinical status and handoff details
 */
export function ClinicalInfoStep({
  formData,
  onChange,
  nurses = DEFAULT_EMPTY_ARRAY,
  nursesLoading = false,
  selectedPatient,
  isAutoGenerated = false,
  nurseScopeNotice = null
}) {
  const shiftOptions = getShiftOptions();

  return (
    <div className="space-y-6">
      {/* Patient Context */}
      {selectedPatient && (
        <div className="p-4 rounded-xl bg-muted/50 border border-border">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-amber-500/10">
              <User className="size-5 text-amber-600" />
            </div>
            <div>
              <p className="font-display text-lg font-medium">{selectedPatient.patient_name}</p>
              <p className="font-mono text-xs text-muted-foreground">
                {selectedPatient.ward_name} - Bed {selectedPatient.bed_number}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Shift & Nurse Selection */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-2">
          <Label className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
            <Clock className="inline size-3 mr-1" />
            Shift Type *
          </Label>
          <Select
            value={formData.shift_type}
            onValueChange={(value) => onChange('shift_type', value)}
          >
            <SelectTrigger className="font-mono">
              <SelectValue placeholder="Select shift" />
            </SelectTrigger>
            <SelectContent>
              {shiftOptions.map((shift) => (
                <SelectItem key={shift.value} value={shift.value} className="font-mono">
                  {shift.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
            <User className="inline size-3 mr-1" />
            Receiving Nurse *
          </Label>
          <Select
            value={formData.to_nurse}
            onValueChange={(value) => onChange('to_nurse', value)}
            disabled={nursesLoading || !selectedPatient}
          >
            <SelectTrigger className="font-mono">
              <SelectValue placeholder={nursesLoading ? "Loading nurses..." : "Select nurse"} />
            </SelectTrigger>
            <SelectContent>
              {nursesLoading ? (
                <div className="p-2 text-sm text-muted-foreground font-mono flex items-center gap-2">
                  <Loader2 className="size-4 animate-spin" />
                  Loading ward nurses…
                </div>
              ) : nurses.length === 0 ? (
                <div className="p-2 text-sm text-muted-foreground font-mono">
                  {selectedPatient?.ward_name
                    ? `No nurses assigned to ${selectedPatient.ward_name}`
                    : 'Select a patient first'}
                </div>
              ) : (
                nurses.map((nurse) => (
                  <SelectItem key={nurse.id} value={String(nurse.id)} className="font-mono">
                    {nurse.full_name || nurse.name} {nurse.role_name && `(${nurse.role_name})`}
                  </SelectItem>
                ))
              )}
            </SelectContent>
          </Select>
          {nurseScopeNotice && (
            <p className="text-xs text-muted-foreground">
              {nurseScopeNotice}
            </p>
          )}
        </div>
      </div>

      {/* Patient Condition */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
            <Heart className="inline size-3 mr-1" />
            Patient Condition *
          </Label>
          {isAutoGenerated && formData.patient_condition && (
            <Badge variant="outline" className="font-mono text-[10px] text-sky-600 border-sky-500/30 bg-sky-500/5">
              <Sparkles className="size-3 mr-1" />
              Auto-generated
            </Badge>
          )}
        </div>
        <p className="text-xs text-muted-foreground mb-2">
          Current status, vital signs trends, level of consciousness
        </p>
        <Textarea
          placeholder="Describe the patient's current condition..."
          value={formData.patient_condition}
          onChange={(e) => onChange('patient_condition', e.target.value)}
          rows={5}
          className="font-mono text-sm"
        />
      </div>

      {/* Ongoing Issues */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
            Ongoing Issues
          </Label>
          {isAutoGenerated && formData.ongoing_issues && (
            <Badge variant="outline" className="font-mono text-[10px] text-sky-600 border-sky-500/30 bg-sky-500/5">
              <Sparkles className="size-3 mr-1" />
              Auto-generated
            </Badge>
          )}
        </div>
        <p className="text-xs text-muted-foreground mb-2">
          Active problems, complications, or concerns
        </p>
        <Textarea
          placeholder="List any ongoing issues..."
          value={formData.ongoing_issues}
          onChange={(e) => onChange('ongoing_issues', e.target.value)}
          rows={3}
          className="font-mono text-sm"
        />
      </div>

      {/* Medication Changes */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
            Medication Changes
          </Label>
          {isAutoGenerated && formData.medication_changes && (
            <Badge variant="outline" className="font-mono text-[10px] text-sky-600 border-sky-500/30 bg-sky-500/5">
              <Sparkles className="size-3 mr-1" />
              Auto-generated
            </Badge>
          )}
        </div>
        <p className="text-xs text-muted-foreground mb-2">
          Recent additions, discontinuations, or dose changes
        </p>
        <Textarea
          placeholder="Note any medication changes..."
          value={formData.medication_changes}
          onChange={(e) => onChange('medication_changes', e.target.value)}
          rows={3}
          className="font-mono text-sm"
        />
      </div>
    </div>
  );
}
