import { PatientSelectStep } from './PatientSelectStep';
import { ClinicalInfoStep } from './ClinicalInfoStep';
import { TasksEventsStep } from './TasksEventsStep';
import { ReviewStep } from './ReviewStep';

export function ShiftHandoffStepContent({
  currentStep,
  patients,
  patientsLoading,
  selectedPatient,
  onSelectPatient,
  searchTerm,
  onSearchChange,
  formData,
  onFieldChange,
  nurses,
  nursesLoading,
  isAutoGenerated,
  nurseScopeNotice,
}) {
  switch (currentStep) {
    case 1:
      return (
        <PatientSelectStep
          patients={patients}
          isLoading={patientsLoading}
          selectedPatient={selectedPatient}
          onSelectPatient={onSelectPatient}
          searchTerm={searchTerm}
          onSearchChange={onSearchChange}
        />
      );
    case 2:
      return (
        <ClinicalInfoStep
          formData={formData}
          onChange={onFieldChange}
          nurses={nurses}
          nursesLoading={nursesLoading}
          selectedPatient={selectedPatient}
          isAutoGenerated={isAutoGenerated}
          nurseScopeNotice={nurseScopeNotice}
        />
      );
    case 3:
      return (
        <TasksEventsStep
          formData={formData}
          onChange={onFieldChange}
          isAutoGenerated={isAutoGenerated}
        />
      );
    case 4:
      return (
        <ReviewStep
          formData={formData}
          selectedPatient={selectedPatient}
          nurses={nurses}
        />
      );
    default:
      return null;
  }
}
