/* oxlint-disable react-doctor/rendering-hydration-mismatch-time -- This Vite SPA page uses useSyncExternalStore for a stable displayed date snapshot; there is no server-rendered clock to hydrate. */
import { useCallback, useEffect, useReducer, useSyncExternalStore } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import format from 'date-fns/format';

import { normalizeApiResults } from '@/lib/utils';
import {
  usePatientMonitoring,
  useCreateShiftHandoff,
  usePatientDetail,
  useNursingTasks,
  useNursingAlerts,
  useMedicationsDueNow
} from '@/features/nursing/hooks';
import { useWardStaff } from '@/features/wards/hooks/useWardQueries';
import { useStaff } from '@/features/staff/hooks';
import { isRustV2ApiMode } from '@/lib/api/v2/runtime';
import { useAuth } from '@/lib/auth';
import { getShiftTypeFromTime } from '@/config/shiftConfig';
import { generateAllHandoffSummaries } from './generateHandoffSummary';
import { getHandoffNurseOptions } from './handoffNurseOptions';

const subscribeToStableDateSnapshot = () => () => {};
const getServerDateLabel = () => '';
const getTodayDateLabel = () => format(new Date(), 'MMMM d, yyyy');

function createInitialHandoffFormData() {
  return {
    shift_type: getShiftTypeFromTime(),
    to_nurse: '',
    patient_condition: '',
    ongoing_issues: '',
    pending_tasks: '',
    medication_changes: '',
    key_events: '',
    care_plan_updates: '',
    family_updates: '',
  };
}

function createInitialHandoffState() {
  return {
    currentStep: 1,
    selectedPatient: null,
    searchTerm: '',
    isAutoGenerated: false,
    formData: createInitialHandoffFormData(),
  };
}

function shiftHandoffReducer(state, action) {
  switch (action.type) {
    case 'select-patient':
      return {
        ...state,
        selectedPatient: action.patient,
        currentStep: 2,
        isAutoGenerated: false,
      };
    case 'set-search':
      return {
        ...state,
        searchTerm: action.searchTerm,
      };
    case 'set-field':
      return {
        ...state,
        formData: {
          ...state.formData,
          [action.field]: action.value,
        },
      };
    case 'hydrate-summaries':
      return {
        ...state,
        isAutoGenerated: true,
        formData: {
          ...state.formData,
          patient_condition: state.formData.patient_condition || action.summaries.patient_condition,
          pending_tasks: state.formData.pending_tasks || action.summaries.pending_tasks,
          ongoing_issues: state.formData.ongoing_issues || action.summaries.ongoing_issues,
          medication_changes: state.formData.medication_changes || action.summaries.medication_changes,
        },
      };
    case 'go-to-step':
      return {
        ...state,
        currentStep: action.stepId,
      };
    case 'next-step':
      return {
        ...state,
        currentStep: Math.min(state.currentStep + 1, 4),
      };
    case 'previous-step':
      return {
        ...state,
        currentStep: Math.max(state.currentStep - 1, 1),
      };
    default:
      return state;
  }
}

function getPatientItems(items, patientId) {
  return Array.isArray(items)
    ? items.filter(item => item.patient === patientId || item.patient_id === patientId)
    : [];
}

export function useShiftHandoffPageController() {
  const navigate = useNavigate();
  const rustV2Mode = isRustV2ApiMode();
  const { user } = useAuth();
  const [state, dispatch] = useReducer(shiftHandoffReducer, undefined, createInitialHandoffState);
  const todayLabel = useSyncExternalStore(
    subscribeToStableDateSnapshot,
    getTodayDateLabel,
    getServerDateLabel
  );
  const {
    currentStep,
    selectedPatient,
    searchTerm,
    isAutoGenerated,
    formData,
  } = state;

  const { data: patientsData, isLoading: patientsLoading } = usePatientMonitoring(null, 1, 100);
  const wardId = selectedPatient?.ward_id;
  const { data: wardStaffData, isLoading: wardNursesLoading } = useWardStaff(wardId, 'nursing');
  const { data: staffData, isLoading: staffLoading } = useStaff(
    { page_size: 100, is_active: true },
    { enabled: rustV2Mode && !!selectedPatient }
  );

  const createMutation = useCreateShiftHandoff();
  const patientId = selectedPatient?.patient_id;
  const { data: patientDetail } = usePatientDetail(patientId);
  const { data: tasksData } = useNursingTasks(patientId ? { patient: patientId } : {});
  const { data: alertsData } = useNursingAlerts(patientId ? { patient: patientId } : {});
  const { data: medicationsDue } = useMedicationsDueNow();

  const patients = normalizeApiResults(patientsData);
  const { nurses, usesDirectoryFallback } = getHandoffNurseOptions({
    rustV2Mode,
    wardStaff: wardStaffData,
    staff: staffData,
    currentUser: user,
  });
  const nursesLoading = wardNursesLoading || (rustV2Mode && staffLoading);

  useEffect(() => {
    if (!selectedPatient || !patientDetail) {
      return;
    }

    const vitals = patientDetail?.latest_vitals || patientDetail?.vitals?.[0] || null;
    const summaries = generateAllHandoffSummaries({
      patient: selectedPatient,
      vitals,
      tasks: getPatientItems(tasksData, patientId),
      alerts: getPatientItems(alertsData, patientId),
      medicationsDue: getPatientItems(medicationsDue, patientId),
      medicationEvents: patientDetail?.medication_events || [],
    });

    dispatch({ type: 'hydrate-summaries', summaries });
  }, [selectedPatient, patientDetail, tasksData, alertsData, medicationsDue, patientId]);

  const handleSelectPatient = useCallback((patient) => {
    dispatch({ type: 'select-patient', patient });
  }, []);

  const handleFieldChange = useCallback((field, value) => {
    dispatch({ type: 'set-field', field, value });
  }, []);

  const handleSearchChange = useCallback((nextSearchTerm) => {
    dispatch({ type: 'set-search', searchTerm: nextSearchTerm });
  }, []);

  const isStepComplete = useCallback((stepId) => {
    switch (stepId) {
      case 1:
        return !!selectedPatient;
      case 2:
        return !!formData.patient_condition && !!formData.to_nurse;
      case 3:
        return !!formData.pending_tasks;
      case 4:
        return true;
      default:
        return false;
    }
  }, [selectedPatient, formData]);

  const goToStep = useCallback((stepId) => {
    dispatch({ type: 'go-to-step', stepId });
  }, []);

  const handleNext = useCallback(() => {
    if (currentStep === 1 && !selectedPatient) {
      toast.error('Please select a patient');
      return;
    }
    if (currentStep === 2 && !formData.patient_condition) {
      toast.error('Please enter the patient condition');
      return;
    }
    if (currentStep === 2 && !formData.to_nurse) {
      toast.error('Please select the receiving nurse');
      return;
    }
    if (currentStep === 3 && !formData.pending_tasks) {
      toast.error('Please enter pending tasks');
      return;
    }

    dispatch({ type: 'next-step' });
  }, [currentStep, selectedPatient, formData]);

  const handleBack = useCallback(() => {
    dispatch({ type: 'previous-step' });
  }, []);

  const handleCancel = useCallback(() => {
    navigate('/dashboards/nurse');
  }, [navigate]);

  const handleSubmit = useCallback(async () => {
    if (!selectedPatient) {
      toast.error('Please select a patient');
      return;
    }
    if (!formData.patient_condition) {
      toast.error('Please enter the patient condition');
      return;
    }
    if (!formData.to_nurse) {
      toast.error('Please select the receiving nurse');
      return;
    }

    try {
      await createMutation.mutateAsync({
        patient: selectedPatient.patient_id,
        ward_id: selectedPatient.ward_id,
        shift_date: format(new Date(), 'yyyy-MM-dd'),
        shift_type: formData.shift_type,
        to_nurse: formData.to_nurse,
        patient_condition: formData.patient_condition,
        ongoing_issues: formData.ongoing_issues || '',
        pending_tasks: formData.pending_tasks || '',
        medication_changes: formData.medication_changes || '',
        key_events: formData.key_events || '',
        care_plan_updates: formData.care_plan_updates || '',
        family_updates: formData.family_updates || '',
      });

      toast.success('Shift handoff completed successfully');
      navigate('/dashboards/nurse');
    } catch (error) {
      console.error('Error creating handoff:', error);
      toast.error('Failed to create shift handoff. Please try again.');
    }
  }, [createMutation, formData, navigate, selectedPatient]);

  return {
    todayLabel,
    currentStep,
    selectedPatient,
    searchTerm,
    isAutoGenerated,
    formData,
    patients,
    patientsLoading,
    nurses,
    nursesLoading,
    usesDirectoryFallback,
    isSubmitting: createMutation.isPending,
    handleSelectPatient,
    handleFieldChange,
    handleSearchChange,
    isStepComplete,
    goToStep,
    handleNext,
    handleBack,
    handleCancel,
    handleSubmit,
  };
}
