# Generated by Django 4.2.10 on 2025-11-01 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_patientprofile_users_patie_medical_73a802_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('consultation', 'Consultation'), ('ward_round', 'Ward Round'), ('admission', 'Admission'), ('discharge', 'Discharge'), ('emergency', 'Emergency Intake')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('encounter_id', models.CharField(blank=True, help_text='FHIR Encounter resource ID', max_length=255, null=True)),
                ('current_step', models.IntegerField(default=1)),
                ('total_steps', models.IntegerField(default=5)),
                ('steps_completed', models.JSONField(default=list)),
                ('context_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_autosave', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='users.patientprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_clinical',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workflow_type', models.CharField(choices=[('consultation', 'Consultation'), ('ward_round', 'Ward Round'), ('admission', 'Admission'), ('discharge', 'Discharge'), ('emergency', 'Emergency Intake')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('template_data', models.JSONField(default=dict)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_template',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(blank=True, help_text='FHIR Appointment resource ID', max_length=255, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('hpi', models.TextField(blank=True, verbose_name='History of Present Illness')),
                ('ros', models.TextField(blank=True, verbose_name='Review of Systems')),
                ('physical_exam', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('template_used', models.CharField(blank=True, max_length=255)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_data', to='workflows.clinicalworkflow')),
            ],
            options={
                'db_table': 'workflows_consultation',
            },
        ),
        migrations.AddIndex(
            model_name='clinicalworkflow',
            index=models.Index(fields=['user', 'status'], name='workflows_c_user_id_87fdee_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalworkflow',
            index=models.Index(fields=['patient', 'workflow_type'], name='workflows_c_patient_343519_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalworkflow',
            index=models.Index(fields=['created_at'], name='workflows_c_created_44f5bd_idx'),
        ),
    ]
