# Generated by Django 4.2.10 on 2025-11-24 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalworkflow',
            name='workflow_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('ward_round', 'Ward Round'), ('admission', 'Admission'), ('discharge', 'Discharge'), ('emergency', 'Emergency Intake'), ('clinical_note', 'Clinical Note')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='workflow_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('ward_round', 'Ward Round'), ('admission', 'Admission'), ('discharge', 'Discharge'), ('emergency', 'Emergency Intake'), ('clinical_note', 'Clinical Note')], max_length=50),
        ),
        migrations.CreateModel(
            name='ClinicalNoteWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('soap', 'SOAP Note'), ('procedure', 'Procedure Note'), ('phone', 'Phone Note')], default='progress', max_length=50)),
                ('chief_complaint', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('hpi', models.TextField(blank=True, verbose_name='History of Present Illness')),
                ('ros', models.TextField(blank=True, verbose_name='Review of Systems')),
                ('physical_exam', models.TextField(blank=True)),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('procedure_name', models.CharField(blank=True, max_length=255)),
                ('indication', models.TextField(blank=True)),
                ('consent', models.CharField(blank=True, max_length=100)),
                ('pre_assessment', models.TextField(blank=True)),
                ('anesthesia', models.CharField(blank=True, max_length=255)),
                ('technique', models.TextField(blank=True)),
                ('specimens', models.TextField(blank=True)),
                ('ebl', models.CharField(blank=True, max_length=100, verbose_name='Estimated Blood Loss')),
                ('complications', models.CharField(blank=True, max_length=100)),
                ('complication_details', models.TextField(blank=True)),
                ('patient_condition', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, max_length=100)),
                ('post_instructions', models.TextField(blank=True)),
                ('caller_name', models.CharField(blank=True, max_length=255)),
                ('caller_relationship', models.CharField(blank=True, max_length=100)),
                ('callback_number', models.CharField(blank=True, max_length=50)),
                ('reason_for_call', models.TextField(blank=True)),
                ('symptoms_discussed', models.TextField(blank=True)),
                ('advice_given', models.TextField(blank=True)),
                ('urgency', models.CharField(blank=True, max_length=50)),
                ('actions_taken', models.TextField(blank=True)),
                ('pending_actions', models.TextField(blank=True)),
                ('callback_needed', models.CharField(blank=True, max_length=50)),
                ('follow_up', models.TextField(blank=True)),
                ('patient_education', models.TextField(blank=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note_data', to='workflows.clinicalworkflow')),
            ],
            options={
                'db_table': 'workflows_clinical_note',
            },
        ),
    ]
