# Generated by Django 4.2.10 on 2025-11-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_add_clinical_note_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnoteworkflow',
            name='note_type',
            field=models.CharField(choices=[('general', 'General'), ('soap', 'SOAP Note'), ('progress', 'Progress Note'), ('procedure', 'Procedure Note'), ('admission', 'Admission Note'), ('discharge', 'Discharge Note'), ('nursing', 'Nursing Note'), ('consultation', 'Consultation Note'), ('custom', 'Custom Note'), ('phone', 'Phone Note')], default='progress', max_length=50),
        ),
    ]
