# Generated by Django 4.2.10 on 2025-11-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_update_clinical_note_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardRoundWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overnight_events', models.TextField(blank=True)),
                ('nursing_concerns', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('vitals_reviewed', models.BooleanField(default=False)),
                ('assessment', models.TextField(blank=True)),
                ('plan_notes', models.TextField(blank=True)),
                ('orders_placed', models.JSONField(blank=True, default=list)),
                ('progress_note', models.TextField(blank=True)),
                ('estimated_discharge', models.DateField(blank=True, null=True)),
                ('discharge_planning_needed', models.BooleanField(default=False)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ward_round_data', to='workflows.clinicalworkflow')),
            ],
            options={
                'db_table': 'workflows_ward_round',
            },
        ),
        migrations.CreateModel(
            name='DischargeWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_criteria_met', models.JSONField(blank=True, default=list)),
                ('discharge_disposition', models.CharField(blank=True, max_length=100)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('transportation', models.CharField(blank=True, max_length=100)),
                ('medications_reconciled', models.BooleanField(default=False)),
                ('discharge_prescriptions', models.JSONField(blank=True, default=list)),
                ('medication_changes', models.TextField(blank=True)),
                ('medication_education_completed', models.BooleanField(default=False)),
                ('activity_restrictions', models.TextField(blank=True)),
                ('diet_instructions', models.TextField(blank=True)),
                ('wound_care', models.TextField(blank=True)),
                ('warning_signs', models.TextField(blank=True)),
                ('follow_up_appointments', models.TextField(blank=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('patient_education_complete', models.BooleanField(default=False)),
                ('discharge_instructions_given', models.BooleanField(default=False)),
                ('prescriptions_sent', models.BooleanField(default=False)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_data', to='workflows.clinicalworkflow')),
            ],
            options={
                'db_table': 'workflows_discharge',
            },
        ),
        migrations.CreateModel(
            name='AdmissionWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_verified', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50)),
                ('ward_id', models.UUIDField(blank=True, null=True)),
                ('bed_id', models.UUIDField(blank=True, null=True)),
                ('admission_type', models.CharField(blank=True, max_length=50)),
                ('admission_source', models.CharField(blank=True, max_length=100)),
                ('admission_reason', models.TextField(blank=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('initial_diagnosis', models.TextField(blank=True)),
                ('relevant_history', models.TextField(blank=True)),
                ('diet', models.CharField(blank=True, max_length=100)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('vitals_frequency', models.CharField(blank=True, max_length=50)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('labs', models.JSONField(blank=True, default=list)),
                ('nursing_instructions', models.TextField(blank=True)),
                ('admission_note', models.TextField(blank=True)),
                ('expected_los', models.IntegerField(blank=True, null=True, verbose_name='Expected Length of Stay')),
                ('attending_physician', models.CharField(blank=True, max_length=255)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_data', to='workflows.clinicalworkflow')),
            ],
            options={
                'db_table': 'workflows_admission',
            },
        ),
    ]
