# Generated by Django 4.2.10 on 2025-11-26 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_add_referral_consultation_linkage'),
        ('workflows', '0004_wardroundworkflow_dischargeworkflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalworkflow',
            name='source_referral',
            field=models.ForeignKey(blank=True, help_text='Referral that initiated this consultation workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_workflows', to='referrals.referral'),
        ),
    ]
