# Generated by Django 4.2.10 on 2026-02-10 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0005_add_referral_consultation_linkage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingEventReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('event_name', models.CharField(db_index=True, max_length=120)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'workflows_onboarding_event_receipt',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingFlowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_key', models.CharField(db_index=True, max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('definition', models.JSONField(default=dict)),
                ('etag', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflows_onboarding_flow_definition',
                'ordering': ['flow_key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_key', models.CharField(db_index=True, max_length=120)),
                ('flow_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=20)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('completed_steps_mask', models.BigIntegerField(default=0)),
                ('skipped_steps_mask', models.BigIntegerField(default=0)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('step_runtime_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='workflows.onboardingflowdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_onboarding_progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='onboardingflowdefinition',
            index=models.Index(fields=['active', 'updated_at'], name='workflows_o_active_ee348d_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingflowdefinition',
            constraint=models.UniqueConstraint(fields=('flow_key', 'version'), name='uq_workflows_onboarding_flow_definition_key_version'),
        ),
        migrations.AddField(
            model_name='onboardingeventreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_event_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='onboardingprogress',
            index=models.Index(fields=['user', 'status', 'updated_at'], name='workflows_o_user_id_7b1a98_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingprogress',
            index=models.Index(fields=['user', 'flow_key'], name='workflows_o_user_id_aaf8e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'flow_key', 'flow_version'), name='uq_workflows_onboarding_progress_user_flow'),
        ),
        migrations.AddIndex(
            model_name='onboardingeventreceipt',
            index=models.Index(fields=['user', 'received_at'], name='workflows_o_user_id_1830e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingeventreceipt',
            constraint=models.UniqueConstraint(fields=('user', 'event_id'), name='uq_workflows_onboarding_event_receipt_user_event'),
        ),
    ]
