# Generated by Django 4.2.10 on 2026-02-10 22:36

import hashlib
import json

from django.db import migrations


def _compute_etag(payload):
    serialized = json.dumps(payload, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(serialized.encode('utf-8')).hexdigest()


def seed_onboarding_flow_definitions(apps, schema_editor):
    OnboardingFlowDefinition = apps.get_model('workflows', 'OnboardingFlowDefinition')

    flow_definitions = [
        {
            "flow_key": "doctor_core_v1",
            "version": 1,
            "active": True,
            "roles": ["doctor", "inpatient_doctor", "physician", "practitioner"],
            "definition": {
                "flow_key": "doctor_core_v1",
                "version": 1,
                "active": True,
                "roles": ["doctor", "inpatient_doctor", "physician", "practitioner"],
                "start": {
                    "mode": "manual_or_first_login",
                    "start_route": "/dashboards/inpatient",
                },
                "steps": [
                    {
                        "id": "core_01_start",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "onboarding.flow_started",
                            "where": {"flow_key": "doctor_core_v1"},
                        },
                    },
                    {
                        "id": "core_02_open_registry",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "nav.route_viewed",
                            "where_any": [
                                {"route": "/patients"},
                                {"route": "/patients/my-patients"},
                            ],
                        },
                    },
                    {
                        "id": "core_03_open_patient_chart",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "patients.chart_opened",
                            "where": {"success": True},
                        },
                    },
                    {
                        "id": "core_04_timeline_filters",
                        "required": True,
                        "complete_when": {
                            "type": "sequence",
                            "events": [
                                {
                                    "name": "chronicle.filter_changed",
                                    "where": {"filter": "progress_note"},
                                    "capture": {"patient_id": "patient_id"},
                                },
                                {
                                    "name": "chronicle.filter_changed",
                                    "where": {
                                        "filter": "all",
                                        "patient_id": "$state.patient_id",
                                    },
                                },
                            ],
                        },
                    },
                    {
                        "id": "core_05_create_note",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "chronicle.note_created",
                            "where": {"success": True},
                        },
                    },
                    {
                        "id": "core_06_place_order",
                        "required": True,
                        "complete_when": {
                            "type": "any_of",
                            "conditions": [
                                {
                                    "type": "event",
                                    "name": "chronicle.prescription_created",
                                    "where": {"success": True},
                                },
                                {
                                    "type": "event",
                                    "name": "labs.order_created",
                                    "where": {"success": True},
                                },
                            ],
                        },
                    },
                ],
            },
        },
        {
            "flow_key": "doctor_templates_v1",
            "version": 1,
            "active": True,
            "roles": ["doctor", "inpatient_doctor", "physician", "practitioner"],
            "definition": {
                "flow_key": "doctor_templates_v1",
                "version": 1,
                "active": True,
                "roles": ["doctor", "inpatient_doctor", "physician", "practitioner"],
                "start": {
                    "mode": "manual_or_after",
                    "after_flow": "doctor_core_v1",
                },
                "steps": [
                    {
                        "id": "tpl_01_open_note_templates",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "nav.route_viewed",
                            "where": {"route": "/clinical-notes/templates"},
                        },
                    },
                    {
                        "id": "tpl_02_create_note_template",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "templates.note.created",
                            "where": {"success": True, "section_count_gte": 3},
                            "capture": {"note_template_id": "template_id"},
                        },
                    },
                    {
                        "id": "tpl_03_use_note_template",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "chronicle.note_created",
                            "where": {
                                "success": True,
                                "template_id": "$state.note_template_id",
                            },
                        },
                    },
                    {
                        "id": "tpl_04_open_chart_templates",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "nav.route_viewed",
                            "where": {"route": "/charts/templates"},
                        },
                    },
                    {
                        "id": "tpl_05_create_chart_template",
                        "required": True,
                        "complete_when": {
                            "type": "event",
                            "name": "templates.chart.created",
                            "where": {"success": True},
                            "capture": {"chart_template_id": "template_id"},
                        },
                    },
                    {
                        "id": "tpl_06_use_chart_template",
                        "required": True,
                        "complete_when": {
                            "type": "sequence",
                            "events": [
                                {
                                    "name": "charts.assignment.created",
                                    "where": {
                                        "success": True,
                                        "template_id": "$state.chart_template_id",
                                    },
                                    "capture": {"assignment_id": "assignment_id"},
                                },
                                {
                                    "name": "charts.entry.created",
                                    "where": {
                                        "success": True,
                                        "assignment_id": "$state.assignment_id",
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
    ]

    for flow in flow_definitions:
        payload = {
            "flow_key": flow["flow_key"],
            "version": flow["version"],
            "active": flow["active"],
            "roles": flow["roles"],
            "definition": flow["definition"],
        }
        OnboardingFlowDefinition.objects.update_or_create(
            flow_key=flow["flow_key"],
            version=flow["version"],
            defaults={
                "active": flow["active"],
                "roles": flow["roles"],
                "definition": flow["definition"],
                "etag": _compute_etag(payload),
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_onboardingeventreceipt_onboardingflowdefinition_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_onboarding_flow_definitions, noop_reverse),
    ]
