# Generated by Django 4.2.10 on 2026-02-12 10:22

import hashlib
import json

from django.db import migrations
from django.utils import timezone


STEP_UI_DEFAULTS = {
    "core_01_start": {
        "target": '[data-onboarding="nav-dashboard"]',
        "placement": "right",
        "title": "Open Inpatient Dashboard",
        "body": "Click here to begin the onboarding flow.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "core_02_open_registry": {
        "target": '[data-onboarding="nav-patients"]',
        "placement": "right",
        "title": "Open Patient Registry",
        "body": "Click Patient Registry in the sidebar.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "core_03_open_patient_chart": {
        "target": '[data-onboarding="patient-list-row"]',
        "placement": "left",
        "title": "Open A Patient Chart",
        "body": "Click a patient row to open their chronicle.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "core_04_timeline_filters": {
        "target": '[data-onboarding="chronicle-filter-group"]',
        "placement": "bottom",
        "title": "Use Chronicle Filters",
        "body": "Use Notes, then switch back to All to complete this step.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "core_05_create_note": {
        "target": '[data-onboarding="chronicle-add-note"]',
        "placement": "bottom",
        "title": "Create A Note",
        "body": "Click Add Note to create a clinical note.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "core_06_place_order": {
        "target": '[data-onboarding="chronicle-prescribe"]',
        "placement": "bottom",
        "title": "Place An Order",
        "body": "Click Prescribe (or use More for lab orders).",
        "arrow": True,
        "scroll_into_view": True,
    },
    "tpl_01_open_note_templates": {
        "target": '[data-onboarding="nav-clinical-content-toggle"]',
        "placement": "right",
        "title": "Open Clinical Content",
        "body": "Use this menu to access note and chart templates.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "tpl_02_create_note_template": {
        "target": '[data-onboarding="note-template-create"]',
        "placement": "left",
        "title": "Create Note Template",
        "body": "Click Create Template, then build one with 3+ sections.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "tpl_03_use_note_template": {
        "target": '[data-onboarding="chronicle-add-note"]',
        "placement": "bottom",
        "title": "Use The Template",
        "body": "Open Add Note and create a note with your new template.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "tpl_04_open_chart_templates": {
        "target": '[data-onboarding="nav-clinical-content-toggle"]',
        "placement": "right",
        "title": "Open Clinical Content",
        "body": "Open Clinical Content to access chart templates.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "tpl_05_create_chart_template": {
        "target": '[data-onboarding="chart-template-create"]',
        "placement": "left",
        "title": "Create Chart Template",
        "body": "Click New Template to create a chart template.",
        "arrow": True,
        "scroll_into_view": True,
    },
    "tpl_06_use_chart_template": {
        "target": '[data-onboarding="chronicle-more-actions"]',
        "placement": "bottom",
        "title": "Assign Then Record",
        "body": "Use More actions to assign a chart, then record a chart entry.",
        "arrow": True,
        "scroll_into_view": True,
    },
}

FLOW_KEYS = ("doctor_core_v1", "doctor_templates_v1")


def _compute_etag(payload):
    serialized = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def add_step_ui_metadata(apps, schema_editor):
    OnboardingFlowDefinition = apps.get_model("workflows", "OnboardingFlowDefinition")

    for flow in OnboardingFlowDefinition.objects.filter(flow_key__in=FLOW_KEYS).iterator():
        definition = flow.definition if isinstance(flow.definition, dict) else {}
        steps = definition.get("steps")
        if not isinstance(steps, list):
            continue

        changed = False
        updated_steps = []
        for step in steps:
            if not isinstance(step, dict):
                updated_steps.append(step)
                continue

            ui_defaults = STEP_UI_DEFAULTS.get(step.get("id"))
            if not ui_defaults:
                updated_steps.append(step)
                continue

            existing_ui = step.get("ui") if isinstance(step.get("ui"), dict) else {}
            merged_ui = {**ui_defaults, **existing_ui}
            if existing_ui == merged_ui and isinstance(step.get("ui"), dict):
                updated_steps.append(step)
                continue

            updated_step = dict(step)
            updated_step["ui"] = merged_ui
            updated_steps.append(updated_step)
            changed = True

        if not changed:
            continue

        updated_definition = dict(definition)
        updated_definition["steps"] = updated_steps
        payload = {
            "flow_key": flow.flow_key,
            "version": flow.version,
            "active": flow.active,
            "roles": flow.roles,
            "definition": updated_definition,
        }
        OnboardingFlowDefinition.objects.filter(pk=flow.pk).update(
            definition=updated_definition,
            etag=_compute_etag(payload),
            updated_at=timezone.now(),
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0007_seed_onboarding_flow_definitions"),
    ]

    operations = [
        migrations.RunPython(add_step_ui_metadata, noop_reverse),
    ]
