# Generated by Django 4.2.29 on 2026-03-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_add_onboarding_step_ui_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalworkflow',
            name='workflow_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('ward_round', 'Ward Round'), ('discharge', 'Discharge'), ('emergency', 'Emergency Intake'), ('clinical_note', 'Clinical Note')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='workflow_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('ward_round', 'Ward Round'), ('discharge', 'Discharge'), ('emergency', 'Emergency Intake'), ('clinical_note', 'Clinical Note')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AdmissionWorkflow',
        ),
    ]
