FEATURE_CHRONICLE_COPILOT = 'chronicle_copilot'
FEATURE_NOTE_DRAFT = 'note_draft'
FEATURE_NOTE_LINT = 'note_lint'
FEATURE_LAB_INTERPRETATION = 'lab_interpretation'
FEATURE_OMNI_NL = 'omni_nl'
FEATURE_SCRIBE = 'scribe'
FEATURE_GENERIC = 'generic'

FEATURE_CHOICES = [
    (FEATURE_CHRONICLE_COPILOT, 'Chronicle Copilot'),
    (FEATURE_NOTE_DRAFT, 'Note Draft'),
    (FEATURE_NOTE_LINT, 'Note Lint'),
    (FEATURE_LAB_INTERPRETATION, 'Lab Interpretation'),
    (FEATURE_OMNI_NL, 'Omni NL'),
    (FEATURE_SCRIBE, 'Ambient Scribe'),
    (FEATURE_GENERIC, 'Generic AI'),
]

FEATURE_ACCESS_SCOPE = {
    FEATURE_CHRONICLE_COPILOT: 'clinical',
    FEATURE_NOTE_DRAFT: 'clinical',
    FEATURE_NOTE_LINT: 'clinical',
    FEATURE_LAB_INTERPRETATION: 'lab',
    FEATURE_OMNI_NL: None,
    FEATURE_SCRIBE: 'clinical',
    FEATURE_GENERIC: None,
}

FEATURE_REQUIRES_PATIENT = {
    FEATURE_CHRONICLE_COPILOT,
    FEATURE_NOTE_DRAFT,
    FEATURE_NOTE_LINT,
    FEATURE_LAB_INTERPRETATION,
    FEATURE_SCRIBE,
}

FEATURE_FLAG_SETTING_BY_FEATURE = {
    FEATURE_CHRONICLE_COPILOT: 'AI_CHRONICLE_COPILOT_ENABLED',
    FEATURE_NOTE_DRAFT: 'AI_NOTE_DRAFT_ENABLED',
    FEATURE_NOTE_LINT: 'AI_NOTE_LINT_ENABLED',
    FEATURE_LAB_INTERPRETATION: 'AI_LAB_INTERPRET_ENABLED',
    FEATURE_OMNI_NL: 'AI_OMNI_NL_ENABLED',
    FEATURE_SCRIBE: 'AI_AMBIENT_SCRIBE_ENABLED',
    FEATURE_GENERIC: 'AI_ENABLED',
}

MODEL_ROLE_REASONER_LARGE = 'reasoner_large'
MODEL_ROLE_WRITER_MEDIUM = 'writer_medium'
MODEL_ROLE_VALIDATOR_SMALL = 'validator_small'
MODEL_ROLE_INTENT_SMALL = 'intent_small'
MODEL_ROLE_EMBEDDING_MODEL = 'embedding_model'
MODEL_ROLE_RERANKER_MODEL = 'reranker_model'
MODEL_ROLE_ASR_MEDICAL = 'asr_medical'
MODEL_ROLE_DIARIZER = 'diarizer'

MODEL_ROLE_CHOICES = [
    MODEL_ROLE_REASONER_LARGE,
    MODEL_ROLE_WRITER_MEDIUM,
    MODEL_ROLE_VALIDATOR_SMALL,
    MODEL_ROLE_INTENT_SMALL,
    MODEL_ROLE_EMBEDDING_MODEL,
    MODEL_ROLE_RERANKER_MODEL,
    MODEL_ROLE_ASR_MEDICAL,
    MODEL_ROLE_DIARIZER,
]

FEATURE_PRIMARY_MODEL_ROLE = {
    FEATURE_CHRONICLE_COPILOT: MODEL_ROLE_REASONER_LARGE,
    FEATURE_NOTE_DRAFT: MODEL_ROLE_WRITER_MEDIUM,
    FEATURE_NOTE_LINT: MODEL_ROLE_VALIDATOR_SMALL,
    FEATURE_LAB_INTERPRETATION: MODEL_ROLE_WRITER_MEDIUM,
    FEATURE_OMNI_NL: MODEL_ROLE_INTENT_SMALL,
    FEATURE_SCRIBE: MODEL_ROLE_ASR_MEDICAL,
    FEATURE_GENERIC: MODEL_ROLE_WRITER_MEDIUM,
}

FEATURE_SECONDARY_MODEL_ROLES = {
    FEATURE_CHRONICLE_COPILOT: [MODEL_ROLE_EMBEDDING_MODEL, MODEL_ROLE_RERANKER_MODEL, MODEL_ROLE_VALIDATOR_SMALL],
    FEATURE_NOTE_DRAFT: [MODEL_ROLE_EMBEDDING_MODEL, MODEL_ROLE_RERANKER_MODEL],
    FEATURE_NOTE_LINT: [MODEL_ROLE_WRITER_MEDIUM],
    FEATURE_LAB_INTERPRETATION: [MODEL_ROLE_VALIDATOR_SMALL, MODEL_ROLE_EMBEDDING_MODEL],
    FEATURE_OMNI_NL: [MODEL_ROLE_VALIDATOR_SMALL],
    FEATURE_SCRIBE: [MODEL_ROLE_DIARIZER, MODEL_ROLE_WRITER_MEDIUM, MODEL_ROLE_VALIDATOR_SMALL],
    FEATURE_GENERIC: [MODEL_ROLE_VALIDATOR_SMALL],
}

SENSITIVE_OMNI_ACTION_PREFIXES = {
    'write',
    'update',
    'delete',
    'sign',
    'order',
    'medication',
    'break_glass',
    'phi_export',
    'share',
    'print',
    'billing_submit',
    'admin_change',
    'role_change',
}
