from datetime import timedelta

from celery import shared_task
from django.conf import settings
from django.utils import timezone

from apps.ai.models import AIArtifact, AIMessage, AISession
from apps.ai.services.policy import build_response_envelope


@shared_task(
    bind=True,
    autoretry_for=(Exception,),
    retry_backoff=True,
    retry_jitter=True,
    retry_kwargs={'max_retries': 3},
    queue='ai_realtime',
    name='apps.ai.tasks.realtime_generate_placeholder_artifact',
)
def realtime_generate_placeholder_artifact(self, session_id: str, artifact_type: str = AIArtifact.TYPE_SUMMARY):
    session = AISession.objects.filter(id=session_id).first()
    if not session:
        return {'status': 'missing_session', 'session_id': session_id}

    envelope = build_response_envelope(
        feature=session.feature,
        confidence=0.0,
        result={'status': 'queued', 'message': 'Placeholder artifact generated by realtime task.'},
        citations=[],
        requires_human_review=True,
    )

    artifact = AIArtifact.objects.create(
        session=session,
        artifact_type=artifact_type,
        payload_json=envelope,
        confidence_score='0',
        requires_human_review=True,
        schema_version=envelope['schema_version'],
    )

    session.status = AISession.STATUS_COMPLETED
    session.ended_at = timezone.now()
    session.save(update_fields=['status', 'ended_at', 'updated_at'])

    return {'status': 'ok', 'session_id': str(session.id), 'artifact_id': str(artifact.id)}


@shared_task(
    bind=True,
    autoretry_for=(Exception,),
    retry_backoff=True,
    retry_jitter=True,
    retry_kwargs={'max_retries': 3},
    queue='ai_batch',
    name='apps.ai.tasks.batch_mark_stale_sessions_failed',
)
def batch_mark_stale_sessions_failed(self):
    timeout_ms = int(getattr(settings, 'AI_REQUEST_TIMEOUT_MS', 8000))
    stale_seconds = max(60, int(timeout_ms / 1000) * 10)
    stale_before = timezone.now() - timedelta(seconds=stale_seconds)

    updated = AISession.objects.filter(
        status__in=[AISession.STATUS_QUEUED, AISession.STATUS_RUNNING],
        started_at__lt=stale_before,
    ).update(
        status=AISession.STATUS_FAILED,
        ended_at=timezone.now(),
        updated_at=timezone.now(),
    )

    return {
        'status': 'ok',
        'stale_before': stale_before.isoformat(),
        'updated_sessions': int(updated),
    }


@shared_task(
    bind=True,
    autoretry_for=(Exception,),
    retry_backoff=True,
    retry_jitter=True,
    retry_kwargs={'max_retries': 2},
    queue='ai_maintenance',
    name='apps.ai.tasks.maintenance_redact_expired_encrypted_messages',
)
def maintenance_redact_expired_encrypted_messages(self):
    retention_days = int(getattr(settings, 'AI_TRANSCRIPT_RETENTION_DAYS', 30))
    cutoff = timezone.now() - timedelta(days=max(retention_days, 1))

    updated_count = AIMessage.objects.filter(created_at__lt=cutoff).exclude(content_encrypted='').update(content_encrypted='')
    return {
        'status': 'ok',
        'retention_days': retention_days,
        'cutoff': cutoff.isoformat(),
        'updated_messages': int(updated_count),
    }
