# Generated by Django 4.2.10 on 2025-11-26 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_notes', '0006_add_template_visibility_and_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_passwordresettoken'),
        ('wards', '0005_add_local_encounter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(help_text="Human-readable allergen name (e.g., 'Penicillin', 'Peanuts')", max_length=255)),
                ('allergen_code', models.CharField(blank=True, help_text='Standard code (RxCUI, SNOMED CT, etc.)', max_length=50, null=True)),
                ('allergen_code_system', models.CharField(blank=True, help_text="Code system (e.g., 'RxNorm', 'SNOMED')", max_length=50, null=True)),
                ('allergy_type', models.CharField(choices=[('drug', 'Drug'), ('food', 'Food'), ('environmental', 'Environmental'), ('other', 'Other')], default='drug', max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-Threatening')], default='moderate', help_text='Severity of allergic reaction', max_length=20)),
                ('reaction', models.TextField(blank=True, help_text="Description of allergic reaction (e.g., 'Rash', 'Anaphylaxis')")),
                ('onset_date', models.DateField(blank=True, help_text='Date allergy was first observed', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this allergy is currently active')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('fhir_id', models.CharField(blank=True, help_text='FHIR AllergyIntolerance resource ID', max_length=100, null=True, unique=True)),
                ('fhir_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allergies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_allergies', to='users.patientprofile')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Practitioner who verified this allergy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_allergies', to='users.practitionerprofile')),
            ],
            options={
                'verbose_name': 'Patient Allergy',
                'verbose_name_plural': 'Patient Allergies',
                'ordering': ['-severity', 'allergen_name'],
            },
        ),
        migrations.CreateModel(
            name='DrugSafetyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('drug_interaction', 'Drug-Drug Interaction'), ('allergy', 'Allergy Alert'), ('contraindication', 'Contraindication'), ('duplicate_therapy', 'Duplicate Therapy')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical (Hard Stop)'), ('high', 'High (Warning)'), ('moderate', 'Moderate (Caution)'), ('low', 'Low (Informational)')], help_text='Critical = hard stop, High = warning, Moderate/Low = informational', max_length=20)),
                ('title', models.CharField(help_text="Brief alert title (e.g., 'Severe Drug Interaction')", max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the safety concern')),
                ('triggering_medication', models.CharField(help_text='The medication being prescribed that triggered the alert', max_length=255)),
                ('conflicting_medication', models.CharField(blank=True, help_text='Existing medication or allergen causing the conflict', max_length=255)),
                ('is_overridden', models.BooleanField(default=False, help_text='Whether provider overrode this alert')),
                ('override_reason', models.TextField(blank=True, help_text='Required reason for overriding critical/high alerts')),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_safety_alerts', to='encounters.Encounter')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_alerts', to='users.practitionerprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_safety_alerts', to='users.patientprofile')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_alerts', to='clinical_notes.prescription')),
            ],
            options={
                'verbose_name': 'Drug Safety Alert',
                'verbose_name_plural': 'Drug Safety Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugInteractionCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug1_rxcui', models.CharField(help_text='RxCUI code for first drug', max_length=20)),
                ('drug2_rxcui', models.CharField(help_text='RxCUI code for second drug', max_length=20)),
                ('severity', models.CharField(help_text='Interaction severity from API', max_length=20)),
                ('description', models.TextField(help_text='Description of the interaction')),
                ('source', models.CharField(help_text="API source (e.g., 'RxNorm', 'OpenFDA')", max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Cache expiration time')),
            ],
            options={
                'verbose_name': 'Drug Interaction Cache',
                'verbose_name_plural': 'Drug Interaction Cache',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['drug1_rxcui', 'drug2_rxcui'], name='drug_safety_drug1_r_a2af8c_idx'), models.Index(fields=['expires_at'], name='drug_safety_expires_6f2ff7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='druginteractioncache',
            constraint=models.UniqueConstraint(fields=('drug1_rxcui', 'drug2_rxcui'), name='unique_drug_pair'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['patient', 'is_active'], name='drug_safety_patient_1ccbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['allergen_code'], name='drug_safety_allerge_7a4f83_idx'),
        ),
        migrations.AddIndex(
            model_name='drugsafetyalert',
            index=models.Index(fields=['patient', 'created_at'], name='drug_safety_patient_e3288b_idx'),
        ),
        migrations.AddIndex(
            model_name='drugsafetyalert',
            index=models.Index(fields=['prescription'], name='drug_safety_prescri_61c0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='drugsafetyalert',
            index=models.Index(fields=['severity', 'is_overridden'], name='drug_safety_severit_7c956c_idx'),
        ),
    ]
