# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_allergy_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    PatientAllergy = apps.get_model('drug_safety', 'PatientAllergy')

    fallback = _get_fallback_facility(Facility)

    allergies = list(
        PatientAllergy.objects.filter(facility__isnull=True)
        .select_related('patient__facility')
    )

    for allergy in allergies:
        facility = None
        if allergy.patient_id and getattr(allergy.patient, 'facility_id', None):
            facility = allergy.patient.facility
        if not facility and fallback:
            facility = fallback
        if facility:
            allergy.facility_id = facility.id

    if allergies:
        PatientAllergy.objects.bulk_update(allergies, ['facility'])

    if PatientAllergy.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "PatientAllergy facility backfill incomplete. "
            "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('drug_safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientallergy',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='patient_allergies',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_allergy_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patientallergy',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='patient_allergies',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['facility', 'is_active'], name='drug_safety_allergy_facility_idx'),
        ),
    ]
