# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('drug_safety', '0002_facility_scoping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientallergy',
            new_name='drug_safety_facilit_557e54_idx',
            old_name='drug_safety_allergy_facility_idx',
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this allergy record', on_delete=django.db.models.deletion.PROTECT, related_name='patient_allergies', to='core.facility'),
        ),
    ]
