web: python manage.py collectstatic --noinput && python manage.py migrate && python manage.py ensure_admin && gunicorn hms_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --access-logfile -
worker: celery -A hms_backend worker --loglevel=info
beat: celery -A hms_backend beat --loglevel=info