# Generated by Django 4.2.10 on 2026-01-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_lab_placeholder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inboxitem',
            new_name='notificatio_recipie_3fabee_idx',
            old_name='notificat_recipient_2b0d44_idx',
        ),
        migrations.RenameIndex(
            model_name='inboxitem',
            new_name='notificatio_recipie_4fca3e_idx',
            old_name='notificat_recipient_8a5250_idx',
        ),
        migrations.RenameIndex(
            model_name='inboxitem',
            new_name='notificatio_facilit_0d86a3_idx',
            old_name='notificat_facility_eb3582_idx',
        ),
        migrations.RenameIndex(
            model_name='inboxitem',
            new_name='notificatio_patient_a80d3e_idx',
            old_name='notificat_patient_24e8d7_idx',
        ),
        migrations.RenameIndex(
            model_name='inboxitem',
            new_name='notificatio_source__9ee270_idx',
            old_name='notificat_source_t_d8f778_idx',
        ),
    ]
