# Generated by Django 4.2.29 on 2026-03-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notificat_recipient_2b0d44_idx_notificatio_recipie_3fabee_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='source_type',
            field=models.CharField(choices=[('referral', 'Referral'), ('nursing_alert', 'Nursing Alert'), ('nursing_task', 'Nursing Task'), ('drug_safety', 'Drug Safety'), ('lab_result', 'Lab Result'), ('discharge', 'Discharge')], max_length=30),
        ),
    ]
