# Generated by Django 4.2.29 on 2026-03-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_inboxitem_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='source_type',
            field=models.CharField(choices=[('referral', 'Referral'), ('admission', 'Admission'), ('nursing_alert', 'Nursing Alert'), ('nursing_task', 'Nursing Task'), ('drug_safety', 'Drug Safety'), ('lab_result', 'Lab Result'), ('discharge', 'Discharge')], max_length=30),
        ),
    ]
