# Generated by Django 4.2.10 on 2025-04-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_schedule_templates'),
        ('appointments', '0003_recurringschedule'),
    ]

    operations = [
    ]
