# Generated by Django 4.2.10 on 2025-11-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_merge_20250420_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='breaks',
            field=models.JSONField(blank=True, default=list, help_text="List of break times, e.g. [{'start': '12:00', 'end': '13:00'}]"),
        ),
    ]
