# Generated by Django 4.2.10 on 2025-11-24 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_user_gender'),
        ('appointments', '0005_recurringschedule_breaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date to block')),
                ('start_time', models.TimeField(help_text='Start time of blocked period')),
                ('end_time', models.TimeField(help_text='End time of blocked period')),
                ('reason', models.CharField(help_text="Reason for blocking (e.g., 'Vacation', 'Emergency', 'Training')", max_length=200)),
                ('is_all_day', models.BooleanField(default=False, help_text='Block the entire day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blocked Time',
                'verbose_name_plural': 'Blocked Times',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['practitioner', 'is_active', 'active_from'], name='appointment_practit_a0f989_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['days_of_week'], name='appointment_days_of_8823ac_idx'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocked_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='users.practitionerprofile'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_blocked_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blockedtime',
            index=models.Index(fields=['practitioner', 'date'], name='appointment_practit_c126b7_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedtime',
            index=models.Index(fields=['date'], name='appointment_date_075ca8_idx'),
        ),
    ]
