# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_schedule_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    RecurringSchedule = apps.get_model('appointments', 'RecurringSchedule')
    BlockedTime = apps.get_model('appointments', 'BlockedTime')

    fallback = _get_fallback_facility(Facility)

    schedules = list(
        RecurringSchedule.objects.filter(facility__isnull=True).select_related(
            'practitioner__staff__primary_facility'
        )
    )
    for schedule in schedules:
        facility = None
        staff = getattr(schedule.practitioner, 'staff', None)
        if staff and getattr(staff, 'primary_facility_id', None):
            facility = staff.primary_facility
        if not facility and fallback:
            facility = fallback
        if facility:
            schedule.facility_id = facility.id
    if schedules:
        RecurringSchedule.objects.bulk_update(schedules, ['facility'])

    blocked_times = list(
        BlockedTime.objects.filter(facility__isnull=True).select_related(
            'practitioner__staff__primary_facility'
        )
    )
    for blocked in blocked_times:
        facility = None
        staff = getattr(blocked.practitioner, 'staff', None)
        if staff and getattr(staff, 'primary_facility_id', None):
            facility = staff.primary_facility
        if not facility and fallback:
            facility = fallback
        if facility:
            blocked.facility_id = facility.id
    if blocked_times:
        BlockedTime.objects.bulk_update(blocked_times, ['facility'])

    if RecurringSchedule.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "RecurringSchedule facility backfill incomplete. "
            "Assign practitioner primary_facility or set DEFAULT_FACILITY_CODE."
        )
    if BlockedTime.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "BlockedTime facility backfill incomplete. "
            "Assign practitioner primary_facility or set DEFAULT_FACILITY_CODE."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('appointments', '0006_add_blocked_time_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recurring_schedules',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='blocked_times',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_schedule_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recurringschedule',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recurring_schedules',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='blocked_times',
                to='core.facility',
            ),
        ),
    ]
