# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('appointments', '0007_facility_scoping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedtime',
            name='facility',
            field=models.ForeignKey(help_text='Facility where this blocked time applies', on_delete=django.db.models.deletion.PROTECT, related_name='blocked_times', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='facility',
            field=models.ForeignKey(help_text='Facility where this schedule applies', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='core.facility'),
        ),
        migrations.AddIndex(
            model_name='blockedtime',
            index=models.Index(fields=['facility', 'date'], name='appointment_facilit_5d1afe_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['facility', 'is_active'], name='appointment_facilit_c25e89_idx'),
        ),
    ]
