# Generated by Django 4.2.10 on 2026-01-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_clinic_clinic_unique_clinic_code_per_facility'),
        ('appointments', '0010_appointment_clinic_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='organization.clinic'),
        ),
    ]
