# Generated by Django 4.2.10 on 2026-01-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_alter_clinicalunit_unit_category'),
        ('appointments', '0011_alter_appointment_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='migrated_at',
            field=models.DateTimeField(blank=True, help_text='When this schedule was migrated to roster-based availability', null=True),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='migrated_to_roster',
            field=models.BooleanField(default=False, help_text='Whether this schedule has been migrated to roster-based availability'),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='roster_duty_type',
            field=models.ForeignKey(blank=True, help_text='The duty type this schedule was migrated to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_schedules', to='organization.departmentdutytype'),
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['migrated_to_roster'], name='appointment_migrate_5dfd2b_idx'),
        ),
    ]
