# Generated by Django 4.2.10 on 2026-02-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_add_duty_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assignment_source',
            field=models.CharField(blank=True, choices=[('booking', 'Booking'), ('preassignment', 'Preassignment'), ('check_in', 'Check-In'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assignment_status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('preassigned', 'Preassigned'), ('assigned', 'Assigned')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
