# Generated by Django 4.2.10 on 2026-02-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointment_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='template_key',
            field=models.UUIDField(blank=True, db_index=True, help_text='Shared template key when this schedule was cloned to multiple practitioners', null=True),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='template_name',
            field=models.CharField(blank=True, help_text='Optional display name for the shared recurring schedule template', max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['facility', 'template_key'], name='appointment_facilit_a9cd5e_idx'),
        ),
    ]
