# Generated by Django 4.2.29 on 2026-05-01 14:50

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feature_entitlement_override'),
        ('appointments', '0014_recurringschedule_template_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSearchIndex',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_projection', serialize=False, to='appointments.appointment')),
                ('search_document', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_search_indexes', to='core.facility')),
            ],
            options={
                'indexes': [models.Index(fields=['facility', 'status'], name='appt_search_idx_fac_status_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='appt_search_idx_doc_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
