# Generated by Django 4.2.10 on 2026-01-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recordexportjob',
            new_name='interop_rec_patient_977f66_idx',
            old_name='interop_rec_patient_0f4d36_idx',
        ),
        migrations.RenameIndex(
            model_name='recordexportjob',
            new_name='interop_rec_target__7e2eb5_idx',
            old_name='interop_rec_target__8b0a78_idx',
        ),
        migrations.RenameIndex(
            model_name='recordexportjob',
            new_name='interop_rec_expires_40b832_idx',
            old_name='interop_rec_expires_e52c14_idx',
        ),
    ]
