# Generated by Django 4.2.10 on 2025-04-16 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerFHIRMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fhir_practitioner_id', models.CharField(max_length=100, unique=True)),
                ('fhir_resource_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practitioner_mappings', to=settings.AUTH_USER_MODEL)),
                ('practitioner_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_mapping', to='users.practitionerprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_practitioner_mappings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
