# Generated by Django 4.2.10 on 2025-10-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_practitionerfhirmapping'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['medical_record_number'], name='users_patie_medical_73a802_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['nhis_id'], name='users_patie_nhis_id_9d978d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['fhir_patient_id'], name='users_patie_fhir_pa_1e1282_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['created_at'], name='users_patie_created_444a1f_idx'),
        ),
    ]
