# Generated by Django 4.2.10 on 2025-12-01 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPatientList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_pinned', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_user_lists', to='users.patientprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Patient List',
                'verbose_name_plural': 'User Patient Lists',
                'ordering': ['-is_pinned', '-added_at'],
                'indexes': [models.Index(fields=['user', '-added_at'], name='users_userp_user_id_599a76_idx'), models.Index(fields=['user', '-is_pinned', '-added_at'], name='users_userp_user_id_e10b8a_idx')],
                'unique_together': {('user', 'patient')},
            },
        ),
    ]
