# Generated by Django 4.2.10 on 2025-12-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_first_name_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_last_name_gin_idx',
        ),
    ]
