# Generated by Django 4.2.10 on 2025-12-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_multi_facility_foundation'),
        ('users', '0008_remove_user_user_first_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='primary_facility',
            field=models.ForeignKey(blank=True, help_text='Primary facility where this staff member works', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.facility'),
        ),
    ]
