# Generated by Codex on 2025-01-01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0009_multi_facility_foundation'),
        ('core', '0006_enable_pg_trgm'),
    ]

    operations = [
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "users_user_first_name_trgm_idx "
                "ON users_user USING gin (first_name gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS users_user_first_name_trgm_idx;"
            ),
        ),
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "users_user_last_name_trgm_idx "
                "ON users_user USING gin (last_name gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS users_user_last_name_trgm_idx;"
            ),
        ),
    ]
