# Generated by Django 4.2.10 on 2026-01-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_mfa_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mfasession',
            new_name='users_mfase_token_h_7521eb_idx',
            old_name='users_mfasess_token_h_6202b6_idx',
        ),
        migrations.RenameIndex(
            model_name='mfasession',
            new_name='users_mfase_user_id_795be6_idx',
            old_name='users_mfasess_user_id_0b2b2b_idx',
        ),
        migrations.RenameIndex(
            model_name='usermfaprofile',
            new_name='users_userm_user_id_8ec2c4_idx',
            old_name='users_userm_user_id_88c74a_idx',
        ),
        migrations.RenameIndex(
            model_name='webauthncredential',
            new_name='users_webau_user_id_f1702c_idx',
            old_name='users_webauth_user_id_3c7d0a_idx',
        ),
    ]
