# Generated by Django 4.2.10 on 2026-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_users_mfasess_token_h_6202b6_idx_users_mfase_token_h_7521eb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfasession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
