# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0014_mfasession_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='primary_users',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='facilities',
            field=models.ManyToManyField(
                blank=True,
                related_name='assigned_users',
                to='core.facility',
            ),
        ),
    ]
