# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_patient_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    PatientProfile = apps.get_model('users', 'PatientProfile')

    fallback = _get_fallback_facility(Facility)
    patients = list(
        PatientProfile.objects.filter(facility__isnull=True)
        .select_related('created_by__primary_facility', 'created_by__staff_profile__primary_facility')
    )

    for patient in patients:
        facility = None
        created_by = patient.created_by
        if created_by and getattr(created_by, 'primary_facility_id', None):
            facility = created_by.primary_facility
        else:
            staff = getattr(created_by, 'staff_profile', None) if created_by else None
            if staff and getattr(staff, 'primary_facility_id', None):
                facility = staff.primary_facility
        if not facility and fallback:
            facility = fallback
        if facility:
            patient.facility_id = facility.id

    if patients:
        PatientProfile.objects.bulk_update(patients, ['facility'])

    if PatientProfile.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "PatientProfile facility backfill incomplete. "
            "Assign primary_facility or set DEFAULT_FACILITY_CODE."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0015_user_facility_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='patients',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_patient_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patientprofile',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='patients',
                to='core.facility',
            ),
        ),
    ]
