# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('users', '0016_patient_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='facility',
            field=models.ForeignKey(help_text='Facility responsible for this patient record', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facilities',
            field=models.ManyToManyField(blank=True, help_text='Facilities this user can access', related_name='assigned_users', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_facility',
            field=models.ForeignKey(blank=True, help_text='Primary facility for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='core.facility'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['facility'], name='users_patie_facilit_57b799_idx'),
        ),
    ]
