# Generated by Django 4.2.10 on 2026-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_sessions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='practitionerprofile',
            index=models.Index(fields=['specialization'], name='users_pract_special_bff76b_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['primary_facility', 'department'], name='users_staff_primary_9ca026_idx'),
        ),
    ]
