# Generated by Django 4.2.10 on 2026-01-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_users_sess_refresh_jti_idx_users_users_refresh_f5b1e9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
