# Generated by Django 4.2.10 on 2026-02-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_backfill_admin_is_staff'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patientprofile',
            name='users_patient_mrn_trgm',
        ),
        migrations.RemoveIndex(
            model_name='patientprofile',
            name='users_patient_nhis_trgm',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_first_name_trgm',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_last_name_trgm',
        ),
    ]
