# Generated by Django 4.2.10 on 2026-02-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_core_singletons'),
        ('users', '0024_user_password_change_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_record_number',
            field=models.CharField(help_text='Patient MRN (e.g., MRN-MAIN-2026-0000001)', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(help_text='Staff identifier (e.g., EMP-MAIN-2026-0000001)', max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='IdentifierSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('mrn', 'MRN'), ('employee', 'Employee ID')], max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier_sequences', to='core.facility')),
            ],
            options={
                'db_table': 'users_identifier_sequence',
            },
        ),
        migrations.AddConstraint(
            model_name='identifiersequence',
            constraint=models.UniqueConstraint(fields=('facility', 'identifier_type', 'year'), name='users_identifier_seq_facility_type_year_uniq'),
        ),
        migrations.AddConstraint(
            model_name='identifiersequence',
            constraint=models.CheckConstraint(check=models.Q(('next_number__gte', 1)), name='users_identifier_seq_next_number_gte_1'),
        ),
    ]
