# Generated by Django 4.2.29 on 2026-05-01 14:50

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feature_entitlement_override'),
        ('users', '0026_merge_users_migration_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSearchIndex',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_projection', serialize=False, to='users.staff')),
                ('search_document', models.TextField(blank=True)),
                ('employee_id', models.CharField(blank=True, max_length=40)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_search_indexes', to='core.facility')),
            ],
            options={
                'indexes': [models.Index(fields=['facility'], name='staff_search_idx_facility_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='staff_search_idx_doc_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
