"""
Cardiac marker tests.
LOINC codes sourced from loinc.org
"""

CARDIAC_TESTS = [
    {
        'code': 'TROPONIN_I',
        'loinc_code': '10839-9',
        'name': 'Troponin I, High Sensitivity',
        'short_name': 'hs-TnI',
        'category': 'cardiac',
        'description': 'High-sensitivity cardiac troponin I - myocardial injury marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal_male': {'low': 0, 'high': 20, 'unit': 'ng/L'},
            'normal_female': {'low': 0, 'high': 15, 'unit': 'ng/L'},
        },
        'unit': 'ng/L',
        'tat_hours': 1,
        'price': 50.00,
        'special_instructions': 'STAT test for chest pain evaluation',
    },
    {
        'code': 'TROPONIN_T',
        'loinc_code': '6598-7',
        'name': 'Troponin T, High Sensitivity',
        'short_name': 'hs-TnT',
        'category': 'cardiac',
        'description': 'High-sensitivity cardiac troponin T - myocardial injury marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 14, 'unit': 'ng/L'},
        },
        'unit': 'ng/L',
        'tat_hours': 1,
        'price': 50.00,
        'special_instructions': 'STAT test for chest pain evaluation',
    },
    {
        'code': 'BNP',
        'loinc_code': '30934-4',
        'name': 'B-type Natriuretic Peptide',
        'short_name': 'BNP',
        'category': 'cardiac',
        'description': 'Heart failure marker - released by ventricles under stress',
        'specimen_type': 'Plasma',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 100, 'unit': 'pg/mL'},
            'grey_zone': {'low': 100, 'high': 400, 'unit': 'pg/mL'},
            'elevated': {'low': 400, 'high': 99999, 'unit': 'pg/mL'},
        },
        'unit': 'pg/mL',
        'tat_hours': 2,
        'price': 55.00,
    },
    {
        'code': 'NT_PROBNP',
        'loinc_code': '33762-6',
        'name': 'NT-proBNP',
        'short_name': 'NT-proBNP',
        'category': 'cardiac',
        'description': 'N-terminal pro-BNP - heart failure marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'age_lt_75': {'low': 0, 'high': 125, 'unit': 'pg/mL'},
            'age_75_plus': {'low': 0, 'high': 450, 'unit': 'pg/mL'},
        },
        'unit': 'pg/mL',
        'tat_hours': 2,
        'price': 55.00,
    },
    {
        'code': 'CK_TOTAL',
        'loinc_code': '2157-6',
        'name': 'Creatine Kinase, Total',
        'short_name': 'CK Total',
        'category': 'cardiac',
        'description': 'Total creatine kinase - muscle/heart damage marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 30, 'high': 200, 'unit': 'U/L'},
            'adult_female': {'low': 30, 'high': 170, 'unit': 'U/L'},
        },
        'unit': 'U/L',
        'tat_hours': 2,
        'price': 30.00,
    },
    {
        'code': 'CK_MB',
        'loinc_code': '13969-1',
        'name': 'Creatine Kinase-MB',
        'short_name': 'CK-MB',
        'category': 'cardiac',
        'description': 'Cardiac-specific CK isoenzyme',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 5, 'unit': 'ng/mL'},
        },
        'unit': 'ng/mL',
        'tat_hours': 2,
        'price': 40.00,
    },
    {
        'code': 'MYOGLOBIN',
        'loinc_code': '2639-3',
        'name': 'Myoglobin',
        'short_name': 'Myoglobin',
        'category': 'cardiac',
        'description': 'Early marker of muscle damage (rises before troponin)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 28, 'high': 72, 'unit': 'ng/mL'},
            'adult_female': {'low': 25, 'high': 58, 'unit': 'ng/mL'},
        },
        'unit': 'ng/mL',
        'tat_hours': 1,
        'price': 45.00,
    },
    {
        'code': 'HOMOCYSTEINE',
        'loinc_code': '2714-4',
        'name': 'Homocysteine',
        'short_name': 'Homocysteine',
        'category': 'cardiac',
        'description': 'Cardiovascular risk factor',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'optimal': {'low': 0, 'high': 10, 'unit': 'umol/L'},
            'normal': {'low': 0, 'high': 15, 'unit': 'umol/L'},
        },
        'unit': 'umol/L',
        'tat_hours': 24,
        'price': 50.00,
        'special_instructions': 'Fasting specimen required',
    },
    {
        'code': 'CRP_HS',
        'loinc_code': '30522-7',
        'name': 'C-Reactive Protein, High Sensitivity',
        'short_name': 'hs-CRP',
        'category': 'cardiac',
        'description': 'Cardiovascular risk marker - inflammation',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'low_risk': {'low': 0, 'high': 1.0, 'unit': 'mg/L'},
            'average_risk': {'low': 1.0, 'high': 3.0, 'unit': 'mg/L'},
            'high_risk': {'low': 3.0, 'high': 999, 'unit': 'mg/L'},
        },
        'unit': 'mg/L',
        'tat_hours': 24,
        'price': 35.00,
    },
    {
        'code': 'D_DIMER',
        'loinc_code': '48065-7',
        'name': 'D-Dimer',
        'short_name': 'D-Dimer',
        'category': 'cardiac',
        'description': 'Fibrin degradation product - PE/DVT screening',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 500, 'unit': 'ng/mL FEU'},
            'age_adjusted': {'low': 0, 'high': 10, 'unit': 'x age (if >50)', 'note': 'Use age x 10 for patients over 50'},
        },
        'unit': 'ng/mL FEU',
        'tat_hours': 2,
        'price': 45.00,
        'special_instructions': 'Fill tube to line, gentle inversion only',
    },
]
