"""
General chemistry lab tests.
LOINC codes sourced from loinc.org
"""

CHEMISTRY_TESTS = [
    {
        'code': 'GLUCOSE',
        'loinc_code': '2345-7',
        'name': 'Glucose',
        'short_name': 'Glucose',
        'category': 'chemistry',
        'description': 'Blood glucose level',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'fasting': {'low': 70, 'high': 100, 'unit': 'mg/dL'},
            'random': {'low': 70, 'high': 140, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'CALCIUM',
        'loinc_code': '17861-6',
        'name': 'Calcium, Total',
        'short_name': 'Calcium',
        'category': 'chemistry',
        'description': 'Total serum calcium level',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 8.6, 'high': 10.2, 'unit': 'mg/dL'},
            'child': {'low': 8.8, 'high': 10.8, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 2,
        'price': 25.00,
    },
    {
        'code': 'CALCIUM_ION',
        'loinc_code': '1994-3',
        'name': 'Calcium, Ionized',
        'short_name': 'Ionized Ca',
        'category': 'chemistry',
        'description': 'Ionized (free) calcium - physiologically active form',
        'specimen_type': 'Whole Blood',
        'container_type': 'Green Top (Heparin)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 4.6, 'high': 5.3, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 1,
        'price': 35.00,
        'special_instructions': 'Process immediately, keep on ice',
    },
    {
        'code': 'MAGNESIUM',
        'loinc_code': '19123-9',
        'name': 'Magnesium',
        'short_name': 'Magnesium',
        'category': 'chemistry',
        'description': 'Serum magnesium level',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 1.7, 'high': 2.2, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 2,
        'price': 25.00,
    },
    {
        'code': 'PHOSPHORUS',
        'loinc_code': '2777-1',
        'name': 'Phosphorus',
        'short_name': 'Phosphorus',
        'category': 'chemistry',
        'description': 'Serum phosphorus level',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 2.5, 'high': 4.5, 'unit': 'mg/dL'},
            'child': {'low': 4.0, 'high': 7.0, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 2,
        'price': 25.00,
    },
    {
        'code': 'URIC_ACID',
        'loinc_code': '3084-1',
        'name': 'Uric Acid',
        'short_name': 'Uric Acid',
        'category': 'chemistry',
        'description': 'Serum uric acid - gout marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 3.5, 'high': 7.2, 'unit': 'mg/dL'},
            'adult_female': {'low': 2.5, 'high': 6.2, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 2,
        'price': 25.00,
    },
    {
        'code': 'TOTAL_PROTEIN',
        'loinc_code': '2885-2',
        'name': 'Total Protein',
        'short_name': 'Total Protein',
        'category': 'chemistry',
        'description': 'Total serum protein (albumin + globulins)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 6.0, 'high': 8.3, 'unit': 'g/dL'},
        },
        'unit': 'g/dL',
        'tat_hours': 2,
        'price': 25.00,
    },
    {
        'code': 'IRON',
        'loinc_code': '2498-4',
        'name': 'Iron',
        'short_name': 'Iron',
        'category': 'chemistry',
        'description': 'Serum iron level',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 65, 'high': 175, 'unit': 'mcg/dL'},
            'adult_female': {'low': 50, 'high': 170, 'unit': 'mcg/dL'},
        },
        'unit': 'mcg/dL',
        'tat_hours': 4,
        'price': 30.00,
        'special_instructions': 'Fasting specimen preferred, morning collection',
    },
    {
        'code': 'TIBC',
        'loinc_code': '2500-7',
        'name': 'Total Iron Binding Capacity',
        'short_name': 'TIBC',
        'category': 'chemistry',
        'description': 'Indirect measure of transferrin',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 250, 'high': 400, 'unit': 'mcg/dL'},
        },
        'unit': 'mcg/dL',
        'tat_hours': 4,
        'price': 30.00,
    },
    {
        'code': 'FERRITIN',
        'loinc_code': '2276-4',
        'name': 'Ferritin',
        'short_name': 'Ferritin',
        'category': 'chemistry',
        'description': 'Iron storage protein - best indicator of iron stores',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 30, 'high': 400, 'unit': 'ng/mL'},
            'adult_female': {'low': 15, 'high': 150, 'unit': 'ng/mL'},
            'post_menopausal': {'low': 30, 'high': 400, 'unit': 'ng/mL'},
        },
        'unit': 'ng/mL',
        'tat_hours': 4,
        'price': 35.00,
    },
    {
        'code': 'TRANSFERRIN',
        'loinc_code': '3034-6',
        'name': 'Transferrin',
        'short_name': 'Transferrin',
        'category': 'chemistry',
        'description': 'Iron transport protein',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 200, 'high': 360, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 35.00,
    },
    {
        'code': 'VITAMIN_B12',
        'loinc_code': '2132-9',
        'name': 'Vitamin B12',
        'short_name': 'Vitamin B12',
        'category': 'chemistry',
        'description': 'Serum vitamin B12 (cobalamin) level',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 200, 'high': 900, 'unit': 'pg/mL'},
        },
        'unit': 'pg/mL',
        'tat_hours': 24,
        'price': 45.00,
    },
    {
        'code': 'FOLATE',
        'loinc_code': '2284-8',
        'name': 'Folate (Folic Acid)',
        'short_name': 'Folate',
        'category': 'chemistry',
        'description': 'Serum folate level',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 3.0, 'high': 17.0, 'unit': 'ng/mL'},
        },
        'unit': 'ng/mL',
        'tat_hours': 24,
        'price': 45.00,
    },
    {
        'code': 'VITAMIN_D',
        'loinc_code': '1989-3',
        'name': 'Vitamin D, 25-Hydroxy',
        'short_name': 'Vitamin D',
        'category': 'chemistry',
        'description': '25-hydroxyvitamin D - best measure of vitamin D status',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'deficient': {'low': 0, 'high': 20, 'unit': 'ng/mL'},
            'insufficient': {'low': 20, 'high': 30, 'unit': 'ng/mL'},
            'sufficient': {'low': 30, 'high': 100, 'unit': 'ng/mL'},
        },
        'unit': 'ng/mL',
        'tat_hours': 24,
        'price': 55.00,
    },
    {
        'code': 'LDH',
        'loinc_code': '2532-0',
        'name': 'Lactate Dehydrogenase',
        'short_name': 'LDH',
        'category': 'chemistry',
        'description': 'Enzyme found in many tissues - marker of tissue damage',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 140, 'high': 280, 'unit': 'U/L'},
        },
        'unit': 'U/L',
        'tat_hours': 4,
        'price': 25.00,
        'special_instructions': 'Avoid hemolysis - will falsely elevate results',
    },
    {
        'code': 'AMMONIA',
        'loinc_code': '1842-4',
        'name': 'Ammonia',
        'short_name': 'Ammonia',
        'category': 'chemistry',
        'description': 'Blood ammonia level - hepatic encephalopathy marker',
        'specimen_type': 'Plasma',
        'container_type': 'Green Top (Heparin)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 15, 'high': 45, 'unit': 'mcg/dL'},
        },
        'unit': 'mcg/dL',
        'tat_hours': 1,
        'price': 40.00,
        'special_instructions': 'Place on ice immediately, process within 15 minutes',
    },
    {
        'code': 'LACTATE',
        'loinc_code': '2524-7',
        'name': 'Lactate (Lactic Acid)',
        'short_name': 'Lactate',
        'category': 'chemistry',
        'description': 'Blood lactate - tissue hypoxia marker',
        'specimen_type': 'Plasma',
        'container_type': 'Gray Top (Sodium Fluoride)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'venous': {'low': 0.5, 'high': 2.2, 'unit': 'mmol/L'},
            'arterial': {'low': 0.5, 'high': 1.6, 'unit': 'mmol/L'},
        },
        'unit': 'mmol/L',
        'tat_hours': 1,
        'price': 35.00,
        'special_instructions': 'Avoid tourniquet use, collect without fist clenching',
    },
]
