"""
Coagulation tests.
LOINC codes sourced from loinc.org
"""

COAGULATION_TESTS = [
    {
        'code': 'PT',
        'loinc_code': '5902-2',
        'name': 'Prothrombin Time',
        'short_name': 'PT',
        'category': 'coagulation',
        'description': 'Extrinsic pathway coagulation test - warfarin monitoring',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 10.0, 'high': 13.0, 'unit': 'seconds'},
        },
        'unit': 'seconds',
        'tat_hours': 2,
        'price': 25.00,
        'special_instructions': 'Fill tube exactly to line. Reject under-filled specimens.',
    },
    {
        'code': 'INR',
        'loinc_code': '6301-6',
        'name': 'International Normalized Ratio',
        'short_name': 'INR',
        'category': 'coagulation',
        'description': 'Standardized PT ratio for anticoagulation monitoring',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 0.9, 'high': 1.1, 'unit': 'ratio'},
            'therapeutic_afib': {'low': 2.0, 'high': 3.0, 'unit': 'ratio'},
            'therapeutic_valve': {'low': 2.5, 'high': 3.5, 'unit': 'ratio'},
        },
        'unit': 'ratio',
        'tat_hours': 2,
        'price': 0.00,  # Calculated from PT
    },
    {
        'code': 'PTT',
        'loinc_code': '3173-2',
        'name': 'Partial Thromboplastin Time',
        'short_name': 'PTT',
        'category': 'coagulation',
        'description': 'Intrinsic pathway coagulation test - heparin monitoring',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 25.0, 'high': 35.0, 'unit': 'seconds'},
        },
        'unit': 'seconds',
        'tat_hours': 2,
        'price': 25.00,
        'special_instructions': 'Fill tube exactly to line.',
    },
    {
        'code': 'APTT',
        'loinc_code': '14979-9',
        'name': 'Activated Partial Thromboplastin Time',
        'short_name': 'aPTT',
        'category': 'coagulation',
        'description': 'Activated PTT - more sensitive for intrinsic pathway',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 25.0, 'high': 37.0, 'unit': 'seconds'},
            'therapeutic_heparin': {'low': 50.0, 'high': 70.0, 'unit': 'seconds'},
        },
        'unit': 'seconds',
        'tat_hours': 2,
        'price': 25.00,
    },
    {
        'code': 'FIBRINOGEN',
        'loinc_code': '3255-7',
        'name': 'Fibrinogen',
        'short_name': 'Fibrinogen',
        'category': 'coagulation',
        'description': 'Clotting factor - acute phase reactant',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 200, 'high': 400, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 35.00,
    },
    {
        'code': 'THROMBIN_TIME',
        'loinc_code': '3243-3',
        'name': 'Thrombin Time',
        'short_name': 'TT',
        'category': 'coagulation',
        'description': 'Tests final step of coagulation - fibrinogen to fibrin',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 14.0, 'high': 19.0, 'unit': 'seconds'},
        },
        'unit': 'seconds',
        'tat_hours': 4,
        'price': 35.00,
    },
    {
        'code': 'ANTI_XA',
        'loinc_code': '3207-8',
        'name': 'Anti-Xa Activity (Heparin)',
        'short_name': 'Anti-Xa',
        'category': 'coagulation',
        'description': 'LMWH and UFH monitoring',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'lmwh_prophylaxis': {'low': 0.2, 'high': 0.5, 'unit': 'IU/mL'},
            'lmwh_treatment': {'low': 0.5, 'high': 1.0, 'unit': 'IU/mL'},
            'ufh_treatment': {'low': 0.3, 'high': 0.7, 'unit': 'IU/mL'},
        },
        'unit': 'IU/mL',
        'tat_hours': 4,
        'price': 50.00,
        'special_instructions': 'Draw 4 hours post-dose for peak levels',
    },
    {
        'code': 'BLEEDING_TIME',
        'loinc_code': '11067-6',
        'name': 'Bleeding Time',
        'short_name': 'Bleeding Time',
        'category': 'coagulation',
        'description': 'Primary hemostasis assessment (rarely used now)',
        'specimen_type': 'In Vivo Test',
        'container_type': 'N/A',
        'volume_required': 'N/A',
        'reference_ranges': {
            'normal': {'low': 2, 'high': 9, 'unit': 'minutes'},
        },
        'unit': 'minutes',
        'tat_hours': 0.5,
        'price': 30.00,
        'special_instructions': 'Performed at bedside. Avoid if platelet count < 100K.',
    },
    {
        'code': 'MIXING_STUDY',
        'loinc_code': '6012-9',
        'name': 'Mixing Study (PT/PTT)',
        'short_name': 'Mixing Study',
        'category': 'coagulation',
        'description': 'Distinguishes factor deficiency from inhibitor',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '5.4 mL (2 tubes)',
        'reference_ranges': {},
        'unit': 'text',
        'tat_hours': 4,
        'price': 75.00,
        'special_instructions': 'Order when PT or PTT is prolonged',
    },
    {
        'code': 'FACTOR_VIII',
        'loinc_code': '3209-4',
        'name': 'Factor VIII Activity',
        'short_name': 'Factor VIII',
        'category': 'coagulation',
        'description': 'Hemophilia A screening/monitoring',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 50, 'high': 150, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 24,
        'price': 85.00,
    },
    {
        'code': 'FACTOR_IX',
        'loinc_code': '3187-2',
        'name': 'Factor IX Activity',
        'short_name': 'Factor IX',
        'category': 'coagulation',
        'description': 'Hemophilia B screening/monitoring',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 50, 'high': 150, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 24,
        'price': 85.00,
    },
    {
        'code': 'VWF_AG',
        'loinc_code': '27816-8',
        'name': 'von Willebrand Factor Antigen',
        'short_name': 'vWF Ag',
        'category': 'coagulation',
        'description': 'von Willebrand disease screening',
        'specimen_type': 'Plasma',
        'container_type': 'Blue Top (Citrate)',
        'volume_required': '2.7 mL',
        'reference_ranges': {
            'normal': {'low': 50, 'high': 200, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 72,
        'price': 95.00,
    },
]
