"""
Diabetes-related tests.
LOINC codes sourced from loinc.org
"""

DIABETES_TESTS = [
    {
        'code': 'HBA1C',
        'loinc_code': '4548-4',
        'name': 'Hemoglobin A1c',
        'short_name': 'HbA1c',
        'category': 'chemistry',
        'description': 'Glycated hemoglobin - 2-3 month average glucose control',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 4.0, 'high': 5.6, 'unit': '%'},
            'prediabetes': {'low': 5.7, 'high': 6.4, 'unit': '%'},
            'diabetes_diagnosis': {'low': 6.5, 'high': 20.0, 'unit': '%'},
            'diabetes_goal': {'low': 0, 'high': 7.0, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 24,
        'price': 45.00,
        'special_instructions': 'Fasting not required. Inaccurate with hemoglobin variants.',
    },
    {
        'code': 'FASTING_GLUCOSE',
        'loinc_code': '1558-6',
        'name': 'Fasting Glucose',
        'short_name': 'Fasting Glucose',
        'category': 'chemistry',
        'description': 'Blood glucose after 8+ hour fast',
        'specimen_type': 'Serum',
        'container_type': 'Gray Top (Sodium Fluoride)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 70, 'high': 99, 'unit': 'mg/dL'},
            'prediabetes': {'low': 100, 'high': 125, 'unit': 'mg/dL'},
            'diabetes': {'low': 126, 'high': 999, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 2,
        'price': 20.00,
        'special_instructions': 'Patient must fast for 8+ hours. Water permitted.',
    },
    {
        'code': 'OGTT_2HR',
        'loinc_code': '1518-0',
        'name': '2-Hour Oral Glucose Tolerance Test',
        'short_name': '2hr OGTT',
        'category': 'chemistry',
        'description': 'Glucose 2 hours after 75g glucose load',
        'specimen_type': 'Serum',
        'container_type': 'Gray Top (Sodium Fluoride)',
        'volume_required': '2 mL per draw',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 139, 'unit': 'mg/dL'},
            'prediabetes': {'low': 140, 'high': 199, 'unit': 'mg/dL'},
            'diabetes': {'low': 200, 'high': 999, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 40.00,
        'special_instructions': 'Overnight fast. 75g glucose load. Draw at 0 and 2 hours.',
    },
    {
        'code': 'FRUCTOSAMINE',
        'loinc_code': '1784-8',
        'name': 'Fructosamine',
        'short_name': 'Fructosamine',
        'category': 'chemistry',
        'description': 'Glycated protein - 2-3 week glucose average',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 200, 'high': 285, 'unit': 'umol/L'},
        },
        'unit': 'umol/L',
        'tat_hours': 24,
        'price': 40.00,
        'special_instructions': 'Useful when HbA1c unreliable (hemoglobin variants, transfusions)',
    },
    {
        'code': 'INSULIN_FASTING',
        'loinc_code': '1549-5',
        'name': 'Insulin, Fasting',
        'short_name': 'Fasting Insulin',
        'category': 'endocrine',
        'description': 'Fasting insulin level - insulin resistance assessment',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 2.6, 'high': 24.9, 'unit': 'uIU/mL'},
        },
        'unit': 'uIU/mL',
        'tat_hours': 24,
        'price': 50.00,
        'special_instructions': 'Patient must fast for 8+ hours',
    },
    {
        'code': 'C_PEPTIDE',
        'loinc_code': '1986-9',
        'name': 'C-Peptide',
        'short_name': 'C-Peptide',
        'category': 'endocrine',
        'description': 'Insulin production marker - distinguishes Type 1 vs Type 2',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'fasting': {'low': 0.8, 'high': 3.9, 'unit': 'ng/mL'},
        },
        'unit': 'ng/mL',
        'tat_hours': 24,
        'price': 55.00,
        'special_instructions': 'Fasting specimen preferred',
    },
    {
        'code': 'HOMA_IR',
        'loinc_code': '63504-3',
        'name': 'HOMA-IR (Insulin Resistance)',
        'short_name': 'HOMA-IR',
        'category': 'chemistry',
        'description': 'Calculated insulin resistance index',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 2.5, 'unit': 'index'},
            'insulin_resistant': {'low': 2.5, 'high': 999, 'unit': 'index'},
        },
        'unit': 'index',
        'tat_hours': 24,
        'price': 0.00,  # Calculated
        'special_instructions': 'Calculated: (Fasting Glucose x Fasting Insulin) / 405',
    },
    {
        'code': 'GAD65_AB',
        'loinc_code': '13926-1',
        'name': 'GAD65 Antibodies',
        'short_name': 'GAD65 Ab',
        'category': 'immunology',
        'description': 'Type 1 diabetes autoantibody marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'low': 0, 'high': 5.0, 'unit': 'U/mL'},
        },
        'unit': 'U/mL',
        'tat_hours': 72,
        'price': 75.00,
    },
    {
        'code': 'IA2_AB',
        'loinc_code': '56540-9',
        'name': 'Islet Antigen 2 Antibodies',
        'short_name': 'IA-2 Ab',
        'category': 'immunology',
        'description': 'Type 1 diabetes autoantibody marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'low': 0, 'high': 7.5, 'unit': 'U/mL'},
        },
        'unit': 'U/mL',
        'tat_hours': 72,
        'price': 75.00,
    },
]
