"""
Hematology lab tests - Complete Blood Count and related tests.
LOINC codes sourced from loinc.org
"""

HEMATOLOGY_TESTS = [
    {
        'code': 'WBC',
        'loinc_code': '6690-2',
        'name': 'White Blood Cell Count',
        'short_name': 'WBC',
        'category': 'hematology',
        'description': 'Total white blood cell count - measures infection fighting cells',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 4.5, 'high': 11.0, 'unit': 'K/uL'},
            'child': {'low': 5.0, 'high': 15.0, 'unit': 'K/uL'},
            'newborn': {'low': 9.0, 'high': 30.0, 'unit': 'K/uL'},
        },
        'unit': 'K/uL',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'RBC',
        'loinc_code': '789-8',
        'name': 'Red Blood Cell Count',
        'short_name': 'RBC',
        'category': 'hematology',
        'description': 'Total red blood cell count - oxygen carrying cells',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult_male': {'low': 4.5, 'high': 5.9, 'unit': 'M/uL'},
            'adult_female': {'low': 4.1, 'high': 5.1, 'unit': 'M/uL'},
            'child': {'low': 4.0, 'high': 5.5, 'unit': 'M/uL'},
        },
        'unit': 'M/uL',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'HGB',
        'loinc_code': '718-7',
        'name': 'Hemoglobin',
        'short_name': 'Hemoglobin',
        'category': 'hematology',
        'description': 'Hemoglobin concentration - oxygen carrying protein',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult_male': {'low': 13.5, 'high': 17.5, 'unit': 'g/dL'},
            'adult_female': {'low': 12.0, 'high': 15.5, 'unit': 'g/dL'},
            'child': {'low': 11.0, 'high': 14.0, 'unit': 'g/dL'},
            'newborn': {'low': 14.0, 'high': 24.0, 'unit': 'g/dL'},
        },
        'unit': 'g/dL',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'HCT',
        'loinc_code': '4544-3',
        'name': 'Hematocrit',
        'short_name': 'Hematocrit',
        'category': 'hematology',
        'description': 'Packed cell volume - percentage of blood volume occupied by RBCs',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult_male': {'low': 38.3, 'high': 48.6, 'unit': '%'},
            'adult_female': {'low': 35.5, 'high': 44.9, 'unit': '%'},
            'child': {'low': 35.0, 'high': 45.0, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'PLT',
        'loinc_code': '777-3',
        'name': 'Platelet Count',
        'short_name': 'Platelets',
        'category': 'hematology',
        'description': 'Platelet count - cells involved in clotting',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 150, 'high': 400, 'unit': 'K/uL'},
            'child': {'low': 150, 'high': 450, 'unit': 'K/uL'},
        },
        'unit': 'K/uL',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'MCV',
        'loinc_code': '787-2',
        'name': 'Mean Corpuscular Volume',
        'short_name': 'MCV',
        'category': 'hematology',
        'description': 'Average red blood cell size',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 80, 'high': 100, 'unit': 'fL'},
        },
        'unit': 'fL',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'MCH',
        'loinc_code': '785-6',
        'name': 'Mean Corpuscular Hemoglobin',
        'short_name': 'MCH',
        'category': 'hematology',
        'description': 'Average hemoglobin per red blood cell',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 27, 'high': 33, 'unit': 'pg'},
        },
        'unit': 'pg',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'MCHC',
        'loinc_code': '786-4',
        'name': 'Mean Corpuscular Hemoglobin Concentration',
        'short_name': 'MCHC',
        'category': 'hematology',
        'description': 'Average hemoglobin concentration in red blood cells',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 32, 'high': 36, 'unit': 'g/dL'},
        },
        'unit': 'g/dL',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'RDW',
        'loinc_code': '788-0',
        'name': 'Red Cell Distribution Width',
        'short_name': 'RDW',
        'category': 'hematology',
        'description': 'Variation in red blood cell size',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 11.5, 'high': 14.5, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 2,
        'price': 15.00,
    },
    {
        'code': 'MPV',
        'loinc_code': '32623-1',
        'name': 'Mean Platelet Volume',
        'short_name': 'MPV',
        'category': 'hematology',
        'description': 'Average platelet size',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 7.5, 'high': 11.5, 'unit': 'fL'},
        },
        'unit': 'fL',
        'tat_hours': 2,
        'price': 15.00,
    },
    # Differential counts
    {
        'code': 'NEUT_ABS',
        'loinc_code': '751-8',
        'name': 'Neutrophils Absolute Count',
        'short_name': 'Neutrophils',
        'category': 'hematology',
        'description': 'Absolute neutrophil count - primary infection fighters',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 1.5, 'high': 8.0, 'unit': 'K/uL'},
        },
        'unit': 'K/uL',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'LYMPH_ABS',
        'loinc_code': '731-0',
        'name': 'Lymphocytes Absolute Count',
        'short_name': 'Lymphocytes',
        'category': 'hematology',
        'description': 'Absolute lymphocyte count - immune cells',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 1.0, 'high': 4.8, 'unit': 'K/uL'},
        },
        'unit': 'K/uL',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'MONO_ABS',
        'loinc_code': '742-7',
        'name': 'Monocytes Absolute Count',
        'short_name': 'Monocytes',
        'category': 'hematology',
        'description': 'Absolute monocyte count',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 0.2, 'high': 0.8, 'unit': 'K/uL'},
        },
        'unit': 'K/uL',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'EOS_ABS',
        'loinc_code': '711-2',
        'name': 'Eosinophils Absolute Count',
        'short_name': 'Eosinophils',
        'category': 'hematology',
        'description': 'Absolute eosinophil count - allergic/parasitic response',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 0.0, 'high': 0.5, 'unit': 'K/uL'},
        },
        'unit': 'K/uL',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'BASO_ABS',
        'loinc_code': '704-7',
        'name': 'Basophils Absolute Count',
        'short_name': 'Basophils',
        'category': 'hematology',
        'description': 'Absolute basophil count',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 0.0, 'high': 0.2, 'unit': 'K/uL'},
        },
        'unit': 'K/uL',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'RETIC',
        'loinc_code': '17849-1',
        'name': 'Reticulocyte Count',
        'short_name': 'Reticulocytes',
        'category': 'hematology',
        'description': 'Immature red blood cells - measures bone marrow response',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult': {'low': 0.5, 'high': 2.5, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 4,
        'price': 25.00,
    },
    {
        'code': 'ESR',
        'loinc_code': '30341-2',
        'name': 'Erythrocyte Sedimentation Rate',
        'short_name': 'ESR',
        'category': 'hematology',
        'description': 'Non-specific marker of inflammation',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {
            'adult_male': {'low': 0, 'high': 15, 'unit': 'mm/hr'},
            'adult_female': {'low': 0, 'high': 20, 'unit': 'mm/hr'},
            'elderly_male': {'low': 0, 'high': 20, 'unit': 'mm/hr'},
            'elderly_female': {'low': 0, 'high': 30, 'unit': 'mm/hr'},
        },
        'unit': 'mm/hr',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'BLOOD_SMEAR',
        'loinc_code': '24317-0',
        'name': 'Peripheral Blood Smear Review',
        'short_name': 'Blood Smear',
        'category': 'hematology',
        'description': 'Microscopic examination of blood cells',
        'specimen_type': 'Whole Blood',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '3 mL',
        'reference_ranges': {},
        'unit': 'text',
        'tat_hours': 4,
        'price': 35.00,
        'special_instructions': 'Performed when automated results are abnormal or flagged',
    },
]
