"""
Infectious disease and serology tests.
LOINC codes sourced from loinc.org
"""

INFECTIOUS_DISEASE_TESTS = [
    # Blood Cultures
    {
        'code': 'BLOOD_CULTURE',
        'loinc_code': '600-7',
        'name': 'Blood Culture',
        'short_name': 'Blood Cx',
        'category': 'microbiology',
        'description': 'Aerobic and anaerobic blood culture for sepsis workup',
        'specimen_type': 'Whole Blood',
        'container_type': 'Blood Culture Bottles (Aerobic + Anaerobic)',
        'volume_required': '20 mL (10 mL per bottle)',
        'reference_ranges': {
            'negative': {'value': 'No growth at 5 days', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 120,  # 5 days
        'price': 65.00,
        'special_instructions': 'Collect before antibiotics. Two sets from different sites recommended.',
    },
    # Hepatitis Panel
    {
        'code': 'HEP_A_AB',
        'loinc_code': '5183-9',
        'name': 'Hepatitis A Antibody, Total',
        'short_name': 'Hep A Ab',
        'category': 'serology',
        'description': 'Total HAV antibodies (IgG + IgM)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
            'positive': {'value': 'Positive (immune)', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 40.00,
    },
    {
        'code': 'HEP_A_IGM',
        'loinc_code': '22314-9',
        'name': 'Hepatitis A IgM Antibody',
        'short_name': 'Hep A IgM',
        'category': 'serology',
        'description': 'Acute hepatitis A infection marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 45.00,
    },
    {
        'code': 'HBSAG',
        'loinc_code': '5195-3',
        'name': 'Hepatitis B Surface Antigen',
        'short_name': 'HBsAg',
        'category': 'serology',
        'description': 'Hepatitis B infection marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 40.00,
    },
    {
        'code': 'HBSAB',
        'loinc_code': '10900-9',
        'name': 'Hepatitis B Surface Antibody',
        'short_name': 'HBsAb',
        'category': 'serology',
        'description': 'Hepatitis B immunity marker (vaccination or resolved infection)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'low': 0, 'high': 10, 'unit': 'mIU/mL'},
            'positive_immune': {'low': 10, 'high': 99999, 'unit': 'mIU/mL'},
        },
        'unit': 'mIU/mL',
        'tat_hours': 24,
        'price': 40.00,
    },
    {
        'code': 'HBCAB_TOTAL',
        'loinc_code': '16933-4',
        'name': 'Hepatitis B Core Antibody, Total',
        'short_name': 'HBcAb Total',
        'category': 'serology',
        'description': 'Hepatitis B exposure marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 45.00,
    },
    {
        'code': 'HCV_AB',
        'loinc_code': '16128-1',
        'name': 'Hepatitis C Antibody',
        'short_name': 'HCV Ab',
        'category': 'serology',
        'description': 'Hepatitis C exposure screening',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 45.00,
    },
    {
        'code': 'HCV_RNA',
        'loinc_code': '11011-4',
        'name': 'Hepatitis C Viral Load (RNA)',
        'short_name': 'HCV RNA',
        'category': 'molecular',
        'description': 'Hepatitis C viral RNA quantification',
        'specimen_type': 'Plasma',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '5 mL',
        'reference_ranges': {
            'undetectable': {'low': 0, 'high': 15, 'unit': 'IU/mL'},
        },
        'unit': 'IU/mL',
        'tat_hours': 72,
        'price': 150.00,
    },
    # HIV
    {
        'code': 'HIV_AG_AB',
        'loinc_code': '56888-1',
        'name': 'HIV-1/2 Antigen and Antibody',
        'short_name': 'HIV Ag/Ab',
        'category': 'serology',
        'description': '4th generation HIV screening (p24 antigen + antibodies)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 50.00,
    },
    {
        'code': 'HIV_VIRAL_LOAD',
        'loinc_code': '20447-9',
        'name': 'HIV-1 Viral Load (RNA)',
        'short_name': 'HIV RNA',
        'category': 'molecular',
        'description': 'HIV-1 RNA quantification for monitoring',
        'specimen_type': 'Plasma',
        'container_type': 'Lavender Top (EDTA)',
        'volume_required': '5 mL',
        'reference_ranges': {
            'undetectable': {'low': 0, 'high': 20, 'unit': 'copies/mL'},
        },
        'unit': 'copies/mL',
        'tat_hours': 72,
        'price': 175.00,
    },
    # STI Tests
    {
        'code': 'RPR',
        'loinc_code': '20507-0',
        'name': 'RPR (Syphilis Screen)',
        'short_name': 'RPR',
        'category': 'serology',
        'description': 'Rapid plasma reagin - syphilis screening',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'nonreactive': {'value': 'Nonreactive', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 30.00,
    },
    {
        'code': 'GC_CT_NAAT',
        'loinc_code': '36903-3',
        'name': 'Gonorrhea/Chlamydia NAAT',
        'short_name': 'GC/CT PCR',
        'category': 'molecular',
        'description': 'Nucleic acid test for gonorrhea and chlamydia',
        'specimen_type': 'Urine or Swab',
        'container_type': 'NAAT Transport',
        'volume_required': 'First void urine or swab',
        'reference_ranges': {
            'negative': {'value': 'Not detected', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 65.00,
        'special_instructions': 'First void urine. Do not urinate for 1 hour before collection.',
    },
    # Common Infections
    {
        'code': 'MONO_SPOT',
        'loinc_code': '31418-7',
        'name': 'Mononucleosis Spot Test',
        'short_name': 'Mono Spot',
        'category': 'serology',
        'description': 'Heterophile antibody test for infectious mononucleosis',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 4,
        'price': 30.00,
    },
    {
        'code': 'STREP_RAPID',
        'loinc_code': '78012-2',
        'name': 'Rapid Strep Test',
        'short_name': 'Rapid Strep',
        'category': 'microbiology',
        'description': 'Rapid antigen detection for Group A Streptococcus',
        'specimen_type': 'Throat Swab',
        'container_type': 'Dry Swab or Transport Medium',
        'volume_required': 'Swab',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 0.5,
        'price': 25.00,
        'special_instructions': 'Swab both tonsils and posterior pharynx',
    },
    {
        'code': 'THROAT_CULTURE',
        'loinc_code': '626-2',
        'name': 'Throat Culture',
        'short_name': 'Throat Cx',
        'category': 'microbiology',
        'description': 'Bacterial culture of throat for Group A Strep',
        'specimen_type': 'Throat Swab',
        'container_type': 'Transport Medium',
        'volume_required': 'Swab',
        'reference_ranges': {
            'negative': {'value': 'No Group A Strep isolated', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 48,
        'price': 35.00,
    },
    {
        'code': 'FLU_PCR',
        'loinc_code': '76078-5',
        'name': 'Influenza A/B PCR',
        'short_name': 'Flu PCR',
        'category': 'molecular',
        'description': 'Molecular test for influenza A and B',
        'specimen_type': 'Nasopharyngeal Swab',
        'container_type': 'Viral Transport Medium',
        'volume_required': 'Swab',
        'reference_ranges': {
            'negative': {'value': 'Not detected', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 4,
        'price': 75.00,
    },
    {
        'code': 'COVID_PCR',
        'loinc_code': '94500-6',
        'name': 'SARS-CoV-2 RNA (COVID-19 PCR)',
        'short_name': 'COVID PCR',
        'category': 'molecular',
        'description': 'RT-PCR test for SARS-CoV-2',
        'specimen_type': 'Nasopharyngeal Swab',
        'container_type': 'Viral Transport Medium',
        'volume_required': 'Swab',
        'reference_ranges': {
            'negative': {'value': 'Not detected', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 24,
        'price': 85.00,
    },
    {
        'code': 'RESP_PANEL',
        'loinc_code': '92142-9',
        'name': 'Respiratory Pathogen Panel',
        'short_name': 'Resp Panel',
        'category': 'molecular',
        'description': 'Multiplex PCR for common respiratory pathogens',
        'specimen_type': 'Nasopharyngeal Swab',
        'container_type': 'Viral Transport Medium',
        'volume_required': 'Swab',
        'reference_ranges': {
            'negative': {'value': 'Not detected', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 4,
        'price': 175.00,
        'special_instructions': 'Tests for Flu A/B, RSV, COVID-19, Adenovirus, Rhinovirus, etc.',
    },
    {
        'code': 'CRP',
        'loinc_code': '1988-5',
        'name': 'C-Reactive Protein',
        'short_name': 'CRP',
        'category': 'chemistry',
        'description': 'Acute phase reactant - infection/inflammation marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 10, 'unit': 'mg/L'},
        },
        'unit': 'mg/L',
        'tat_hours': 4,
        'price': 25.00,
    },
    {
        'code': 'PROCALCITONIN',
        'loinc_code': '33959-8',
        'name': 'Procalcitonin',
        'short_name': 'PCT',
        'category': 'chemistry',
        'description': 'Bacterial infection marker - sepsis risk stratification',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'low_risk': {'low': 0, 'high': 0.25, 'unit': 'ng/mL'},
            'possible_sepsis': {'low': 0.25, 'high': 0.5, 'unit': 'ng/mL'},
            'likely_sepsis': {'low': 0.5, 'high': 2.0, 'unit': 'ng/mL'},
            'severe_sepsis': {'low': 2.0, 'high': 999, 'unit': 'ng/mL'},
        },
        'unit': 'ng/mL',
        'tat_hours': 4,
        'price': 55.00,
    },
]
