"""
Lipid panel tests.
LOINC codes sourced from loinc.org
"""

LIPID_TESTS = [
    {
        'code': 'CHOLESTEROL',
        'loinc_code': '2093-3',
        'name': 'Total Cholesterol',
        'short_name': 'Cholesterol',
        'category': 'chemistry',
        'description': 'Total cholesterol level',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'desirable': {'low': 0, 'high': 200, 'unit': 'mg/dL'},
            'borderline_high': {'low': 200, 'high': 239, 'unit': 'mg/dL'},
            'high': {'low': 240, 'high': 999, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 30.00,
        'special_instructions': 'Fasting not required but preferred',
    },
    {
        'code': 'TRIGLYCERIDES',
        'loinc_code': '2571-8',
        'name': 'Triglycerides',
        'short_name': 'Triglycerides',
        'category': 'chemistry',
        'description': 'Serum triglycerides',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 150, 'unit': 'mg/dL'},
            'borderline_high': {'low': 150, 'high': 199, 'unit': 'mg/dL'},
            'high': {'low': 200, 'high': 499, 'unit': 'mg/dL'},
            'very_high': {'low': 500, 'high': 9999, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 30.00,
        'special_instructions': '9-12 hour fasting required for accurate results',
    },
    {
        'code': 'HDL',
        'loinc_code': '2085-9',
        'name': 'HDL Cholesterol',
        'short_name': 'HDL',
        'category': 'chemistry',
        'description': 'High-density lipoprotein (good) cholesterol',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'low_risk_male': {'low': 40, 'high': 999, 'unit': 'mg/dL'},
            'low_risk_female': {'low': 50, 'high': 999, 'unit': 'mg/dL'},
            'high_risk': {'low': 0, 'high': 40, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 30.00,
    },
    {
        'code': 'LDL',
        'loinc_code': '18262-6',
        'name': 'LDL Cholesterol (Calculated)',
        'short_name': 'LDL',
        'category': 'chemistry',
        'description': 'Low-density lipoprotein (bad) cholesterol - calculated',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'optimal': {'low': 0, 'high': 100, 'unit': 'mg/dL'},
            'near_optimal': {'low': 100, 'high': 129, 'unit': 'mg/dL'},
            'borderline_high': {'low': 130, 'high': 159, 'unit': 'mg/dL'},
            'high': {'low': 160, 'high': 189, 'unit': 'mg/dL'},
            'very_high': {'low': 190, 'high': 999, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 0.00,  # Calculated
        'special_instructions': 'Calculated using Friedewald equation when TG < 400',
    },
    {
        'code': 'LDL_DIRECT',
        'loinc_code': '18261-8',
        'name': 'LDL Cholesterol (Direct)',
        'short_name': 'Direct LDL',
        'category': 'chemistry',
        'description': 'Directly measured LDL - used when TG > 400',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'optimal': {'low': 0, 'high': 100, 'unit': 'mg/dL'},
            'near_optimal': {'low': 100, 'high': 129, 'unit': 'mg/dL'},
            'borderline_high': {'low': 130, 'high': 159, 'unit': 'mg/dL'},
            'high': {'low': 160, 'high': 189, 'unit': 'mg/dL'},
            'very_high': {'low': 190, 'high': 999, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 45.00,
        'special_instructions': 'Order when triglycerides > 400 mg/dL',
    },
    {
        'code': 'VLDL',
        'loinc_code': '13458-5',
        'name': 'VLDL Cholesterol',
        'short_name': 'VLDL',
        'category': 'chemistry',
        'description': 'Very low-density lipoprotein cholesterol',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 5, 'high': 40, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 0.00,  # Calculated as TG/5
    },
    {
        'code': 'NON_HDL',
        'loinc_code': '43396-1',
        'name': 'Non-HDL Cholesterol',
        'short_name': 'Non-HDL',
        'category': 'chemistry',
        'description': 'Total cholesterol minus HDL - includes all atherogenic particles',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'optimal': {'low': 0, 'high': 130, 'unit': 'mg/dL'},
            'above_optimal': {'low': 130, 'high': 159, 'unit': 'mg/dL'},
            'borderline_high': {'low': 160, 'high': 189, 'unit': 'mg/dL'},
            'high': {'low': 190, 'high': 219, 'unit': 'mg/dL'},
            'very_high': {'low': 220, 'high': 999, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 0.00,  # Calculated
    },
    {
        'code': 'APO_B',
        'loinc_code': '1884-6',
        'name': 'Apolipoprotein B',
        'short_name': 'Apo B',
        'category': 'chemistry',
        'description': 'Protein component of atherogenic lipoproteins',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'optimal': {'low': 0, 'high': 90, 'unit': 'mg/dL'},
            'desirable': {'low': 0, 'high': 100, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 24,
        'price': 55.00,
    },
    {
        'code': 'LP_A',
        'loinc_code': '43583-4',
        'name': 'Lipoprotein(a)',
        'short_name': 'Lp(a)',
        'category': 'chemistry',
        'description': 'Independent cardiovascular risk factor',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'low_risk': {'low': 0, 'high': 30, 'unit': 'mg/dL'},
            'intermediate_risk': {'low': 30, 'high': 50, 'unit': 'mg/dL'},
            'high_risk': {'low': 50, 'high': 999, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 24,
        'price': 65.00,
    },
]
