"""
Liver function tests (LFTs).
LOINC codes sourced from loinc.org
"""

LIVER_FUNCTION_TESTS = [
    {
        'code': 'ALT',
        'loinc_code': '1742-6',
        'name': 'Alanine Aminotransferase',
        'short_name': 'ALT',
        'category': 'chemistry',
        'description': 'Liver enzyme - specific for liver damage',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 7, 'high': 56, 'unit': 'U/L'},
            'adult_female': {'low': 7, 'high': 45, 'unit': 'U/L'},
        },
        'unit': 'U/L',
        'tat_hours': 4,
        'price': 25.00,
    },
    {
        'code': 'AST',
        'loinc_code': '1920-8',
        'name': 'Aspartate Aminotransferase',
        'short_name': 'AST',
        'category': 'chemistry',
        'description': 'Liver enzyme - also elevated in heart/muscle damage',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 10, 'high': 40, 'unit': 'U/L'},
            'adult_female': {'low': 9, 'high': 32, 'unit': 'U/L'},
        },
        'unit': 'U/L',
        'tat_hours': 4,
        'price': 25.00,
    },
    {
        'code': 'ALP',
        'loinc_code': '6768-6',
        'name': 'Alkaline Phosphatase',
        'short_name': 'Alk Phos',
        'category': 'chemistry',
        'description': 'Liver and bone enzyme - elevated in cholestasis',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 44, 'high': 147, 'unit': 'U/L'},
            'child': {'low': 100, 'high': 400, 'unit': 'U/L'},
        },
        'unit': 'U/L',
        'tat_hours': 4,
        'price': 25.00,
    },
    {
        'code': 'GGT',
        'loinc_code': '2324-2',
        'name': 'Gamma-Glutamyl Transferase',
        'short_name': 'GGT',
        'category': 'chemistry',
        'description': 'Liver enzyme - sensitive for biliary disease and alcohol use',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 9, 'high': 48, 'unit': 'U/L'},
            'adult_female': {'low': 9, 'high': 36, 'unit': 'U/L'},
        },
        'unit': 'U/L',
        'tat_hours': 4,
        'price': 25.00,
    },
    {
        'code': 'BILIRUBIN_TOTAL',
        'loinc_code': '1975-2',
        'name': 'Bilirubin, Total',
        'short_name': 'Total Bili',
        'category': 'chemistry',
        'description': 'Total bilirubin - jaundice marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 0.1, 'high': 1.2, 'unit': 'mg/dL'},
            'newborn_day1': {'low': 0, 'high': 6.0, 'unit': 'mg/dL'},
            'newborn_day2': {'low': 0, 'high': 8.0, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 25.00,
        'special_instructions': 'Protect from light',
    },
    {
        'code': 'BILIRUBIN_DIRECT',
        'loinc_code': '1968-7',
        'name': 'Bilirubin, Direct',
        'short_name': 'Direct Bili',
        'category': 'chemistry',
        'description': 'Conjugated bilirubin - elevated in obstructive jaundice',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 0.0, 'high': 0.3, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 4,
        'price': 25.00,
        'special_instructions': 'Protect from light',
    },
    {
        'code': 'ALBUMIN',
        'loinc_code': '1751-7',
        'name': 'Albumin',
        'short_name': 'Albumin',
        'category': 'chemistry',
        'description': 'Serum albumin - liver synthetic function',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 3.5, 'high': 5.5, 'unit': 'g/dL'},
        },
        'unit': 'g/dL',
        'tat_hours': 4,
        'price': 25.00,
    },
    {
        'code': 'GLOBULIN',
        'loinc_code': '2336-6',
        'name': 'Globulin',
        'short_name': 'Globulin',
        'category': 'chemistry',
        'description': 'Serum globulin (calculated)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 2.0, 'high': 3.5, 'unit': 'g/dL'},
        },
        'unit': 'g/dL',
        'tat_hours': 4,
        'price': 0.00,  # Usually calculated
        'special_instructions': 'Calculated: Total Protein - Albumin',
    },
    {
        'code': 'AG_RATIO',
        'loinc_code': '1759-0',
        'name': 'Albumin/Globulin Ratio',
        'short_name': 'A/G Ratio',
        'category': 'chemistry',
        'description': 'Albumin to globulin ratio',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 1.0, 'high': 2.5, 'unit': 'ratio'},
        },
        'unit': 'ratio',
        'tat_hours': 4,
        'price': 0.00,  # Calculated
    },
]
