"""
Standard lab panels (test bundles).
These group related tests together for convenient ordering.
"""

STANDARD_PANELS = [
    {
        'code': 'CBC',
        'name': 'Complete Blood Count',
        'description': 'Comprehensive blood cell evaluation including WBC, RBC, hemoglobin, hematocrit, platelets, and indices',
        'test_codes': ['WBC', 'RBC', 'HGB', 'HCT', 'PLT', 'MCV', 'MCH', 'MCHC', 'RDW', 'MPV'],
        'price': 65.00,
    },
    {
        'code': 'CBC_DIFF',
        'name': 'Complete Blood Count with Differential',
        'description': 'CBC plus white blood cell differential',
        'test_codes': ['WBC', 'RBC', 'HGB', 'HCT', 'PLT', 'MCV', 'MCH', 'MCHC', 'RDW', 'MPV',
                       'NEUT_ABS', 'LYMPH_ABS', 'MONO_ABS', 'EOS_ABS', 'BASO_ABS'],
        'price': 85.00,
    },
    {
        'code': 'BMP',
        'name': 'Basic Metabolic Panel',
        'description': 'Basic chemistry panel - kidney function and electrolytes',
        'test_codes': ['GLUCOSE', 'BUN', 'CREATININE', 'SODIUM', 'POTASSIUM', 'CHLORIDE', 'CO2', 'CALCIUM'],
        'price': 120.00,
    },
    {
        'code': 'CMP',
        'name': 'Comprehensive Metabolic Panel',
        'description': 'Complete chemistry panel - kidney, liver, and electrolytes',
        'test_codes': ['GLUCOSE', 'BUN', 'CREATININE', 'SODIUM', 'POTASSIUM', 'CHLORIDE', 'CO2',
                       'CALCIUM', 'TOTAL_PROTEIN', 'ALBUMIN', 'BILIRUBIN_TOTAL', 'ALP', 'ALT', 'AST'],
        'price': 180.00,
    },
    {
        'code': 'LFT',
        'name': 'Liver Function Tests',
        'description': 'Comprehensive liver enzyme panel',
        'test_codes': ['ALT', 'AST', 'ALP', 'GGT', 'BILIRUBIN_TOTAL', 'BILIRUBIN_DIRECT', 'ALBUMIN', 'TOTAL_PROTEIN'],
        'price': 110.00,
    },
    {
        'code': 'RFT',
        'name': 'Renal Function Tests',
        'description': 'Kidney function panel',
        'test_codes': ['BUN', 'CREATININE', 'EGFR', 'SODIUM', 'POTASSIUM', 'CHLORIDE', 'CO2'],
        'price': 95.00,
    },
    {
        'code': 'LIPID',
        'name': 'Lipid Panel',
        'description': 'Comprehensive cholesterol and lipid evaluation',
        'test_codes': ['CHOLESTEROL', 'TRIGLYCERIDES', 'HDL', 'LDL', 'VLDL', 'NON_HDL'],
        'price': 95.00,
    },
    {
        'code': 'THYROID',
        'name': 'Thyroid Panel',
        'description': 'Basic thyroid function assessment',
        'test_codes': ['TSH', 'FREE_T4', 'FREE_T3'],
        'price': 110.00,
    },
    {
        'code': 'THYROID_FULL',
        'name': 'Thyroid Panel, Comprehensive',
        'description': 'Complete thyroid evaluation with antibodies',
        'test_codes': ['TSH', 'FREE_T4', 'FREE_T3', 'TOTAL_T4', 'TOTAL_T3', 'TPO_AB', 'THYROGLOBULIN_AB'],
        'price': 225.00,
    },
    {
        'code': 'IRON',
        'name': 'Iron Studies',
        'description': 'Complete iron status evaluation',
        'test_codes': ['IRON', 'TIBC', 'FERRITIN', 'TRANSFERRIN'],
        'price': 95.00,
    },
    {
        'code': 'ANEMIA',
        'name': 'Anemia Panel',
        'description': 'Comprehensive anemia workup',
        'test_codes': ['CBC', 'IRON', 'TIBC', 'FERRITIN', 'VITAMIN_B12', 'FOLATE', 'RETIC'],
        'price': 175.00,
    },
    {
        'code': 'COAG',
        'name': 'Coagulation Panel',
        'description': 'Basic coagulation studies',
        'test_codes': ['PT', 'INR', 'APTT', 'FIBRINOGEN'],
        'price': 85.00,
    },
    {
        'code': 'CARDIAC',
        'name': 'Cardiac Biomarkers',
        'description': 'Acute coronary syndrome workup',
        'test_codes': ['TROPONIN_I', 'CK_MB', 'BNP'],
        'price': 125.00,
    },
    {
        'code': 'ELECTROLYTES',
        'name': 'Electrolyte Panel',
        'description': 'Serum electrolytes',
        'test_codes': ['SODIUM', 'POTASSIUM', 'CHLORIDE', 'CO2', 'CALCIUM', 'MAGNESIUM', 'PHOSPHORUS'],
        'price': 85.00,
    },
    {
        'code': 'DIABETES',
        'name': 'Diabetes Panel',
        'description': 'Diabetes screening and monitoring',
        'test_codes': ['GLUCOSE', 'HBA1C', 'MICROALBUMIN', 'URINE_ACR'],
        'price': 95.00,
    },
    {
        'code': 'DIABETES_COMP',
        'name': 'Diabetes Comprehensive',
        'description': 'Complete diabetes evaluation',
        'test_codes': ['GLUCOSE', 'HBA1C', 'FASTING_GLUCOSE', 'INSULIN_FASTING', 'C_PEPTIDE',
                       'MICROALBUMIN', 'URINE_ACR', 'LIPID'],
        'price': 195.00,
    },
    {
        'code': 'HEPATITIS',
        'name': 'Hepatitis Panel, Acute',
        'description': 'Acute hepatitis screening',
        'test_codes': ['HEP_A_IGM', 'HBSAG', 'HBCAB_TOTAL', 'HCV_AB'],
        'price': 145.00,
    },
    {
        'code': 'HEPATITIS_FULL',
        'name': 'Hepatitis Panel, Complete',
        'description': 'Comprehensive hepatitis screening with immunity check',
        'test_codes': ['HEP_A_AB', 'HEP_A_IGM', 'HBSAG', 'HBSAB', 'HBCAB_TOTAL', 'HCV_AB'],
        'price': 195.00,
    },
    {
        'code': 'STI',
        'name': 'STI Panel',
        'description': 'Sexually transmitted infection screening',
        'test_codes': ['HIV_AG_AB', 'RPR', 'GC_CT_NAAT', 'HCV_AB', 'HBSAG'],
        'price': 175.00,
    },
    {
        'code': 'PRENATAL',
        'name': 'Prenatal Panel',
        'description': 'Initial prenatal laboratory screening',
        'test_codes': ['CBC_DIFF', 'BMP', 'HIV_AG_AB', 'RPR', 'HBSAG', 'HCV_AB', 'UA_COMPLETE',
                       'TSH', 'PREGNANCY_URINE'],
        'price': 295.00,
    },
    {
        'code': 'PREOP',
        'name': 'Pre-Operative Panel',
        'description': 'Pre-surgical laboratory evaluation',
        'test_codes': ['CBC_DIFF', 'BMP', 'PT', 'INR', 'APTT', 'UA_COMPLETE'],
        'price': 175.00,
    },
    {
        'code': 'WELLNESS',
        'name': 'Annual Wellness Panel',
        'description': 'Comprehensive annual health screening',
        'test_codes': ['CBC_DIFF', 'CMP', 'LIPID', 'TSH', 'UA_COMPLETE', 'HBA1C'],
        'price': 245.00,
    },
    {
        'code': 'CARDIAC_RISK',
        'name': 'Cardiovascular Risk Panel',
        'description': 'Cardiovascular disease risk assessment',
        'test_codes': ['LIPID', 'CRP_HS', 'HOMOCYSTEINE', 'APO_B', 'LP_A', 'HBA1C'],
        'price': 225.00,
    },
]
