"""
Renal (kidney) function tests.
LOINC codes sourced from loinc.org
"""

RENAL_FUNCTION_TESTS = [
    {
        'code': 'BUN',
        'loinc_code': '3094-0',
        'name': 'Blood Urea Nitrogen',
        'short_name': 'BUN',
        'category': 'chemistry',
        'description': 'Kidney function marker - urea clearance',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 7, 'high': 20, 'unit': 'mg/dL'},
            'elderly': {'low': 8, 'high': 23, 'unit': 'mg/dL'},
            'child': {'low': 5, 'high': 18, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'CREATININE',
        'loinc_code': '2160-0',
        'name': 'Creatinine',
        'short_name': 'Creatinine',
        'category': 'chemistry',
        'description': 'Kidney function marker - muscle breakdown product',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult_male': {'low': 0.7, 'high': 1.3, 'unit': 'mg/dL'},
            'adult_female': {'low': 0.6, 'high': 1.1, 'unit': 'mg/dL'},
            'child': {'low': 0.3, 'high': 0.7, 'unit': 'mg/dL'},
        },
        'unit': 'mg/dL',
        'tat_hours': 2,
        'price': 20.00,
    },
    {
        'code': 'BUN_CREAT_RATIO',
        'loinc_code': '3097-3',
        'name': 'BUN/Creatinine Ratio',
        'short_name': 'BUN/Cr Ratio',
        'category': 'chemistry',
        'description': 'Helps distinguish pre-renal vs intrinsic renal disease',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 10, 'high': 20, 'unit': 'ratio'},
        },
        'unit': 'ratio',
        'tat_hours': 2,
        'price': 0.00,  # Calculated
    },
    {
        'code': 'EGFR',
        'loinc_code': '33914-3',
        'name': 'Estimated GFR (CKD-EPI)',
        'short_name': 'eGFR',
        'category': 'chemistry',
        'description': 'Estimated glomerular filtration rate - kidney function staging',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'normal': {'low': 90, 'high': 999, 'unit': 'mL/min/1.73m2'},
            'mild_decrease': {'low': 60, 'high': 89, 'unit': 'mL/min/1.73m2'},
            'moderate_decrease': {'low': 30, 'high': 59, 'unit': 'mL/min/1.73m2'},
            'severe_decrease': {'low': 15, 'high': 29, 'unit': 'mL/min/1.73m2'},
            'kidney_failure': {'low': 0, 'high': 15, 'unit': 'mL/min/1.73m2'},
        },
        'unit': 'mL/min/1.73m2',
        'tat_hours': 2,
        'price': 0.00,  # Calculated from creatinine
        'special_instructions': 'Calculated using CKD-EPI equation based on creatinine, age, sex',
    },
    {
        'code': 'CYSTATIN_C',
        'loinc_code': '33863-2',
        'name': 'Cystatin C',
        'short_name': 'Cystatin C',
        'category': 'chemistry',
        'description': 'Alternative kidney function marker - less affected by muscle mass',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 0.53, 'high': 0.95, 'unit': 'mg/L'},
        },
        'unit': 'mg/L',
        'tat_hours': 24,
        'price': 50.00,
    },
    {
        'code': 'CREATININE_CLEARANCE',
        'loinc_code': '2164-2',
        'name': 'Creatinine Clearance (24hr Urine)',
        'short_name': 'CrCl',
        'category': 'chemistry',
        'description': 'Measured creatinine clearance from 24-hour urine',
        'specimen_type': '24-hour Urine + Serum',
        'container_type': '24-hour Urine Container + Red Top',
        'volume_required': '24-hour urine + 2 mL serum',
        'reference_ranges': {
            'adult_male': {'low': 97, 'high': 137, 'unit': 'mL/min'},
            'adult_female': {'low': 88, 'high': 128, 'unit': 'mL/min'},
        },
        'unit': 'mL/min',
        'tat_hours': 24,
        'price': 45.00,
        'special_instructions': 'Complete 24-hour urine collection required. Record total volume.',
    },
    {
        'code': 'MICROALBUMIN',
        'loinc_code': '14957-5',
        'name': 'Microalbumin, Urine',
        'short_name': 'Microalbumin',
        'category': 'chemistry',
        'description': 'Early marker of diabetic nephropathy',
        'specimen_type': 'Random Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '10 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 30, 'unit': 'mg/L'},
            'microalbuminuria': {'low': 30, 'high': 300, 'unit': 'mg/L'},
            'macroalbuminuria': {'low': 300, 'high': 9999, 'unit': 'mg/L'},
        },
        'unit': 'mg/L',
        'tat_hours': 4,
        'price': 35.00,
    },
    {
        'code': 'URINE_ACR',
        'loinc_code': '9318-7',
        'name': 'Albumin/Creatinine Ratio, Urine',
        'short_name': 'Urine ACR',
        'category': 'chemistry',
        'description': 'Urine albumin to creatinine ratio - diabetic nephropathy screening',
        'specimen_type': 'Random Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '10 mL',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 30, 'unit': 'mg/g'},
            'moderately_increased': {'low': 30, 'high': 300, 'unit': 'mg/g'},
            'severely_increased': {'low': 300, 'high': 9999, 'unit': 'mg/g'},
        },
        'unit': 'mg/g',
        'tat_hours': 4,
        'price': 40.00,
        'special_instructions': 'First morning void preferred',
    },
]
