"""
Thyroid function tests.
LOINC codes sourced from loinc.org
"""

THYROID_TESTS = [
    {
        'code': 'TSH',
        'loinc_code': '3016-3',
        'name': 'Thyroid Stimulating Hormone',
        'short_name': 'TSH',
        'category': 'endocrine',
        'description': 'Primary thyroid function screening test',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 0.4, 'high': 4.0, 'unit': 'mIU/L'},
            'pregnancy_t1': {'low': 0.1, 'high': 2.5, 'unit': 'mIU/L'},
            'pregnancy_t2': {'low': 0.2, 'high': 3.0, 'unit': 'mIU/L'},
            'pregnancy_t3': {'low': 0.3, 'high': 3.0, 'unit': 'mIU/L'},
        },
        'unit': 'mIU/L',
        'tat_hours': 24,
        'price': 40.00,
    },
    {
        'code': 'FREE_T4',
        'loinc_code': '3024-7',
        'name': 'Free T4 (Thyroxine)',
        'short_name': 'Free T4',
        'category': 'endocrine',
        'description': 'Free thyroxine - active thyroid hormone',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 0.8, 'high': 1.8, 'unit': 'ng/dL'},
        },
        'unit': 'ng/dL',
        'tat_hours': 24,
        'price': 45.00,
    },
    {
        'code': 'FREE_T3',
        'loinc_code': '3051-0',
        'name': 'Free T3 (Triiodothyronine)',
        'short_name': 'Free T3',
        'category': 'endocrine',
        'description': 'Free triiodothyronine - most active thyroid hormone',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 2.3, 'high': 4.2, 'unit': 'pg/mL'},
        },
        'unit': 'pg/mL',
        'tat_hours': 24,
        'price': 45.00,
    },
    {
        'code': 'TOTAL_T4',
        'loinc_code': '3026-2',
        'name': 'Total T4',
        'short_name': 'Total T4',
        'category': 'endocrine',
        'description': 'Total thyroxine (bound + free)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 4.5, 'high': 12.0, 'unit': 'mcg/dL'},
        },
        'unit': 'mcg/dL',
        'tat_hours': 24,
        'price': 40.00,
    },
    {
        'code': 'TOTAL_T3',
        'loinc_code': '3053-6',
        'name': 'Total T3',
        'short_name': 'Total T3',
        'category': 'endocrine',
        'description': 'Total triiodothyronine (bound + free)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 80, 'high': 200, 'unit': 'ng/dL'},
        },
        'unit': 'ng/dL',
        'tat_hours': 24,
        'price': 40.00,
    },
    {
        'code': 'TPO_AB',
        'loinc_code': '8099-4',
        'name': 'Thyroid Peroxidase Antibodies',
        'short_name': 'TPO Ab',
        'category': 'endocrine',
        'description': 'Autoimmune thyroid disease marker (Hashimoto\'s)',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'low': 0, 'high': 34, 'unit': 'IU/mL'},
        },
        'unit': 'IU/mL',
        'tat_hours': 48,
        'price': 55.00,
    },
    {
        'code': 'THYROGLOBULIN_AB',
        'loinc_code': '8098-6',
        'name': 'Thyroglobulin Antibodies',
        'short_name': 'Tg Ab',
        'category': 'endocrine',
        'description': 'Autoimmune thyroid disease marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'low': 0, 'high': 4, 'unit': 'IU/mL'},
        },
        'unit': 'IU/mL',
        'tat_hours': 48,
        'price': 55.00,
    },
    {
        'code': 'TSI',
        'loinc_code': '11580-8',
        'name': 'Thyroid Stimulating Immunoglobulin',
        'short_name': 'TSI',
        'category': 'endocrine',
        'description': 'Graves\' disease marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'negative': {'low': 0, 'high': 140, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 72,
        'price': 85.00,
    },
    {
        'code': 'THYROGLOBULIN',
        'loinc_code': '3013-0',
        'name': 'Thyroglobulin',
        'short_name': 'Thyroglobulin',
        'category': 'endocrine',
        'description': 'Thyroid cancer tumor marker',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 0, 'high': 55, 'unit': 'ng/mL'},
            'post_thyroidectomy': {'low': 0, 'high': 1, 'unit': 'ng/mL'},
        },
        'unit': 'ng/mL',
        'tat_hours': 72,
        'price': 75.00,
        'special_instructions': 'Must be interpreted with Tg antibody level',
    },
    {
        'code': 'REVERSE_T3',
        'loinc_code': '3055-1',
        'name': 'Reverse T3',
        'short_name': 'rT3',
        'category': 'endocrine',
        'description': 'Inactive thyroid hormone metabolite',
        'specimen_type': 'Serum',
        'container_type': 'Red Top or Gold Top (SST)',
        'volume_required': '2 mL',
        'reference_ranges': {
            'adult': {'low': 9.2, 'high': 24.1, 'unit': 'ng/dL'},
        },
        'unit': 'ng/dL',
        'tat_hours': 72,
        'price': 65.00,
    },
]
