"""
Urinalysis tests.
LOINC codes sourced from loinc.org
"""

URINALYSIS_TESTS = [
    {
        'code': 'UA_COMPLETE',
        'loinc_code': '24356-8',
        'name': 'Urinalysis, Complete with Microscopy',
        'short_name': 'Urinalysis',
        'category': 'urinalysis',
        'description': 'Complete urinalysis with microscopic examination',
        'specimen_type': 'Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '10 mL',
        'reference_ranges': {
            'color': {'value': 'Yellow', 'unit': 'text'},
            'clarity': {'value': 'Clear', 'unit': 'text'},
            'specific_gravity': {'low': 1.005, 'high': 1.030, 'unit': ''},
            'pH': {'low': 4.5, 'high': 8.0, 'unit': ''},
            'protein': {'value': 'Negative', 'unit': 'text'},
            'glucose': {'value': 'Negative', 'unit': 'text'},
            'ketones': {'value': 'Negative', 'unit': 'text'},
            'blood': {'value': 'Negative', 'unit': 'text'},
            'leukocyte_esterase': {'value': 'Negative', 'unit': 'text'},
            'nitrite': {'value': 'Negative', 'unit': 'text'},
            'WBC': {'low': 0, 'high': 5, 'unit': '/HPF'},
            'RBC': {'low': 0, 'high': 3, 'unit': '/HPF'},
            'bacteria': {'value': 'None seen', 'unit': 'text'},
        },
        'unit': 'various',
        'tat_hours': 4,
        'price': 25.00,
        'special_instructions': 'Clean catch midstream specimen preferred. Process within 2 hours.',
    },
    {
        'code': 'UA_DIPSTICK',
        'loinc_code': '5778-6',
        'name': 'Urinalysis, Dipstick Only',
        'short_name': 'UA Dipstick',
        'category': 'urinalysis',
        'description': 'Chemical analysis only (no microscopy)',
        'specimen_type': 'Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '5 mL',
        'reference_ranges': {
            'specific_gravity': {'low': 1.005, 'high': 1.030, 'unit': ''},
            'pH': {'low': 4.5, 'high': 8.0, 'unit': ''},
            'protein': {'value': 'Negative', 'unit': 'text'},
            'glucose': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'various',
        'tat_hours': 1,
        'price': 15.00,
    },
    {
        'code': 'URINE_CULTURE',
        'loinc_code': '630-4',
        'name': 'Urine Culture and Sensitivity',
        'short_name': 'Urine C&S',
        'category': 'microbiology',
        'description': 'Bacterial culture with antibiotic susceptibility',
        'specimen_type': 'Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '10 mL',
        'reference_ranges': {
            'negative': {'low': 0, 'high': 10000, 'unit': 'CFU/mL'},
            'significant': {'low': 100000, 'high': 999999999, 'unit': 'CFU/mL'},
        },
        'unit': 'CFU/mL',
        'tat_hours': 72,
        'price': 45.00,
        'special_instructions': 'Clean catch midstream. Refrigerate if delay > 2 hours.',
    },
    {
        'code': 'URINE_PROTEIN_24',
        'loinc_code': '2889-4',
        'name': 'Protein, 24-Hour Urine',
        'short_name': '24hr Protein',
        'category': 'urinalysis',
        'description': 'Quantitative protein excretion',
        'specimen_type': '24-hour Urine',
        'container_type': '24-hour Urine Container',
        'volume_required': '24-hour collection',
        'reference_ranges': {
            'normal': {'low': 0, 'high': 150, 'unit': 'mg/24hr'},
            'nephrotic': {'low': 3500, 'high': 99999, 'unit': 'mg/24hr'},
        },
        'unit': 'mg/24hr',
        'tat_hours': 24,
        'price': 35.00,
        'special_instructions': 'Record total volume. Refrigerate during collection.',
    },
    {
        'code': 'URINE_CREATININE_24',
        'loinc_code': '2162-6',
        'name': 'Creatinine, 24-Hour Urine',
        'short_name': '24hr Creatinine',
        'category': 'urinalysis',
        'description': 'Creatinine excretion - validates complete collection',
        'specimen_type': '24-hour Urine',
        'container_type': '24-hour Urine Container',
        'volume_required': '24-hour collection',
        'reference_ranges': {
            'adult_male': {'low': 1000, 'high': 2000, 'unit': 'mg/24hr'},
            'adult_female': {'low': 800, 'high': 1800, 'unit': 'mg/24hr'},
        },
        'unit': 'mg/24hr',
        'tat_hours': 24,
        'price': 25.00,
    },
    {
        'code': 'URINE_OSMOLALITY',
        'loinc_code': '2695-5',
        'name': 'Urine Osmolality',
        'short_name': 'Urine Osm',
        'category': 'urinalysis',
        'description': 'Urine concentration - kidney concentrating ability',
        'specimen_type': 'Random Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '5 mL',
        'reference_ranges': {
            'random': {'low': 50, 'high': 1200, 'unit': 'mOsm/kg'},
            'first_morning': {'low': 500, 'high': 800, 'unit': 'mOsm/kg'},
        },
        'unit': 'mOsm/kg',
        'tat_hours': 4,
        'price': 30.00,
    },
    {
        'code': 'URINE_SODIUM',
        'loinc_code': '2955-3',
        'name': 'Sodium, Urine Random',
        'short_name': 'Urine Na',
        'category': 'urinalysis',
        'description': 'Spot urine sodium - acute kidney injury workup',
        'specimen_type': 'Random Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '5 mL',
        'reference_ranges': {
            'random': {'low': 20, 'high': 200, 'unit': 'mmol/L'},
        },
        'unit': 'mmol/L',
        'tat_hours': 4,
        'price': 25.00,
    },
    {
        'code': 'FENA',
        'loinc_code': '33558-8',
        'name': 'Fractional Excretion of Sodium',
        'short_name': 'FENa',
        'category': 'urinalysis',
        'description': 'Calculated FENa - prerenal vs intrinsic AKI',
        'specimen_type': 'Serum + Urine',
        'container_type': 'Red Top + Sterile Cup',
        'volume_required': '2 mL serum + 5 mL urine',
        'reference_ranges': {
            'prerenal': {'low': 0, 'high': 1, 'unit': '%'},
            'intrinsic_renal': {'low': 2, 'high': 100, 'unit': '%'},
        },
        'unit': '%',
        'tat_hours': 4,
        'price': 0.00,  # Calculated
        'special_instructions': 'Calculated: (UNa x PCr) / (PNa x UCr) x 100',
    },
    {
        'code': 'URINE_DRUG_SCREEN',
        'loinc_code': '19295-5',
        'name': 'Urine Drug Screen',
        'short_name': 'UDS',
        'category': 'toxicology',
        'description': 'Qualitative drug screen (amphetamines, barbiturates, benzodiazepines, cocaine, opiates, PCP, THC)',
        'specimen_type': 'Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '30 mL',
        'reference_ranges': {
            'all_drugs': {'value': 'Negative', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 4,
        'price': 45.00,
        'special_instructions': 'Chain of custody required for legal/employment testing',
    },
    {
        'code': 'PREGNANCY_URINE',
        'loinc_code': '2106-3',
        'name': 'Pregnancy Test, Urine (hCG)',
        'short_name': 'Urine hCG',
        'category': 'urinalysis',
        'description': 'Qualitative pregnancy test',
        'specimen_type': 'Urine',
        'container_type': 'Sterile Cup',
        'volume_required': '5 mL',
        'reference_ranges': {
            'negative': {'value': 'Negative', 'unit': 'text'},
            'positive': {'value': 'Positive', 'unit': 'text'},
        },
        'unit': 'text',
        'tat_hours': 1,
        'price': 20.00,
        'special_instructions': 'First morning specimen preferred for early pregnancy',
    },
]
