# Generated by Django 4.2.10 on 2025-12-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffSiteAccessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offsite_mode', models.CharField(choices=[('readonly', 'Read-Only Mode'), ('deny', 'Deny Access'), ('allow', 'Allow Full Access')], default='readonly', help_text='How to handle off-site access attempts', max_length=20)),
                ('readonly_message', models.TextField(default='You are accessing from outside the hospital network. Write operations are disabled for security.', help_text='Message shown to users in read-only mode')),
                ('deny_message', models.TextField(default='Access denied. Please connect from within the hospital network.', help_text='Message shown when access is denied')),
                ('allow_admin_override', models.BooleanField(default=True, help_text='Allow admin users to bypass off-site restrictions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Off-Site Access Settings',
                'verbose_name_plural': 'Off-Site Access Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this network (e.g., 'Main Hospital LAN')", max_length=100)),
                ('cidr', models.CharField(help_text="Network in CIDR notation (e.g., '192.168.1.0/24' or '10.0.0.0/8')", max_length=43)),
                ('description', models.TextField(blank=True, help_text='Additional details about this network')),
                ('is_active', models.BooleanField(default=True, help_text='Only active networks are checked for on-site access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Network',
                'verbose_name_plural': 'Site Networks',
                'ordering': ['name'],
            },
        ),
    ]
