# Generated by Django 4.2.10 on 2025-12-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_site_network_offsite_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsiteaccesssettings',
            name='treat_localhost_as_offsite',
            field=models.BooleanField(default=False, help_text='For testing: treat localhost (127.0.0.1) as off-site instead of on-site'),
        ),
    ]
