# Generated by Django 4.2.10 on 2025-12-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_localhost_testing_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityFluidBalanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_daily_intake_target', models.PositiveIntegerField(default=1500, help_text='Minimum daily intake target in ml. Alert when patient intake is below this.')),
                ('max_daily_output_threshold', models.PositiveIntegerField(default=3000, help_text='Maximum daily output threshold in ml. Alert when output exceeds this.')),
                ('negative_balance_alert_threshold', models.IntegerField(default=-500, help_text='Alert when daily balance (intake - output) falls below this value in ml.')),
                ('positive_balance_alert_threshold', models.PositiveIntegerField(default=2000, help_text='Alert when daily balance exceeds this value in ml (indicates fluid retention).')),
                ('enable_intake_alerts', models.BooleanField(default=True, help_text='Enable alerts for low daily intake.')),
                ('enable_output_alerts', models.BooleanField(default=True, help_text='Enable alerts for high daily output.')),
                ('enable_balance_alerts', models.BooleanField(default=True, help_text='Enable alerts for abnormal fluid balance.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility Fluid Balance Settings',
                'verbose_name_plural': 'Facility Fluid Balance Settings',
            },
        ),
    ]
