# Generated by Django 4.2.10 on 2025-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facility_fluid_balance_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique idempotency key (typically hashed)', max_length=128, unique=True)),
                ('operation_type', models.CharField(help_text="Type of operation (e.g., 'payment', 'admission', 'discharge')", max_length=64)),
                ('request_path', models.CharField(blank=True, help_text='API endpoint path', max_length=255)),
                ('request_hash', models.CharField(blank=True, help_text='Hash of request body for validation', max_length=64)),
                ('response_status', models.IntegerField(help_text='HTTP status code of the response')),
                ('response_body', models.JSONField(help_text='Serialized response data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this record can be cleaned up')),
            ],
            options={
                'verbose_name': 'Idempotency Record',
                'verbose_name_plural': 'Idempotency Records',
                'indexes': [models.Index(fields=['key', 'operation_type'], name='core_idempo_key_cf876a_idx'), models.Index(fields=['expires_at'], name='core_idempo_expires_9f124d_idx')],
            },
        ),
    ]
