# Generated by Django 4.2.10 on 2025-12-17 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_add_idempotency_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Unique facility code (e.g., 'MAIN', 'BRANCH-A')", max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('diagnostic_center', 'Diagnostic Center'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('rehabilitation', 'Rehabilitation Center'), ('urgent_care', 'Urgent Care')], default='hospital', max_length=20)),
                ('address', models.TextField(help_text='Full street address')),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, help_text='State/Region/Province', max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude for mapping', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude for mapping', max_digits=9, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='Africa/Accra', help_text='Timezone for scheduling and timestamps', max_length=50)),
                ('currency', models.CharField(default='GHS', help_text='ISO 4217 currency code', max_length=3)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('license_number', models.CharField(blank=True, help_text='Healthcare facility license number', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_headquarters', models.BooleanField(default=False, help_text='Whether this is the main/headquarters facility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_facilities', to=settings.AUTH_USER_MODEL)),
                ('parent_facility', models.ForeignKey(blank=True, help_text='Parent facility for branch locations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_facilities', to='core.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Department code (unique within facility)', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('department_type', models.CharField(choices=[('clinical', 'Clinical'), ('diagnostic', 'Diagnostic'), ('surgical', 'Surgical'), ('emergency', 'Emergency'), ('support', 'Support Services'), ('administrative', 'Administrative'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('nursing', 'Nursing')], default='clinical', max_length=20)),
                ('phone_extension', models.CharField(blank=True, help_text='Internal phone extension', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, help_text="Physical location within facility (e.g., 'Building A, Floor 2')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_clinical', models.BooleanField(default=True, help_text='Whether this department provides clinical services')),
                ('accepts_referrals', models.BooleanField(default=True, help_text='Whether this department accepts patient referrals')),
                ('operating_hours_start', models.TimeField(blank=True, help_text='Department opening time (leave blank to use facility default)', null=True)),
                ('operating_hours_end', models.TimeField(blank=True, help_text='Department closing time (leave blank to use facility default)', null=True)),
                ('operates_24_hours', models.BooleanField(default=False, help_text='Whether department operates 24/7')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.facility')),
                ('head', models.ForeignKey(blank=True, help_text='Department head/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['facility__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['code'], name='core_facili_code_d15fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type', 'is_active'], name='core_facili_facilit_e99055_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['parent_facility'], name='core_facili_parent__7be52a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['facility', 'code'], name='core_depart_facilit_33713b_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_type', 'is_active'], name='core_depart_departm_fb9b15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('facility', 'code')},
        ),
    ]
