# Generated by Django 4.2.10 on 2025-12-22 20:35

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakGlassEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('clinical', 'Clinical'), ('lab', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('demographics', 'Demographics')], default='clinical', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('patient', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='break_glass_events', to='users.patientprofile')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='break_glass_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='breakglassevent',
            index=models.Index(fields=['user', 'patient', 'scope'], name='core_break_user_9c0c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='breakglassevent',
            index=models.Index(fields=['patient', 'scope'], name='core_break_patie_06d6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='breakglassevent',
            index=models.Index(fields=['expires_at'], name='core_break_expi_0f7c0f_idx'),
        ),
    ]
