# Generated by Django 4.2.10 on 2025-12-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_break_glass_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='breakglassevent',
            new_name='core_breakg_user_id_194f83_idx',
            old_name='core_break_user_9c0c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='breakglassevent',
            new_name='core_breakg_patient_6ee83f_idx',
            old_name='core_break_patie_06d6ee_idx',
        ),
        migrations.RenameIndex(
            model_name='breakglassevent',
            new_name='core_breakg_expires_8b663e_idx',
            old_name='core_break_expi_0f7c0f_idx',
        ),
    ]
