# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('running', 'Running'),
                    ('ready', 'Ready'),
                    ('failed', 'Failed'),
                    ('suspended', 'Suspended'),
                ],
                default='ready',
                help_text='Provisioning status for this facility',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='facility',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, help_text='When this facility was provisioned', null=True),
        ),
    ]
