# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_encounter_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    Encounter = apps.get_model('encounters', 'Encounter')

    fallback = _get_fallback_facility(Facility)
    encounters = list(
        Encounter.objects.filter(facility__isnull=True).select_related(
            'patient__facility',
            'created_by__primary_facility',
            'created_by__staff_profile__primary_facility'
        )
    )

    for encounter in encounters:
        facility = None
        if encounter.patient_id and getattr(encounter.patient, 'facility_id', None):
            facility = encounter.patient.facility
        else:
            created_by = encounter.created_by
            if created_by and getattr(created_by, 'primary_facility_id', None):
                facility = created_by.primary_facility
            else:
                staff = getattr(created_by, 'staff_profile', None) if created_by else None
                if staff and getattr(staff, 'primary_facility_id', None):
                    facility = staff.primary_facility
        if not facility and fallback:
            facility = fallback
        if facility:
            encounter.facility_id = facility.id

    if encounters:
        Encounter.objects.bulk_update(encounters, ['facility'])

    if Encounter.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "Encounter facility backfill incomplete. "
            "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='encounters',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_encounter_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='encounter',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='encounters',
                to='core.facility',
            ),
        ),
    ]
