# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('encounters', '0002_add_facility_scoping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='facility',
            field=models.ForeignKey(help_text='Facility where this encounter occurred', on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='core.facility'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['facility', 'status'], name='wards_encou_facilit_210532_idx'),
        ),
    ]
