# Generated by Django 4.2.10 on 2026-01-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment'),
        ('encounters', '0003_alter_encounter_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='appointments.appointment'),
        ),
    ]
