# Generated by Django 4.2.10 on 2026-01-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_encounter_appointment'),
        ('organization', '0007_clinic_clinic_unique_clinic_code_per_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='organization.clinic'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['clinic', 'status'], name='wards_encou_clinic__9c53a1_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['appointment', 'status'], name='wards_encou_appoint_16093e_idx'),
        ),
    ]
