# Generated by Django 4.2.10 on 2026-01-13 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('users', '0017_alter_patientprofile_facility_alter_user_facilities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0010_appointment_clinic_appointment_created_by_and_more'),
        ('organization', '0007_clinic_clinic_unique_clinic_code_per_facility'),
        ('encounters', '0005_encounter_clinic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_status', models.CharField(choices=[('checked_in', 'Checked In'), ('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'With Doctor'), ('on_hold', 'On Hold'), ('ready_checkout', 'Ready for Checkout'), ('checked_out', 'Checked Out'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='checked_in', max_length=20)),
                ('queue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_ended_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriageQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('routine', 'Routine')], default='routine', max_length=20)),
                ('chief_complaint', models.TextField(blank=True)),
                ('triage_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Triage'), ('triaged', 'Triaged'), ('assigned', 'Assigned to Clinic'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': [models.Case(models.When(priority='emergency', then=0), models.When(priority='urgent', then=1), models.When(priority='routine', then=2), default=3), 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('appointment',), name='unique_encounter_per_appointment'),
        ),
        migrations.AddField(
            model_name='triagequeue',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_entry', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='triagequeue',
            name='assigned_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.clinic'),
        ),
        migrations.AddField(
            model_name='triagequeue',
            name='assigned_practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.practitionerprofile'),
        ),
        migrations.AddField(
            model_name='triagequeue',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_queue', to='core.facility'),
        ),
        migrations.AddField(
            model_name='triagequeue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_entries', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='triagequeue',
            name='triaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outpatientvisit',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='outpatientvisit',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outpatient_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outpatientvisit',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outpatient_checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outpatientvisit',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outpatient_visits', to='organization.clinic'),
        ),
        migrations.AddField(
            model_name='outpatientvisit',
            name='encounter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_visit', to='encounters.encounter'),
        ),
        migrations.AddIndex(
            model_name='triagequeue',
            index=models.Index(fields=['facility', 'status'], name='encounters__facilit_dce56c_idx'),
        ),
        migrations.AddIndex(
            model_name='triagequeue',
            index=models.Index(fields=['patient', 'created_at'], name='encounters__patient_893987_idx'),
        ),
        migrations.AddIndex(
            model_name='triagequeue',
            index=models.Index(fields=['priority', 'created_at'], name='encounters__priorit_fec316_idx'),
        ),
        migrations.AddIndex(
            model_name='outpatientvisit',
            index=models.Index(fields=['clinic', 'visit_status', 'checked_in_at'], name='encounters__clinic__c1e42f_idx'),
        ),
        migrations.AddIndex(
            model_name='outpatientvisit',
            index=models.Index(fields=['queue_number', 'checked_in_at'], name='encounters__queue_n_f4fc81_idx'),
        ),
    ]
