# Generated by Django 4.2.10 on 2026-01-18 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0009_add_primary_team_and_care_teams'),
        ('encounters', '0007_encounter_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterCareTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('consulting', 'Consulting'), ('co_managing', 'Co-Managing'), ('procedure', 'Procedure Team')], default='consulting', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('active', 'Active'), ('completed', 'Completed'), ('declined', 'Declined')], default='requested', max_length=20)),
                ('consult_reason', models.TextField(blank=True, null=True)),
                ('consult_requested_at', models.DateTimeField(blank=True, null=True)),
                ('consult_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('consult_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encounter Care Team',
                'verbose_name_plural': 'Encounter Care Teams',
                'db_table': 'encounters_encountercareTeam',
            },
        ),
        migrations.RenameIndex(
            model_name='encounter',
            new_name='wards_encou_departm_221755_idx',
            old_name='encounters_departm_66288b_idx',
        ),
        migrations.AddField(
            model_name='encounter',
            name='primary_team',
            field=models.ForeignKey(blank=True, help_text='Primary clinical team responsible for this encounter', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_encounters', to='organization.clinicalunit'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['primary_team', 'status'], name='wards_encou_primary_7a8c84_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'primary_team', 'status'], name='wards_encou_patient_287fef_idx'),
        ),
        migrations.AddField(
            model_name='encountercareteam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_encounter_care_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encountercareteam',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team_assignments', to='encounters.encounter'),
        ),
        migrations.AddField(
            model_name='encountercareteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_consulting_assignments', to='organization.clinicalunit'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='consulting_teams',
            field=models.ManyToManyField(blank=True, related_name='consulting_encounters', through='encounters.EncounterCareTeam', to='organization.clinicalunit'),
        ),
        migrations.AddIndex(
            model_name='encountercareteam',
            index=models.Index(fields=['encounter', 'status', 'is_active'], name='encounters__encount_760857_idx'),
        ),
        migrations.AddIndex(
            model_name='encountercareteam',
            index=models.Index(fields=['team', 'status', 'is_active'], name='encounters__team_id_ac6b03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='encountercareteam',
            unique_together={('encounter', 'team')},
        ),
    ]
