# Generated by Django 4.2.10 on 2026-01-18 19:37

from django.db import migrations


def migrate_care_teams_forward(apps, schema_editor):
    """
    Copy primary_team and CareTeamAssignment data from Admission to Encounter.
    """
    Admission = apps.get_model('wards', 'Admission')
    Encounter = apps.get_model('encounters', 'Encounter')
    CareTeamAssignment = apps.get_model('wards', 'CareTeamAssignment')
    EncounterCareTeam = apps.get_model('encounters', 'EncounterCareTeam')

    # Copy primary_team from Admission to linked Encounter
    # Use a subquery approach to avoid N+1 queries
    for admission in Admission.objects.filter(primary_team__isnull=False).select_related('encounter'):
        encounter = getattr(admission, 'encounter', None)
        if encounter:
            encounter.primary_team_id = admission.primary_team_id
            encounter.save(update_fields=['primary_team'])

    # Copy CareTeamAssignment to EncounterCareTeam
    for assignment in CareTeamAssignment.objects.select_related('admission'):
        admission = assignment.admission
        encounter = getattr(admission, 'encounter', None)
        if encounter:
            # Check if this team assignment already exists
            if not EncounterCareTeam.objects.filter(
                encounter=encounter,
                team_id=assignment.team_id
            ).exists():
                EncounterCareTeam.objects.create(
                    encounter=encounter,
                    team_id=assignment.team_id,
                    role=assignment.role,
                    status=assignment.status,
                    consult_reason=assignment.consult_reason,
                    consult_requested_at=assignment.consult_requested_at,
                    consult_accepted_at=assignment.consult_accepted_at,
                    consult_completed_at=assignment.consult_completed_at,
                    is_active=assignment.is_active,
                    created_by_id=assignment.created_by_id,
                )


def migrate_care_teams_backward(apps, schema_editor):
    """
    Reverse migration: copy data back from Encounter to Admission.
    """
    Admission = apps.get_model('wards', 'Admission')
    Encounter = apps.get_model('encounters', 'Encounter')
    CareTeamAssignment = apps.get_model('wards', 'CareTeamAssignment')
    EncounterCareTeam = apps.get_model('encounters', 'EncounterCareTeam')

    # Copy primary_team from Encounter back to Admission
    for encounter in Encounter.objects.filter(
        primary_team__isnull=False,
        admission__isnull=False
    ).select_related('admission'):
        if encounter.admission:
            encounter.admission.primary_team_id = encounter.primary_team_id
            encounter.admission.save(update_fields=['primary_team'])

    # Copy EncounterCareTeam back to CareTeamAssignment
    for ect in EncounterCareTeam.objects.select_related('encounter__admission'):
        admission = getattr(ect.encounter, 'admission', None)
        if admission:
            if not CareTeamAssignment.objects.filter(
                admission=admission,
                team_id=ect.team_id
            ).exists():
                CareTeamAssignment.objects.create(
                    admission=admission,
                    team_id=ect.team_id,
                    role=ect.role,
                    status=ect.status,
                    consult_reason=ect.consult_reason,
                    consult_requested_at=ect.consult_requested_at,
                    consult_accepted_at=ect.consult_accepted_at,
                    consult_completed_at=ect.consult_completed_at,
                    is_active=ect.is_active,
                    created_by_id=ect.created_by_id,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0008_add_primary_team_and_care_teams'),
        ('wards', '0018_rename_wards_admission_facility_status_idx_wards_admis_facilit_e9d05e_idx_and_more'),  # Ensure wards migrations are applied
    ]

    operations = [
        migrations.RunPython(
            migrate_care_teams_forward,
            migrate_care_teams_backward,
        ),
    ]
