# Generated by Django 4.2.10 on 2026-01-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0010_add_admitted_by_team'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='encounter',
            new_name='wards_encou_admitte_7702a2_idx',
            old_name='wards_encou_admitted_2d3a66_idx',
        ),
    ]
