/* oxlint-disable react-doctor/prefer-useReducer -- These components keep independent UI states; a reducer would add dispatch indirection without a shared transition invariant. */
/* oxlint-disable react-doctor/no-render-in-render -- Step rendering is a pure switch over the active wizard step; a broader extraction should preserve the clinical handoff flow in its own pass. */
/* oxlint-disable react-doctor/rendering-hydration-mismatch-time -- This Vite SPA page uses useSyncExternalStore for a stable displayed date snapshot; there is no server-rendered clock to hydrate. */
import ArrowRight from 'lucide-react/dist/esm/icons/arrow-right.js';
import ArrowLeft from 'lucide-react/dist/esm/icons/arrow-left.js';
import CheckCircle from 'lucide-react/dist/esm/icons/circle-check-big.js';
import Circle from 'lucide-react/dist/esm/icons/circle.js';
import Loader2 from 'lucide-react/dist/esm/icons/loader-circle.js';
import User from 'lucide-react/dist/esm/icons/user.js';
import Heart from 'lucide-react/dist/esm/icons/heart.js';
import ClipboardList from 'lucide-react/dist/esm/icons/clipboard-list.js';
import FileCheck from 'lucide-react/dist/esm/icons/file-check.js';
import Calendar from 'lucide-react/dist/esm/icons/calendar.js';
import { useCallback, useEffect, useReducer, useSyncExternalStore } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';

import { toast } from 'sonner';
import format from 'date-fns/format';
import { cn, normalizeApiResults } from '@/lib/utils';

import {
  usePatientMonitoring,
  useCreateShiftHandoff,
  usePatientDetail,
  useNursingTasks,
  useNursingAlerts,
  useMedicationsDueNow
} from '@/features/nursing/hooks';
import { useWardStaff } from '@/features/wards/hooks/useWardQueries';
import { useStaff } from '@/features/staff/hooks';
import { isRustV2ApiMode } from '@/lib/api/v2/runtime';
import { useAuth } from '@/lib/auth';
import { Layout } from '@/components/layout/layout';
import { PageHeader } from '@/shared/components/page/PageHeader';
import { PageShell } from '@/shared/components/page/PageShell';
import { usePageMeta } from '@/shared/hooks/usePageMeta';

// Config and utilities
import { getShiftTypeFromTime, getShiftOptions } from '@/config/shiftConfig';
import { generateAllHandoffSummaries } from './shift-handoff/generateHandoffSummary';

// Step components
import { PatientSelectStep } from './shift-handoff/PatientSelectStep';
import { ClinicalInfoStep } from './shift-handoff/ClinicalInfoStep';
import { TasksEventsStep } from './shift-handoff/TasksEventsStep';
import { ReviewStep } from './shift-handoff/ReviewStep';

const STEPS = [
  { id: 1, key: 'patient', title: 'Select Patient', icon: User },
  { id: 2, key: 'clinical', title: 'Clinical Info', icon: Heart },
  { id: 3, key: 'tasks', title: 'Tasks & Events', icon: ClipboardList },
  { id: 4, key: 'review', title: 'Review & Submit', icon: FileCheck },
];

const subscribeToStableDateSnapshot = () => () => {};
const getServerDateLabel = () => '';
const getTodayDateLabel = () => format(new Date(), 'MMMM d, yyyy');

function createInitialHandoffFormData() {
  return {
    shift_type: getShiftTypeFromTime(), // Auto-detect from current time
    to_nurse: '',
    patient_condition: '',
    ongoing_issues: '',
    pending_tasks: '',
    medication_changes: '',
    key_events: '',
    care_plan_updates: '',
    family_updates: '',
  };
}

function createInitialHandoffState() {
  return {
    currentStep: 1,
    selectedPatient: null,
    searchTerm: '',
    isAutoGenerated: false,
    formData: createInitialHandoffFormData(),
  };
}

function shiftHandoffReducer(state, action) {
  switch (action.type) {
    case 'select-patient':
      return {
        ...state,
        selectedPatient: action.patient,
        currentStep: 2,
        isAutoGenerated: false,
      };
    case 'set-search':
      return {
        ...state,
        searchTerm: action.searchTerm,
      };
    case 'set-field':
      return {
        ...state,
        formData: {
          ...state.formData,
          [action.field]: action.value,
        },
      };
    case 'hydrate-summaries':
      return {
        ...state,
        isAutoGenerated: true,
        formData: {
          ...state.formData,
          patient_condition: state.formData.patient_condition || action.summaries.patient_condition,
          pending_tasks: state.formData.pending_tasks || action.summaries.pending_tasks,
          ongoing_issues: state.formData.ongoing_issues || action.summaries.ongoing_issues,
          medication_changes: state.formData.medication_changes || action.summaries.medication_changes,
        },
      };
    case 'go-to-step':
      return {
        ...state,
        currentStep: action.stepId,
      };
    case 'next-step':
      return {
        ...state,
        currentStep: Math.min(state.currentStep + 1, 4),
      };
    case 'previous-step':
      return {
        ...state,
        currentStep: Math.max(state.currentStep - 1, 1),
      };
    default:
      return state;
  }
}

function getCurrentUserDisplayName(user) {
  return [user?.firstName, user?.lastName].filter(Boolean).join(' ').trim()
    || user?.email
    || 'Current User';
}

export function getHandoffNurseOptions({ rustV2Mode, wardStaff = [], staff = [], currentUser = null }) {
  const assignedWardStaff = normalizeApiResults(wardStaff);
  if (!rustV2Mode || assignedWardStaff.length > 0) {
    return {
      nurses: assignedWardStaff,
      usesDirectoryFallback: false,
    };
  }

  const directoryNurses = normalizeApiResults(staff).reduce((nurses, member) => {
    if (member.is_active === false) {
      return nurses;
    }

    const nurse = {
      id: member.user_id || member.id,
      full_name: member.full_name || member.name || member.display_name || member.email,
      role_name: member.user_type ? member.user_type.replaceAll('_', ' ') : member.role_name || 'Staff',
    };
    if (nurse.id && nurse.full_name) {
      nurses.push(nurse);
    }
    return nurses;
  }, []);

  const currentUserFallback = currentUser?.id
    ? [{
      id: currentUser.id,
      full_name: getCurrentUserDisplayName(currentUser),
      role_name: currentUser.role || currentUser.user_type || 'Staff',
    }]
    : [];

  const fallbackNurses = directoryNurses.length > 0 ? directoryNurses : currentUserFallback;

  return {
    nurses: fallbackNurses,
    usesDirectoryFallback: fallbackNurses.length > 0,
  };
}

export default function ShiftHandoffPage() {
  const navigate = useNavigate();
  const rustV2Mode = isRustV2ApiMode();
  const { user } = useAuth();
  const [state, dispatch] = useReducer(shiftHandoffReducer, undefined, createInitialHandoffState);
  const todayLabel = useSyncExternalStore(
    subscribeToStableDateSnapshot,
    getTodayDateLabel,
    getServerDateLabel
  );
  const {
    currentStep,
    selectedPatient,
    searchTerm,
    isAutoGenerated,
    formData,
  } = state;

  // Fetch patients from monitoring dashboard
  const { data: patientsData, isLoading: patientsLoading } = usePatientMonitoring(null, 1, 100);

  // Get ward ID from selected patient
  const wardId = selectedPatient?.ward_id;

  // Fetch nursing staff assigned to the selected patient's ward
  const { data: wardStaffData, isLoading: wardNursesLoading } = useWardStaff(wardId, 'nursing');
  const { data: staffData, isLoading: staffLoading } = useStaff(
    { page_size: 100, is_active: true },
    { enabled: rustV2Mode && !!selectedPatient }
  );

  // Create handoff mutation
  const createMutation = useCreateShiftHandoff();

  // Fetch clinical data for selected patient (for prepopulation)
  const patientId = selectedPatient?.patient_id;
  const { data: patientDetail } = usePatientDetail(patientId);
  const { data: tasksData } = useNursingTasks(patientId ? { patient: patientId } : {});
  const { data: alertsData } = useNursingAlerts(patientId ? { patient: patientId } : {});
  const { data: medicationsDue } = useMedicationsDueNow();

  // Get patients list
  const patients = normalizeApiResults(patientsData);

  // Get nurses assigned to the ward. Rust V2 does not expose ward staff assignments yet,
  // so the handoff workflow falls back to the active staff directory.
  const { nurses, usesDirectoryFallback } = getHandoffNurseOptions({
    rustV2Mode,
    wardStaff: wardStaffData,
    staff: staffData,
    currentUser: user,
  });
  const nursesLoading = wardNursesLoading || (rustV2Mode && staffLoading);

  // Prepopulate form when patient data is loaded
  useEffect(() => {
    if (selectedPatient && patientDetail) {
      // Extract vitals from patient detail
      const vitals = patientDetail?.latest_vitals || patientDetail?.vitals?.[0] || null;

      // Filter tasks and alerts for this patient
      const patientTasks = Array.isArray(tasksData)
        ? tasksData.filter(t => t.patient === patientId || t.patient_id === patientId)
        : [];
      const patientAlerts = Array.isArray(alertsData)
        ? alertsData.filter(a => a.patient === patientId || a.patient_id === patientId)
        : [];
      const patientMeds = Array.isArray(medicationsDue)
        ? medicationsDue.filter(m => m.patient === patientId || m.patient_id === patientId)
        : [];

      // Generate prepopulated summaries
      const summaries = generateAllHandoffSummaries({
        patient: selectedPatient,
        vitals,
        tasks: patientTasks,
        alerts: patientAlerts,
        medicationsDue: patientMeds,
        medicationEvents: patientDetail?.medication_events || [],
      });

      dispatch({ type: 'hydrate-summaries', summaries });
    }
  }, [selectedPatient, patientDetail, tasksData, alertsData, medicationsDue, patientId]);

  // Handle patient selection - auto advance to next step
  const handleSelectPatient = useCallback((patient) => {
    dispatch({ type: 'select-patient', patient });
  }, []);

  // Handle form field changes
  const handleFieldChange = useCallback((field, value) => {
    dispatch({ type: 'set-field', field, value });
  }, []);

  const handleSearchChange = useCallback((nextSearchTerm) => {
    dispatch({ type: 'set-search', searchTerm: nextSearchTerm });
  }, []);

  // Check if step is complete
  const isStepComplete = useCallback((stepId) => {
    switch (stepId) {
      case 1:
        return !!selectedPatient;
      case 2:
        return !!formData.patient_condition && !!formData.to_nurse;
      case 3:
        return !!formData.pending_tasks;
      case 4:
        return true;
      default:
        return false;
    }
  }, [selectedPatient, formData]);

  // Navigate to step (clickable steps) - all steps accessible
  const goToStep = useCallback((stepId) => {
    dispatch({ type: 'go-to-step', stepId });
  }, []);

  // Navigate to next step
  const handleNext = useCallback(() => {
    if (currentStep === 1 && !selectedPatient) {
      toast.error('Please select a patient');
      return;
    }
    if (currentStep === 2 && !formData.patient_condition) {
      toast.error('Please enter the patient condition');
      return;
    }
    if (currentStep === 2 && !formData.to_nurse) {
      toast.error('Please select the receiving nurse');
      return;
    }
    if (currentStep === 3 && !formData.pending_tasks) {
      toast.error('Please enter pending tasks');
      return;
    }

    dispatch({ type: 'next-step' });
  }, [currentStep, selectedPatient, formData]);

  // Navigate to previous step
  const handleBack = useCallback(() => {
    dispatch({ type: 'previous-step' });
  }, []);

  // Submit the handoff
  const handleSubmit = async () => {
    if (!selectedPatient) {
      toast.error('Please select a patient');
      return;
    }
    if (!formData.patient_condition) {
      toast.error('Please enter the patient condition');
      return;
    }
    if (!formData.to_nurse) {
      toast.error('Please select the receiving nurse');
      return;
    }

    try {
      await createMutation.mutateAsync({
        patient: selectedPatient.patient_id,
        ward_id: selectedPatient.ward_id,
        shift_date: format(new Date(), 'yyyy-MM-dd'),
        shift_type: formData.shift_type,
        to_nurse: formData.to_nurse,
        patient_condition: formData.patient_condition,
        ongoing_issues: formData.ongoing_issues || '',
        pending_tasks: formData.pending_tasks || '',
        medication_changes: formData.medication_changes || '',
        key_events: formData.key_events || '',
        care_plan_updates: formData.care_plan_updates || '',
        family_updates: formData.family_updates || '',
      });

      toast.success('Shift handoff completed successfully');
      navigate('/dashboards/nurse');
    } catch (error) {
      console.error('Error creating handoff:', error);
      toast.error('Failed to create shift handoff. Please try again.');
    }
  };

  // Render step content
  const renderStepContent = () => {
    switch (currentStep) {
      case 1:
        return (
          <PatientSelectStep
            patients={patients}
            isLoading={patientsLoading}
            selectedPatient={selectedPatient}
            onSelectPatient={handleSelectPatient}
            searchTerm={searchTerm}
            onSearchChange={handleSearchChange}
          />
        );
      case 2:
        return (
          <ClinicalInfoStep
            formData={formData}
            onChange={handleFieldChange}
            nurses={nurses}
            nursesLoading={nursesLoading}
            selectedPatient={selectedPatient}
            isAutoGenerated={isAutoGenerated}
            nurseScopeNotice={usesDirectoryFallback
              ? 'Ward-specific nurse assignments are not available for this deployment yet. Choose from active staff.'
              : null}
          />
        );
      case 3:
        return (
          <TasksEventsStep
            formData={formData}
            onChange={handleFieldChange}
            selectedPatient={selectedPatient}
            isAutoGenerated={isAutoGenerated}
          />
        );
      case 4:
        return (
          <ReviewStep
            formData={formData}
            selectedPatient={selectedPatient}
            nurses={nurses}
          />
        );
      default:
        return null;
    }
  };

  const currentStepDef = STEPS.find(s => s.id === currentStep);

  const pageMeta = usePageMeta({
    title: 'Shift Handoff | HMS',
    breadcrumbs: [
      { label: 'Nursing', href: '/dashboards/nurse' },
      { label: 'Shift Handoff' },
    ],
  });

  return (
    <Layout>
      <PageShell>
        {pageMeta}
        <PageHeader
          title="Shift Handoff"
          description="Document and transfer patient care to the next shift"
          actions={(
            <Badge variant="outline" className="font-mono text-sm px-4 py-2">
              <Calendar className="mr-2 size-4" />
              {todayLabel}
            </Badge>
          )}
          size="lg"
        />

        <div className="container mx-auto px-4 py-6 max-w-4xl">
          {/* Step Progress - Clickable */}
          <div className="flex items-center justify-center gap-2 mb-8">
            {STEPS.map((step, index) => {
              const Icon = step.icon;
              const isActive = currentStep === step.id;
              const isCompleted = isStepComplete(step.id);

              return (
                <div key={step.id} className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => goToStep(step.id)}
                    className={cn(
                      "flex items-center gap-2 px-4 py-2 rounded-lg transition-all cursor-pointer",
                      isActive && "bg-amber-500 text-white",
                      isCompleted && !isActive && "bg-emerald-500/10 text-emerald-600 hover:bg-emerald-500/20",
                      !isActive && !isCompleted && "bg-muted text-muted-foreground hover:bg-muted/80"
                    )}
                  >
                    {isCompleted && !isActive ? (
                      <CheckCircle className="size-4" />
                    ) : (
                      <Icon className="size-4" />
                    )}
                    <span className="font-mono text-xs uppercase tracking-wide hidden sm:inline">
                      {step.title}
                    </span>
                  </button>

                  {index < STEPS.length - 1 && (
                    <ArrowRight className={cn(
                      "size-4",
                      isCompleted ? "text-emerald-500" : "text-muted-foreground/30"
                    )} />
                  )}
                </div>
              );
            })}
          </div>

          {/* Step Content */}
          <Card className="border-border">
            <CardContent className="p-6">
              {/* Step Header */}
              <div className="mb-6 pb-4 border-b border-border">
                <div className="flex items-center gap-3">
                  {currentStepDef && (
                    <div className="p-2 rounded-lg bg-amber-500/10">
                      <currentStepDef.icon className="size-5 text-amber-600" />
                    </div>
                  )}
                  <div>
                    <h2 className="font-display text-xl font-semibold">
                      {currentStepDef?.title}
                    </h2>
                    <p className="text-sm text-muted-foreground">
                      Step {currentStep} of {STEPS.length}
                    </p>
                  </div>
                </div>
              </div>

              {/* Step Content */}
              <div className="min-h-[400px]">
                {renderStepContent()}
              </div>
            </CardContent>
          </Card>

          {/* Navigation */}
          <div className="flex items-center justify-between mt-6">
            <Button
              variant="outline"
              onClick={currentStep === 1 ? () => navigate('/dashboards/nurse') : handleBack}
              className="font-mono"
            >
              <ArrowLeft className="mr-2 size-4" />
              {currentStep === 1 ? 'Cancel' : 'Back'}
            </Button>

            {currentStep < 4 ? (
              <Button
                onClick={handleNext}
                className="font-mono bg-amber-500 hover:bg-amber-600 text-white"
              >
                Continue
                <ArrowRight className="ml-2 size-4" />
              </Button>
            ) : (
              <Button
                onClick={handleSubmit}
                disabled={createMutation.isPending || !formData.to_nurse}
                className="font-mono bg-emerald-600 hover:bg-emerald-700 text-white"
              >
                {createMutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 size-4 animate-spin" />
                    Submitting…
                  </>
                ) : (
                  <>
                    <CheckCircle className="mr-2 size-4" />
                    Complete Handoff
                  </>
                )}
              </Button>
            )}
          </div>
        </div>
      </PageShell>
  </Layout>
  );
}
