# Generated by Django 4.2.10 on 2026-02-22 21:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_alter_patientprofile_medical_record_number_and_more'),
        ('core', '0010_seed_core_singletons'),
        ('encounters', '0011_rename_wards_encou_admitted_2d3a66_idx_wards_encou_admitte_7702a2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('summary', 'Summary'), ('answer', 'Answer'), ('note_draft', 'Note Draft'), ('note_lint', 'Note Lint'), ('lab_interpretation', 'Lab Interpretation'), ('omni_parse', 'Omni Parse'), ('omni_preview', 'Omni Execute Preview'), ('scribe_section_draft', 'Scribe Section Draft'), ('other', 'Other')], max_length=40)),
                ('payload_json', models.JSONField(default=dict)),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('requires_human_review', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('note_entry_id', models.UUIDField(blank=True, null=True)),
                ('lab_result_id', models.UUIDField(blank=True, null=True)),
                ('timeline_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_ai_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('chronicle_copilot', 'Chronicle Copilot'), ('note_draft', 'Note Draft'), ('note_lint', 'Note Lint'), ('lab_interpretation', 'Lab Interpretation'), ('omni_nl', 'Omni NL'), ('scribe', 'Ambient Scribe'), ('generic', 'Generic AI')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('request_context_hash', models.CharField(db_index=True, max_length=64)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='encounters.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_sessions', to='core.facility')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='users.patientprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=20)),
                ('content_encrypted', models.TextField(blank=True)),
                ('content_redacted', models.TextField(blank=True)),
                ('model_role', models.CharField(blank=True, choices=[('reasoner_large', 'reasoner_large'), ('writer_medium', 'writer_medium'), ('validator_small', 'validator_small'), ('intent_small', 'intent_small'), ('embedding_model', 'embedding_model'), ('reranker_model', 'reranker_model'), ('asr_medical', 'asr_medical'), ('diarizer', 'diarizer')], max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aisession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumb', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='ai.aiartifact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiartifact',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ai.aisession'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['facility', 'feature', '-created_at'], name='ai_ses_fac_feat_created'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='ai_ses_fac_status_created'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['user', '-created_at'], name='ai_session_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_msg_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['provider', 'model_name'], name='ai_msg_provider_model_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['artifact', 'created_at'], name='ai_feedback_art_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='aifeedback',
            constraint=models.UniqueConstraint(fields=('artifact', 'user'), name='ai_feedback_unique_artifact_user'),
        ),
        migrations.AddIndex(
            model_name='aiartifact',
            index=models.Index(fields=['session', 'artifact_type'], name='ai_art_session_type_idx'),
        ),
        migrations.AddIndex(
            model_name='aiartifact',
            index=models.Index(fields=['requires_human_review', '-created_at'], name='ai_art_review_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiartifact',
            constraint=models.CheckConstraint(check=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), _connector='OR'), name='ai_artifact_confidence_range'),
        ),
    ]
