# Generated by Django 4.2.10 on 2025-11-25 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('NOTE_CREATE', 'Note Create'), ('NOTE_UPDATE', 'Note Update'), ('NOTE_DELETE', 'Note Delete'), ('ORDER_CREATE', 'Order Create'), ('DISCHARGE', 'Discharge'), ('CANCEL', 'Cancel'), ('ADMISSION', 'Admission'), ('TRANSFER', 'Transfer'), ('BED_ASSIGN', 'Bed Assign'), ('CHECK_IN', 'Check In'), ('USER_CREATE', 'User Create'), ('USER_UPDATE', 'User Update'), ('ROLE_CHANGE', 'Role Change')], max_length=50)),
                ('category', models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('PATIENT', 'Patient'), ('CLINICAL', 'Clinical'), ('ENCOUNTER', 'Encounter'), ('ADMIN', 'Admin'), ('WARD', 'Ward'), ('APPOINTMENT', 'Appointment')], max_length=50)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_user_ts_idx'), models.Index(fields=['category', '-timestamp'], name='audit_cat_ts_idx'), models.Index(fields=['action', '-timestamp'], name='audit_act_ts_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_res_idx'), models.Index(fields=['-timestamp'], name='audit_ts_idx')],
            },
        ),
    ]
