# Generated by Django 4.2.10 on 2025-12-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action_alter_auditlog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('PATIENT', 'Patient'), ('CLINICAL', 'Clinical'), ('ENCOUNTER', 'Encounter'), ('ADMIN', 'Admin'), ('WARD', 'Ward'), ('APPOINTMENT', 'Appointment'), ('LABORATORY', 'Laboratory'), ('DRUG_SAFETY', 'Drug Safety'), ('REFERRAL', 'Referral'), ('PRESCRIPTION', 'Prescription'), ('VITALS', 'Vital Signs'), ('NURSING', 'Nursing'), ('PHARMACY', 'Pharmacy')], max_length=50),
        ),
    ]
