# Generated by Codex on 2025-01-01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('audit', '0003_alter_auditlog_category'),
        ('core', '0006_enable_pg_trgm'),
    ]

    operations = [
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "audit_logs_description_trgm_idx "
                "ON audit_logs USING gin (description gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS audit_logs_description_trgm_idx;"
            ),
        ),
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "audit_logs_resource_name_trgm_idx "
                "ON audit_logs USING gin (resource_name gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS audit_logs_resource_name_trgm_idx;"
            ),
        ),
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "audit_logs_user_email_trgm_idx "
                "ON audit_logs USING gin (user_email gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS audit_logs_user_email_trgm_idx;"
            ),
        ),
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "audit_logs_ts_brin_idx "
                "ON audit_logs USING brin (timestamp);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS audit_logs_ts_brin_idx;"
            ),
        ),
    ]
