# Generated by Django 4.2.10 on 2025-12-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_trgm_brin_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('OFFSITE_ACCESS', 'Off-Site Access'), ('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('NOTE_CREATE', 'Note Create'), ('NOTE_UPDATE', 'Note Update'), ('NOTE_DELETE', 'Note Delete'), ('ORDER_CREATE', 'Order Create'), ('DISCHARGE', 'Discharge'), ('CANCEL', 'Cancel'), ('ADMISSION', 'Admission'), ('TRANSFER', 'Transfer'), ('BED_ASSIGN', 'Bed Assign'), ('CHECK_IN', 'Check In'), ('USER_CREATE', 'User Create'), ('USER_UPDATE', 'User Update'), ('ROLE_CHANGE', 'Role Change'), ('LAB_ORDER_SUBMIT', 'Lab Order Submitted'), ('LAB_SPECIMEN_COLLECT', 'Lab Specimen Collected'), ('LAB_SPECIMEN_RECEIVE', 'Lab Specimen Received'), ('LAB_PROCESSING_START', 'Lab Processing Started'), ('LAB_RESULT_ENTER', 'Lab Result Entered'), ('LAB_RESULT_VERIFY', 'Lab Result Verified'), ('LAB_ORDER_COMPLETE', 'Lab Order Completed'), ('LAB_ORDER_CANCEL', 'Lab Order Cancelled'), ('ALLERGY_RECORDED', 'Allergy Recorded'), ('ALLERGY_VERIFY', 'Allergy Verified'), ('ALLERGY_DEACTIVATE', 'Allergy Deactivated'), ('SAFETY_CHECK_PERFORMED', 'Safety Check Performed'), ('SAFETY_ALERT_OVERRIDE', 'Safety Alert Overridden'), ('REFERRAL_SUBMIT', 'Referral Submitted'), ('REFERRAL_ACCEPT', 'Referral Accepted'), ('REFERRAL_DECLINE', 'Referral Declined'), ('REFERRAL_SCHEDULE', 'Referral Scheduled'), ('REFERRAL_COMPLETE', 'Referral Completed'), ('PRESCRIPTION_CREATE', 'Prescription Created'), ('PRESCRIPTION_UPDATE', 'Prescription Updated'), ('PRESCRIPTION_DISCONTINUE', 'Prescription Discontinued'), ('VITALS_RECORD', 'Vital Signs Recorded'), ('VITALS_UPDATE', 'Vital Signs Updated'), ('FLUID_INTAKE_RECORD', 'Fluid Intake Recorded'), ('FLUID_OUTPUT_RECORD', 'Fluid Output Recorded'), ('FLUID_BALANCE_UPDATE', 'Fluid Balance Updated'), ('FLUID_BALANCE_DELETE', 'Fluid Balance Deleted'), ('INVOICE_CREATE', 'Invoice Created'), ('INVOICE_UPDATE', 'Invoice Updated'), ('INVOICE_CANCEL', 'Invoice Cancelled'), ('INVOICE_VOID', 'Invoice Voided'), ('PAYMENT_RECORD', 'Payment Recorded'), ('PAYMENT_VOID', 'Payment Voided'), ('CLAIM_SUBMIT', 'Claim Submitted'), ('CLAIM_UPDATE', 'Claim Updated'), ('INSURANCE_ADD', 'Insurance Added'), ('INSURANCE_UPDATE', 'Insurance Updated'), ('DOCUMENT_PRINT', 'Document Printed'), ('RECEIPT_PRINT', 'Receipt Printed'), ('INVOICE_PRINT', 'Invoice Printed'), ('REPORT_GENERATE', 'Report Generated'), ('REPORT_EXPORT', 'Report Exported'), ('BREAK_GLASS', 'Break-Glass Access')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('PATIENT', 'Patient'), ('CLINICAL', 'Clinical'), ('ENCOUNTER', 'Encounter'), ('ADMIN', 'Admin'), ('WARD', 'Ward'), ('APPOINTMENT', 'Appointment'), ('LABORATORY', 'Laboratory'), ('DRUG_SAFETY', 'Drug Safety'), ('REFERRAL', 'Referral'), ('PRESCRIPTION', 'Prescription'), ('VITALS', 'Vital Signs'), ('NURSING', 'Nursing'), ('PHARMACY', 'Pharmacy'), ('BILLING', 'Billing')], max_length=50),
        ),
    ]
