# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_audit_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    AuditLog = apps.get_model('audit', 'AuditLog')

    fallback = _get_fallback_facility(Facility)
    logs = list(
        AuditLog.objects.filter(facility__isnull=True).select_related(
            'user__primary_facility',
            'user__staff_profile__primary_facility'
        )
    )
    for log in logs:
        facility = None
        user = log.user
        if user and getattr(user, 'primary_facility_id', None):
            facility = user.primary_facility
        else:
            staff = getattr(user, 'staff_profile', None) if user else None
            if staff and getattr(staff, 'primary_facility_id', None):
                facility = staff.primary_facility
        if not facility and fallback:
            facility = fallback
        if facility:
            log.facility_id = facility.id
    if logs:
        AuditLog.objects.bulk_update(logs, ['facility'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('audit', '0005_alter_auditlog_action_alter_auditlog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='audit_logs',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_audit_facility, migrations.RunPython.noop),
    ]
