# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('audit', '0006_add_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility context for this audit event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.facility'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['facility', '-timestamp'], name='audit_facility_ts_idx'),
        ),
    ]
