# Generated by Django 4.2.29 on 2026-03-22 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wards', '0020_alter_admission_status'),
        ('nursing', '0013_alter_nursingtask_task_type'),
        ('core', '0010_seed_core_singletons'),
        ('users', '0025_alter_patientprofile_medical_record_number_and_more'),
        ('workflows', '0008_add_onboarding_step_ui_metadata'),
        ('encounters', '0011_rename_wards_encou_admitted_2d3a66_idx_wards_encou_admitte_7702a2_idx'),
        ('clinical_notes', '0016_timeline_event_trigram_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medical_ready_at', models.DateTimeField()),
                ('billing_cutoff_at', models.DateTimeField()),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('awaiting_clearance', 'Awaiting Clearance'), ('ready_for_finalization', 'Ready for Finalization'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened')], default='awaiting_clearance', max_length=32)),
                ('discharge_disposition', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_case', to='wards.admission')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_discharge_cases', to=settings.AUTH_USER_MODEL)),
                ('discharge_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_cases', to='clinical_notes.noteentry')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_cases', to='encounters.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_cases', to='core.facility')),
                ('nursing_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_case', to='nursing.nursingtask')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_cases', to='users.patientprofile')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_discharge_cases', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_discharge_cases', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_cases', to='workflows.clinicalworkflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DischargeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('billing_clearance', 'Billing Clearance'), ('nursing_finalization', 'Nursing Finalization'), ('pharmacy_followup', 'Pharmacy Follow-up'), ('lab_followup', 'Lab Follow-up'), ('imaging', 'Imaging'), ('social_work', 'Social Work'), ('transport', 'Transport'), ('documents', 'Documents'), ('other', 'Other')], max_length=40)),
                ('assigned_role', models.CharField(blank=True, max_length=30)),
                ('blocking', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_required', 'Not Required'), ('acknowledged_unresolved', 'Acknowledged Unresolved'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_discharge_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='discharge.dischargecase')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_discharge_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discharge_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['blocking', 'created_at'],
                'indexes': [models.Index(fields=['case', 'blocking', 'status'], name='discharge_d_case_id_379b73_idx'), models.Index(fields=['assigned_role', 'status'], name='discharge_d_assigne_776fe1_idx'), models.Index(fields=['task_type', 'status'], name='discharge_d_task_ty_cf7b46_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dischargetask',
            constraint=models.UniqueConstraint(fields=('case', 'task_type'), name='discharge_case_task_type_uniq'),
        ),
        migrations.AddIndex(
            model_name='dischargecase',
            index=models.Index(fields=['facility', 'status', '-medical_ready_at'], name='discharge_d_facilit_cfd98e_idx'),
        ),
        migrations.AddIndex(
            model_name='dischargecase',
            index=models.Index(fields=['patient', '-medical_ready_at'], name='discharge_d_patient_667bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='dischargecase',
            index=models.Index(fields=['admission'], name='discharge_d_admissi_ec9abe_idx'),
        ),
    ]
