"""
Seed definitions for opinionated clinical chart templates.
"""

SYSTEM_TEMPLATE_DEFINITIONS = [
    {
        'system_key': 'vital_signs',
        'name': 'Vital Signs Trend Chart',
        'description': 'Visit-scoped vital sign monitoring with paired blood pressure and critical thresholds.',
        'icon': 'activity',
        'category': 'cardiovascular',
        'scope_type': 'encounter',
        'default_interval': 'hourly',
        'display_mode': 'table',
        'fields': [
            {
                'name': 'Temperature',
                'field_key': 'temperature',
                'field_type': 'numeric',
                'display_order': 1,
                'group_name': 'Vitals',
                'config': {'unit': '°C', 'min': 35, 'max': 42, 'decimals': 1, 'critical_low': 36, 'critical_high': 39},
            },
            {
                'name': 'Blood Pressure',
                'field_key': 'blood_pressure',
                'field_type': 'paired',
                'display_order': 2,
                'group_name': 'Vitals',
                'is_required': True,
                'config': {
                    'fields': [{'key': 'systolic', 'label': 'Systolic'}, {'key': 'diastolic', 'label': 'Diastolic'}],
                    'separator': '/',
                    'unit': 'mmHg',
                    'critical_low': {'systolic': 90, 'diastolic': 60},
                    'critical_high': {'systolic': 180, 'diastolic': 110},
                },
            },
            {
                'name': 'Heart Rate',
                'field_key': 'heart_rate',
                'field_type': 'numeric',
                'display_order': 3,
                'group_name': 'Vitals',
                'config': {'unit': 'bpm', 'min': 30, 'max': 220, 'critical_low': 50, 'critical_high': 120},
            },
            {
                'name': 'Respiratory Rate',
                'field_key': 'respiratory_rate',
                'field_type': 'numeric',
                'display_order': 4,
                'group_name': 'Vitals',
                'config': {'unit': '/min', 'min': 8, 'max': 60, 'critical_low': 10, 'critical_high': 30},
            },
            {
                'name': 'SpO2',
                'field_key': 'oxygen_saturation',
                'field_type': 'numeric',
                'display_order': 5,
                'group_name': 'Vitals',
                'config': {'unit': '%', 'min': 50, 'max': 100, 'critical_low': 92},
            },
            {
                'name': 'Pain Score',
                'field_key': 'pain_level',
                'field_type': 'scale',
                'display_order': 6,
                'group_name': 'Assessment',
                'config': {'min': 0, 'max': 10, 'step': 1, 'critical_value': 8, 'critical_direction': 'above'},
            },
        ],
    },
    {
        'system_key': 'fluid_balance',
        'name': 'Fluid Balance Chart',
        'description': 'Admission-scoped intake and output monitoring with automatic net balance calculation.',
        'icon': 'droplets',
        'category': 'fluid_balance',
        'scope_type': 'admission',
        'default_interval': 'hourly',
        'display_mode': 'table',
        'fields': [
            {
                'name': 'Intake (mL)',
                'field_key': 'intake_ml',
                'field_type': 'numeric',
                'display_order': 1,
                'group_name': 'Fluid Balance',
                'config': {'unit': 'mL', 'min': 0, 'max': 5000},
            },
            {
                'name': 'Output (mL)',
                'field_key': 'output_ml',
                'field_type': 'numeric',
                'display_order': 2,
                'group_name': 'Fluid Balance',
                'config': {'unit': 'mL', 'min': 0, 'max': 5000},
            },
            {
                'name': 'Intake Route',
                'field_key': 'intake_route',
                'field_type': 'select',
                'display_order': 3,
                'group_name': 'Fluid Balance',
                'config': {'options': [
                    {'value': 'oral', 'label': 'Oral'},
                    {'value': 'iv', 'label': 'IV'},
                    {'value': 'enteral', 'label': 'Enteral'},
                    {'value': 'blood', 'label': 'Blood Products'},
                ]},
            },
            {
                'name': 'Output Source',
                'field_key': 'output_source',
                'field_type': 'select',
                'display_order': 4,
                'group_name': 'Fluid Balance',
                'config': {'options': [
                    {'value': 'urine', 'label': 'Urine'},
                    {'value': 'vomit', 'label': 'Vomit'},
                    {'value': 'stool', 'label': 'Stool'},
                    {'value': 'drain', 'label': 'Drain'},
                    {'value': 'other', 'label': 'Other'},
                ]},
            },
            {
                'name': 'Net Balance',
                'field_key': 'net_balance',
                'field_type': 'calculated',
                'display_order': 5,
                'group_name': 'Fluid Balance',
                'config': {'formula': '{intake_ml} - {output_ml}'},
            },
        ],
    },
    {
        'system_key': 'pain_assessment',
        'name': 'Pain Assessment Chart',
        'description': 'Encounter-scoped pain tracking with body-map location and qualitative context.',
        'icon': 'activity',
        'category': 'pain',
        'scope_type': 'encounter',
        'default_interval': '4hourly',
        'display_mode': 'table',
        'fields': [
            {
                'name': 'Pain Score',
                'field_key': 'pain_score',
                'field_type': 'scale',
                'display_order': 1,
                'is_required': True,
                'group_name': 'Pain',
                'config': {'min': 0, 'max': 10, 'step': 1, 'critical_value': 8, 'critical_direction': 'above'},
            },
            {
                'name': 'Pain Location',
                'field_key': 'pain_location',
                'field_type': 'body_map',
                'display_order': 2,
                'group_name': 'Pain',
                'is_required': True,
                'config': {'mode': 'pain'},
            },
            {
                'name': 'Pain Quality',
                'field_key': 'pain_quality',
                'field_type': 'select',
                'display_order': 3,
                'group_name': 'Pain',
                'config': {'options': [
                    {'value': 'sharp', 'label': 'Sharp'},
                    {'value': 'dull', 'label': 'Dull'},
                    {'value': 'burning', 'label': 'Burning'},
                    {'value': 'cramping', 'label': 'Cramping'},
                    {'value': 'throbbing', 'label': 'Throbbing'},
                ]},
            },
            {
                'name': 'Pattern',
                'field_key': 'pain_pattern',
                'field_type': 'select',
                'display_order': 4,
                'group_name': 'Pain',
                'config': {'options': [
                    {'value': 'constant', 'label': 'Constant'},
                    {'value': 'intermittent', 'label': 'Intermittent'},
                    {'value': 'movement_related', 'label': 'Movement Related'},
                ]},
            },
            {
                'name': 'Notes',
                'field_key': 'pain_notes',
                'field_type': 'textarea',
                'display_order': 5,
                'group_name': 'Pain',
            },
        ],
    },
    {
        'system_key': 'gcs',
        'name': 'Neuro / GCS Chart',
        'description': 'Admission-scoped neurological observation with Glasgow Coma Scale tracking.',
        'icon': 'brain',
        'category': 'neurological',
        'scope_type': 'admission',
        'default_interval': 'hourly',
        'display_mode': 'table',
        'fields': [
            {
                'name': 'Eye Opening',
                'field_key': 'eye_opening',
                'field_type': 'scale',
                'display_order': 1,
                'group_name': 'GCS',
                'is_required': True,
                'config': {'min': 1, 'max': 4, 'step': 1, 'labels': {'1': 'None', '2': 'Pain', '3': 'Voice', '4': 'Spontaneous'}},
            },
            {
                'name': 'Verbal Response',
                'field_key': 'verbal_response',
                'field_type': 'scale',
                'display_order': 2,
                'group_name': 'GCS',
                'is_required': True,
                'config': {'min': 1, 'max': 5, 'step': 1, 'labels': {'1': 'None', '2': 'Sounds', '3': 'Words', '4': 'Confused', '5': 'Oriented'}},
            },
            {
                'name': 'Motor Response',
                'field_key': 'motor_response',
                'field_type': 'scale',
                'display_order': 3,
                'group_name': 'GCS',
                'is_required': True,
                'config': {'min': 1, 'max': 6, 'step': 1, 'labels': {'1': 'None', '2': 'Extension', '3': 'Flexion', '4': 'Withdraws', '5': 'Localizes', '6': 'Obeys'}},
            },
            {
                'name': 'Pupil Reactivity',
                'field_key': 'pupil_reactivity',
                'field_type': 'select',
                'display_order': 4,
                'group_name': 'Neuro',
                'config': {'options': [
                    {'value': 'both_brisk', 'label': 'Both Brisk'},
                    {'value': 'sluggish', 'label': 'Sluggish'},
                    {'value': 'fixed', 'label': 'Fixed'},
                ]},
            },
            {
                'name': 'Total GCS',
                'field_key': 'total_gcs',
                'field_type': 'calculated',
                'display_order': 5,
                'group_name': 'GCS',
                'config': {'formula': '{eye_opening} + {verbal_response} + {motor_response}'},
            },
        ],
    },
    {
        'system_key': 'wound_body_map',
        'name': 'Wound Body Map Chart',
        'description': 'Admission-scoped wound and pressure injury mapping with structured body location.',
        'icon': 'bandage',
        'category': 'wound',
        'scope_type': 'admission',
        'default_interval': 'shift',
        'display_mode': 'grid',
        'fields': [
            {
                'name': 'Wound Location',
                'field_key': 'wound_location',
                'field_type': 'body_map',
                'display_order': 1,
                'group_name': 'Wound',
                'is_required': True,
                'config': {'mode': 'wound'},
            },
            {
                'name': 'Stage / Severity',
                'field_key': 'wound_stage',
                'field_type': 'select',
                'display_order': 2,
                'group_name': 'Wound',
                'config': {'options': [
                    {'value': 'stage_1', 'label': 'Stage 1'},
                    {'value': 'stage_2', 'label': 'Stage 2'},
                    {'value': 'stage_3', 'label': 'Stage 3'},
                    {'value': 'stage_4', 'label': 'Stage 4'},
                    {'value': 'unstageable', 'label': 'Unstageable'},
                ]},
            },
            {
                'name': 'Length',
                'field_key': 'wound_length_cm',
                'field_type': 'numeric',
                'display_order': 3,
                'group_name': 'Measurements',
                'config': {'unit': 'cm', 'min': 0, 'max': 100, 'decimals': 1},
            },
            {
                'name': 'Width',
                'field_key': 'wound_width_cm',
                'field_type': 'numeric',
                'display_order': 4,
                'group_name': 'Measurements',
                'config': {'unit': 'cm', 'min': 0, 'max': 100, 'decimals': 1},
            },
            {
                'name': 'Drainage',
                'field_key': 'drainage',
                'field_type': 'select',
                'display_order': 5,
                'group_name': 'Wound',
                'config': {'options': [
                    {'value': 'none', 'label': 'None'},
                    {'value': 'serous', 'label': 'Serous'},
                    {'value': 'purulent', 'label': 'Purulent'},
                    {'value': 'bloody', 'label': 'Bloody'},
                ]},
            },
            {
                'name': 'Wound Notes',
                'field_key': 'wound_notes',
                'field_type': 'textarea',
                'display_order': 6,
                'group_name': 'Wound',
            },
        ],
    },
    {
        'system_key': 'generic_observation',
        'name': 'Generic Observation Chart',
        'description': 'A safe starting chart for custom longitudinal observations.',
        'icon': 'clipboard-list',
        'category': 'custom',
        'scope_type': 'patient',
        'default_interval': 'daily',
        'display_mode': 'table',
        'fields': [
            {
                'name': 'Observation Value',
                'field_key': 'observation_value',
                'field_type': 'numeric',
                'display_order': 1,
                'group_name': 'Observation',
                'config': {'unit': 'units', 'min': 0, 'max': 9999},
            },
            {
                'name': 'Observation Label',
                'field_key': 'observation_label',
                'field_type': 'text',
                'display_order': 2,
                'group_name': 'Observation',
            },
            {
                'name': 'Observation Notes',
                'field_key': 'observation_notes',
                'field_type': 'textarea',
                'display_order': 3,
                'group_name': 'Observation',
            },
        ],
    },
]
