# Generated by Django 4.2.10 on 2025-12-17 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_multi_facility_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_context', models.CharField(choices=[('regular', 'Regular Hours'), ('after_hours', 'After Hours'), ('weekend', 'Weekend'), ('holiday', 'Holiday'), ('emergency', 'Emergency')], default='regular', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Override price for this context', max_digits=10)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Override tax rate (null = use service default)', max_digits=5, null=True)),
                ('effective_from', models.DateField(help_text='Date from which this price is effective')),
                ('effective_until', models.DateField(blank=True, help_text='Date until which this price is effective (null = indefinite)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_prices', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Specific department for this price (null = all departments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='core.department')),
                ('facility', models.ForeignKey(blank=True, help_text='Specific facility for this price (null = all facilities)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='core.facility')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='billing.service')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_service_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Price Override',
                'verbose_name_plural': 'Service Price Overrides',
                'ordering': ['-effective_from', 'service__name'],
                'indexes': [models.Index(fields=['service', 'facility', 'department', 'price_context'], name='billing_ser_service_c3c407_idx'), models.Index(fields=['service', 'is_active'], name='billing_ser_service_c25cdd_idx'), models.Index(fields=['effective_from', 'effective_until'], name='billing_ser_effecti_b98409_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.UniqueConstraint(fields=('service', 'facility', 'department', 'price_context', 'effective_from'), name='unique_service_price_override'),
        ),
    ]
