# Generated by Django 4.2.10 on 2025-12-17 22:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_multi_facility_foundation'),
        ('billing', '0003_add_service_price_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityBillingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV -> INV-00001)', max_length=10)),
                ('invoice_number_length', models.PositiveSmallIntegerField(default=8, help_text='Total length of invoice number (excluding prefix)')),
                ('invoice_due_days', models.PositiveIntegerField(default=30, help_text='Default number of days until invoice is due')),
                ('invoice_footer_text', models.TextField(blank=True, help_text='Custom text to appear on invoice footer')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default tax rate percentage', max_digits=5)),
                ('tax_inclusive_pricing', models.BooleanField(default=False, help_text='Are displayed prices inclusive of tax?')),
                ('tax_registration_number', models.CharField(blank=True, help_text='Tax registration/VAT number for invoices', max_length=50)),
                ('accepted_payment_methods', models.JSONField(default=list, help_text='List of accepted payment method codes')),
                ('default_payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('auto_generate_invoice_on_encounter_complete', models.BooleanField(default=True, help_text='Automatically generate invoice when outpatient encounter completes')),
                ('auto_generate_invoice_on_discharge', models.BooleanField(default=True, help_text='Automatically generate invoice on patient discharge')),
                ('require_deposit_for_admission', models.BooleanField(default=False, help_text='Require deposit before admission')),
                ('minimum_deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum deposit amount for admission', max_digits=10)),
                ('minimum_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum deposit as percentage of estimated bill', max_digits=5)),
                ('regular_hours_start', models.TimeField(default='08:00', help_text='Start of regular operating hours')),
                ('regular_hours_end', models.TimeField(default='17:00', help_text='End of regular operating hours')),
                ('weekend_hours_start', models.TimeField(blank=True, help_text='Start of weekend operating hours (null = closed)', null=True)),
                ('weekend_hours_end', models.TimeField(blank=True, help_text='End of weekend operating hours', null=True)),
                ('holidays', models.JSONField(default=list, help_text='List of holiday dates (ISO format: YYYY-MM-DD)')),
                ('currency_override', models.CharField(blank=True, help_text='Override facility currency for billing', max_length=3)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Decimal places for currency display')),
                ('rounding_method', models.CharField(choices=[('none', 'No Rounding'), ('round_half_up', 'Round Half Up'), ('round_down', 'Round Down'), ('round_up', 'Round Up'), ('nearest_5', 'Nearest 5'), ('nearest_10', 'Nearest 10')], default='round_half_up', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_settings', to=settings.AUTH_USER_MODEL)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='core.facility')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_billing_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Billing Settings',
                'verbose_name_plural': 'Facility Billing Settings',
            },
        ),
        migrations.CreateModel(
            name='BillingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable rule name', max_length=100)),
                ('code', models.CharField(help_text='Unique code for referencing this rule', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this rule does')),
                ('rule_type', models.CharField(choices=[('senior_discount', 'Senior Citizen Discount'), ('child_discount', 'Child Discount'), ('staff_discount', 'Staff/Employee Discount'), ('insurance_discount', 'Insurance Patient Discount'), ('loyalty_discount', 'Returning Patient Discount'), ('bulk_discount', 'Bulk Service Discount'), ('package_discount', 'Package/Bundle Discount'), ('emergency_surcharge', 'Emergency Service Surcharge'), ('after_hours_surcharge', 'After Hours Surcharge'), ('weekend_surcharge', 'Weekend Surcharge'), ('holiday_surcharge', 'Holiday Surcharge'), ('priority_surcharge', 'Priority/Express Surcharge'), ('rounding_adjustment', 'Rounding Adjustment'), ('minimum_charge', 'Minimum Charge'), ('maximum_discount', 'Maximum Discount Cap'), ('custom', 'Custom Rule')], max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Rule-specific parameters (validated against schema)')),
                ('adjustment_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='How the adjustment is calculated', max_length=20)),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage (e.g., 10.00 for 10%) or fixed amount', max_digits=10)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority (evaluated first)')),
                ('is_stackable', models.BooleanField(default=False, help_text='Can this rule be combined with other rules?')),
                ('applies_to_insurance', models.BooleanField(default=True, help_text='Does this rule apply to insured patients?')),
                ('applies_to_self_pay', models.BooleanField(default=True, help_text='Does this rule apply to self-pay patients?')),
                ('effective_from', models.DateField(help_text='Date from which this rule is effective')),
                ('effective_until', models.DateField(blank=True, help_text='Date until which this rule is effective (null = indefinite)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Specific categories this rule applies to (empty = all)', related_name='applicable_rules', to='billing.servicecategory')),
                ('applicable_services', models.ManyToManyField(blank=True, help_text='Specific services this rule applies to (empty = all)', related_name='applicable_rules', to='billing.service')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_rules', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Specific facility (null = all facilities)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_rules', to='core.facility')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_billing_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Rule',
                'verbose_name_plural': 'Billing Rules',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['facility', 'is_active', 'priority'], name='billing_bil_facilit_7bcecf_idx'), models.Index(fields=['rule_type', 'is_active'], name='billing_bil_rule_ty_4ddef1_idx'), models.Index(fields=['effective_from', 'effective_until'], name='billing_bil_effecti_ebcb21_idx'), models.Index(fields=['is_active', 'priority'], name='billing_bil_is_acti_77d176_idx')],
            },
        ),
    ]
