# Generated by Django 4.2.10 on 2025-12-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_billing_rules_and_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrule',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Rule-specific parameters (validated against schema)'),
        ),
        migrations.AlterField(
            model_name='facilitybillingsettings',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='List of accepted payment method codes'),
        ),
        migrations.AlterField(
            model_name='facilitybillingsettings',
            name='holidays',
            field=models.JSONField(blank=True, default=list, help_text='List of holiday dates (ISO format: YYYY-MM-DD)'),
        ),
    ]
