# Generated by Django 4.2.10 on 2025-12-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0012_fix_ward_department_hierarchy'),
        ('core', '0005_multi_facility_foundation'),
        ('billing', '0005_fix_json_fields_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='applied_rules',
            field=models.JSONField(blank=True, default=list, help_text='List of billing rule IDs that were applied to this invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department for department-specific pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.department'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='Associated clinical encounter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='encounters.Encounter'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility where services were rendered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.facility'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_context',
            field=models.CharField(choices=[('regular', 'Regular Hours'), ('after_hours', 'After Hours'), ('weekend', 'Weekend'), ('holiday', 'Holiday'), ('emergency', 'Emergency')], default='regular', help_text='Price context when invoice was generated', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['facility', 'status'], name='billing_inv_facilit_0bf472_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', 'status'], name='billing_inv_patient_ac2240_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date', 'status'], name='billing_inv_invoice_e5a3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['encounter'], name='billing_inv_encount_fe1234_idx'),
        ),
    ]
