# Generated by Django 4.2.10 on 2025-12-19 23:09

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_invoice_multi_facility_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=apps.billing.models.today_date),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(default=apps.billing.models.today_date),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
