# Generated by Django 4.2.10 on 2025-12-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('billing', '0009_alter_invoiceitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serviceprice',
            name='unique_service_price_override',
        ),
        migrations.AddField(
            model_name='invoice',
            name='rendering_unit',
            field=models.ForeignKey(blank=True, help_text='Clinical unit that rendered the services', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_invoices', to='organization.clinicalunit'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='clinical_unit',
            field=models.ForeignKey(blank=True, help_text='Specific clinical unit for this price (null = all units)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='organization.clinicalunit'),
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['service', 'clinical_unit', 'price_context'], name='billing_ser_service_2e15bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.UniqueConstraint(fields=('service', 'facility', 'department', 'clinical_unit', 'price_context', 'effective_from'), name='unique_service_price_override_v2'),
        ),
    ]
