# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_billing_facilities(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    Invoice = apps.get_model('billing', 'Invoice')
    InvoiceItem = apps.get_model('billing', 'InvoiceItem')
    Payment = apps.get_model('billing', 'Payment')
    Claim = apps.get_model('billing', 'Claim')
    Receipt = apps.get_model('billing', 'Receipt')

    fallback = _get_fallback_facility(Facility)

    invoices = list(
        Invoice.objects.filter(facility__isnull=True).select_related(
            'patient__facility',
            'encounter__facility',
            'admission__bed__ward__department__facility',
            'created_by__primary_facility',
            'created_by__staff_profile__primary_facility',
        )
    )
    for invoice in invoices:
        facility = None
        if invoice.encounter_id and getattr(invoice.encounter, 'facility_id', None):
            facility = invoice.encounter.facility
        elif invoice.patient_id and getattr(invoice.patient, 'facility_id', None):
            facility = invoice.patient.facility
        else:
            admission = getattr(invoice, 'admission', None)
            if admission and admission.bed_id:
                ward = getattr(admission.bed, 'ward', None)
                department = getattr(ward, 'department', None) if ward else None
                if department and getattr(department, 'facility_id', None):
                    facility = department.facility

        if not facility:
            created_by = invoice.created_by
            if created_by and getattr(created_by, 'primary_facility_id', None):
                facility = created_by.primary_facility
            else:
                staff = getattr(created_by, 'staff_profile', None) if created_by else None
                if staff and getattr(staff, 'primary_facility_id', None):
                    facility = staff.primary_facility
        if not facility and fallback:
            facility = fallback
        if facility:
            invoice.facility_id = facility.id

    if invoices:
        Invoice.objects.bulk_update(invoices, ['facility'])

    if Invoice.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "Invoice facility backfill incomplete. "
            "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
        )

    items = list(
        InvoiceItem.objects.filter(facility__isnull=True)
        .select_related('invoice__facility')
    )
    for item in items:
        facility = item.invoice.facility if item.invoice_id else None
        if not facility and fallback:
            facility = fallback
        if facility:
            item.facility_id = facility.id
    if items:
        InvoiceItem.objects.bulk_update(items, ['facility'])
    if InvoiceItem.objects.filter(facility__isnull=True).exists():
        raise RuntimeError("InvoiceItem facility backfill incomplete.")

    payments = list(
        Payment.objects.filter(facility__isnull=True)
        .select_related('invoice__facility')
    )
    for payment in payments:
        facility = payment.invoice.facility if payment.invoice_id else None
        if not facility and fallback:
            facility = fallback
        if facility:
            payment.facility_id = facility.id
    if payments:
        Payment.objects.bulk_update(payments, ['facility'])
    if Payment.objects.filter(facility__isnull=True).exists():
        raise RuntimeError("Payment facility backfill incomplete.")

    claims = list(
        Claim.objects.filter(facility__isnull=True)
        .select_related('invoice__facility')
    )
    for claim in claims:
        facility = claim.invoice.facility if claim.invoice_id else None
        if not facility and fallback:
            facility = fallback
        if facility:
            claim.facility_id = facility.id
    if claims:
        Claim.objects.bulk_update(claims, ['facility'])
    if Claim.objects.filter(facility__isnull=True).exists():
        raise RuntimeError("Claim facility backfill incomplete.")

    receipts = list(
        Receipt.objects.filter(facility__isnull=True)
        .select_related('payment__facility', 'payment__invoice__facility')
    )
    for receipt in receipts:
        facility = None
        if receipt.payment_id and getattr(receipt.payment, 'facility_id', None):
            facility = receipt.payment.facility
        elif receipt.payment_id and receipt.payment.invoice_id:
            facility = receipt.payment.invoice.facility
        if not facility and fallback:
            facility = fallback
        if facility:
            receipt.facility_id = facility.id
    if receipts:
        Receipt.objects.bulk_update(receipts, ['facility'])
    if Receipt.objects.filter(facility__isnull=True).exists():
        raise RuntimeError("Receipt facility backfill incomplete.")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('encounters', '0002_add_facility_scoping'),
        ('billing', '0010_add_clinical_unit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='invoice_items',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payments',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='claim',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='claims',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='receipt',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='receipts',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_billing_facilities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='invoices',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='invoice_items',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payments',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='claim',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='claims',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='receipts',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['facility', 'service'], name='billing_invoice_item_facility_service_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['facility', 'payment_date'], name='billing_pay_facility_date_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['facility', 'status'], name='bill_claim_fac_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['facility', 'receipt_date'], name='billing_receipt_facility_date_idx'),
        ),
    ]
