# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('billing', '0011_facility_scoping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoiceitem',
            new_name='billing_inv_facilit_bfbe06_idx',
            old_name='billing_invoice_item_facility_service_idx',
        ),
        migrations.RenameIndex(
            model_name='receipt',
            new_name='billing_rec_facilit_8f9766_idx',
            old_name='billing_receipt_facility_date_idx',
        ),
        migrations.AlterField(
            model_name='claim',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this claim', on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='facility',
            field=models.ForeignKey(help_text='Facility where services were rendered', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this invoice item', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this receipt', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.facility'),
        ),
    ]
