# Generated by Django 4.2.10 on 2026-01-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('billing', '0013_facility_scope_catalogs'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='claim',
            name='bill_claim_fac_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceitem',
            name='billing_inv_facilit_bfbe06_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_facility_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='billing_rec_facilit_8f9766_idx',
        ),
        migrations.RenameIndex(
            model_name='insuranceplan',
            new_name='billing_ins_facilit_18c06c_idx',
            old_name='billing_insu_facility_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='insuranceprovider',
            new_name='billing_ins_facilit_e182ee_idx',
            old_name='billing_insu_facility_name_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='billing_ser_facilit_e4d3b2_idx',
            old_name='billing_servi_facility_code_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='billing_ser_facilit_3f82fc_idx',
            old_name='billing_servi_facility_active_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecategory',
            new_name='billing_ser_facilit_d7821b_idx',
            old_name='billing_servi_facility_name_idx',
        ),
        migrations.AlterUniqueTogether(
            name='insuranceplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='claim',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='facility',
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this insurance plan', on_delete=django.db.models.deletion.PROTECT, related_name='insurance_plans', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this insurance provider', on_delete=django.db.models.deletion.PROTECT, related_name='insurance_providers', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility where services were rendered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='service',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this service', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this service category', on_delete=django.db.models.deletion.PROTECT, related_name='service_categories', to='core.facility'),
        ),
    ]
