# Generated by Django 4.2.10 on 2026-02-06 19:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def backfill_invoice_facility(apps, schema_editor):
    """
    Backfill Invoice.facility using Invoice.patient.facility.

    This is required for strict facility scoping (querysets filter on invoice.facility).
    """
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            """
            UPDATE billing_invoice AS i
            SET facility_id = p.facility_id
            FROM users_patientprofile AS p
            WHERE i.facility_id IS NULL
              AND i.patient_id = p.id
              AND p.facility_id IS NOT NULL
            """
        )
        return

    Invoice = apps.get_model('billing', 'Invoice')
    for invoice in Invoice.objects.filter(facility__isnull=True).select_related('patient'):
        patient = getattr(invoice, 'patient', None)
        facility_id = getattr(patient, 'facility_id', None) if patient else None
        if facility_id:
            invoice.facility_id = facility_id
            invoice.save(update_fields=['facility'])


def normalize_payment_method_codes(apps, schema_editor):
    """
    Canonicalize legacy payment method codes.
    """
    Payment = apps.get_model('billing', 'Payment')
    FacilityBillingSettings = apps.get_model('billing', 'FacilityBillingSettings')

    # Legacy frontend/backends used "card"; normalize to canonical backend code.
    Payment.objects.filter(payment_method='card').update(payment_method='credit_card')
    FacilityBillingSettings.objects.filter(default_payment_method='card').update(default_payment_method='credit_card')

    # accepted_payment_methods is JSON; update per-row.
    for row in FacilityBillingSettings.objects.all().only('id', 'accepted_payment_methods'):
        methods = list(row.accepted_payment_methods or [])
        if not methods:
            continue
        changed = False
        normalized = []
        for method in methods:
            if method == 'card':
                normalized.append('credit_card')
                changed = True
            else:
                normalized.append(method)
        if changed:
            row.accepted_payment_methods = normalized
            row.save(update_fields=['accepted_payment_methods'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_core_singletons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0014_remove_claim_bill_claim_fac_stat_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_drawers', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawers', to='core.facility')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cash_drawers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='facilitybillingsettings',
            name='cash_control_enabled',
            field=models.BooleanField(default=False, help_text='Require cash sessions for payment recording and enable close-of-day reconciliation'),
        ),
        migrations.AddField(
            model_name='facilitybillingsettings',
            name='cash_variance_threshold_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flag a cash session when abs(variance) exceeds this amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.CharField(choices=[('patient', 'Patient'), ('insurance', 'Insurance')], default='patient', help_text='Who is paying this amount (patient vs insurance remittance)', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('voided', 'Voided')], default='posted', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='FacilityInvoiceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequence', to='core.facility')),
            ],
            options={
                'verbose_name': 'Facility Invoice Sequence',
                'verbose_name_plural': 'Facility Invoice Sequences',
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_float_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_totals', models.JSONField(blank=True, default=dict)),
                ('expected_cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('counted_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_flagged', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('drawer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='billing.cashdrawer')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='core.facility')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=5)),
                ('movement_type', models.CharField(choices=[('float_in', 'Float In'), ('float_out', 'Float Out'), ('cash_drop', 'Cash Drop'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='billing.cashsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_session',
            field=models.ForeignKey(blank=True, help_text='Cash session during which this payment was recorded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.cashsession'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['facility', 'status', 'opened_at'], name='billing_cas_facilit_441999_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['facility', 'opened_by', 'status'], name='billing_cas_facilit_8b1082_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['facility', 'is_flagged', 'opened_at'], name='billing_cas_facilit_cd7c6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('facility', 'opened_by'), name='uniq_open_cash_session_per_user_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('drawer__isnull', False)), fields=('facility', 'drawer'), name='uniq_open_cash_session_per_drawer_per_facility'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['session', 'created_at'], name='billing_cas_session_2b3d27_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['facility', 'is_active'], name='billing_cas_facilit_ba60f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashdrawer',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='cash_drawer_facility_code_uniq'),
        ),
        migrations.RunPython(backfill_invoice_facility, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(normalize_payment_method_codes, reverse_code=migrations.RunPython.noop),
    ]
