# Generated by Django 4.2.10 on 2026-02-06 20:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_core_singletons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0015_cashdrawer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer', models.CharField(choices=[('patient', 'Patient'), ('insurance', 'Insurance')], default='patient', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance'), ('cheque', 'Cheque'), ('other', 'Other')], help_text='Intended payment method for this intent (e.g. mobile_money, credit_card)', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='created', max_length=20)),
                ('provider', models.CharField(choices=[('hubtel', 'Hubtel')], max_length=20)),
                ('client_reference', models.CharField(help_text='Client-side unique reference used to correlate webhooks (no PHI).', max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, help_text='Provider reference (e.g. paylinkId).', max_length=100, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=500, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('hubtel', 'Hubtel')], max_length=20)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('payload_encrypted', models.TextField(blank=True)),
                ('payload_checksum', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to='core.facility')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_settlement_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('client_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('mismatch', 'Mismatch')], default='unmatched', max_length=20)),
                ('mismatch_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.settlementbatch')),
                ('matched_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_lines', to='billing.paymentintent')),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_lines', to='billing.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PSPWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('hubtel', 'Hubtel')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('client_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('payload_encrypted', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'provider_reference', '-received_at'], name='psp_webhook_provider_ref_idx'), models.Index(fields=['provider', 'processing_status', '-received_at'], name='psp_webhook_provider_stat_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pspwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'payload_hash'), name='psp_webhook_provider_payload_hash_uniq'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='billing.cashsession'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='core.facility'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payment_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intent', to='billing.payment'),
        ),
        migrations.AddIndex(
            model_name='settlementline',
            index=models.Index(fields=['batch', 'match_status'], name='settle_line_batch_match_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementline',
            index=models.Index(fields=['provider_reference'], name='settle_line_provider_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementline',
            index=models.Index(fields=['client_reference'], name='settle_line_client_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['facility', 'provider', 'status', '-created_at'], name='settle_batch_fac_prov_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['facility', 'statement_date'], name='settle_batch_fac_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='psp_intent_fac_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['invoice', 'status', '-created_at'], name='psp_intent_inv_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider', 'provider_reference'], name='psp_intent_provider_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__isnull', False)), fields=('provider', 'provider_reference'), name='psp_intent_provider_reference_uniq'),
        ),
    ]
