# Generated by Django 4.2.10 on 2026-02-06 21:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_core_singletons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0016_paymentintent_settlementbatch_settlementline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error', max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['severity', 'code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NHISClaimBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('exported', 'Exported'), ('submitted', 'Submitted'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NHISClaimExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('payload_encrypted', models.TextField(blank=True)),
                ('payload_checksum', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayerServiceCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_code', models.CharField(max_length=50)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['payer__name', 'service__name', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('payload_encrypted', models.TextField(blank=True)),
                ('payload_checksum', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(blank=True, max_length=50)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('underpaid', 'Underpaid'), ('denied', 'Denied'), ('error', 'Error')], default='unmatched', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='last_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='paid_amount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='submission_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='payer_type',
            field=models.CharField(choices=[('nhis', 'NHIS'), ('private', 'Private'), ('other', 'Other')], default='private', help_text='Payer classification (NHIS vs private).', max_length=20),
        ),
        migrations.AddIndex(
            model_name='insuranceprovider',
            index=models.Index(fields=['facility', 'payer_type'], name='billing_ins_facilit_6647c5_idx'),
        ),
        migrations.AddField(
            model_name='remittanceline',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.remittanceimportjob'),
        ),
        migrations.AddField(
            model_name='remittanceline',
            name='matched_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_lines', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='remittanceline',
            name='matched_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_lines', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='remittanceimportjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_remittance_import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittanceimportjob',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_import_jobs', to='core.facility'),
        ),
        migrations.AddField(
            model_name='remittanceimportjob',
            name='payer',
            field=models.ForeignKey(help_text='Payer/provider whose remittance format is being imported (e.g. NHIS).', on_delete=django.db.models.deletion.PROTECT, related_name='remittance_import_jobs', to='billing.insuranceprovider'),
        ),
        migrations.AddField(
            model_name='payerservicecode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payer_service_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payerservicecode',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_service_codes', to='core.facility'),
        ),
        migrations.AddField(
            model_name='payerservicecode',
            name='payer',
            field=models.ForeignKey(help_text='Payer/provider this code applies to (e.g. NHIS).', on_delete=django.db.models.deletion.PROTECT, related_name='service_codes', to='billing.insuranceprovider'),
        ),
        migrations.AddField(
            model_name='payerservicecode',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_codes', to='billing.service'),
        ),
        migrations.AddField(
            model_name='payerservicecode',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payer_service_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhisclaimexportjob',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='billing.nhisclaimbatch'),
        ),
        migrations.AddField(
            model_name='nhisclaimexportjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nhis_export_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhisclaimexportjob',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhis_export_jobs', to='core.facility'),
        ),
        migrations.AddField(
            model_name='nhisclaimbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nhis_claim_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhisclaimbatch',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhis_claim_batches', to='core.facility'),
        ),
        migrations.AddField(
            model_name='nhisclaimbatch',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nhis_claim_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceposting',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_posting', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='insuranceposting',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_postings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceposting',
            name='remittance_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='billing.remittanceline'),
        ),
        migrations.AddField(
            model_name='claimvalidationissue',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='claim',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='billing.nhisclaimbatch'),
        ),
        migrations.AddIndex(
            model_name='remittanceline',
            index=models.Index(fields=['job', 'match_status'], name='remit_line_job_match_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceline',
            index=models.Index(fields=['claim_number'], name='remit_line_claim_num_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceline',
            index=models.Index(fields=['invoice_number'], name='remit_line_inv_num_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceimportjob',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='remit_job_fac_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='payerservicecode',
            index=models.Index(fields=['facility', 'payer', 'is_active'], name='billing_pay_facilit_7fef11_idx'),
        ),
        migrations.AddIndex(
            model_name='payerservicecode',
            index=models.Index(fields=['service', 'payer'], name='billing_pay_service_66c374_idx'),
        ),
        migrations.AddIndex(
            model_name='payerservicecode',
            index=models.Index(fields=['effective_from', 'effective_until'], name='billing_pay_effecti_bde461_idx'),
        ),
        migrations.AddConstraint(
            model_name='payerservicecode',
            constraint=models.UniqueConstraint(fields=('facility', 'payer', 'service', 'external_code', 'effective_from'), name='payer_service_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='nhisclaimexportjob',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='nhis_exp_fac_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='nhisclaimexportjob',
            index=models.Index(fields=['expires_at'], name='nhis_exp_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='nhisclaimbatch',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='nhis_batch_fac_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='nhisclaimbatch',
            index=models.Index(fields=['facility', 'period_start', 'period_end'], name='nhis_batch_fac_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='nhisclaimbatch',
            constraint=models.UniqueConstraint(fields=('facility', 'period_start', 'period_end'), name='nhis_batch_fac_period_uniq'),
        ),
        migrations.AddIndex(
            model_name='insuranceposting',
            index=models.Index(fields=['posted_at'], name='ins_post_posted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='claimvalidationissue',
            index=models.Index(fields=['claim', 'severity'], name='claim_issue_claim_sev_idx'),
        ),
    ]
