# Generated by Django 4.2.10 on 2026-02-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_claimvalidationissue_insuranceposting_nhisclaimbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
