# Generated by Django 4.2.10 on 2026-02-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_core_singletons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0018_alter_claim_claim_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerServiceCodeImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('preview_ready', 'Preview Ready'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('seed_services', models.BooleanField(default=False, help_text='If true, create missing ServiceCategory/Service records (services created inactive by default).')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('payload_encrypted', models.TextField(blank=True)),
                ('payload_checksum', models.CharField(blank=True, max_length=64)),
                ('parsed_payload_encrypted', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payer_service_code_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_service_code_import_jobs', to='core.facility')),
                ('payer', models.ForeignKey(help_text='Payer/provider whose codes are being imported (e.g. NHIS).', on_delete=django.db.models.deletion.PROTECT, related_name='payer_service_code_import_jobs', to='billing.insuranceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payerservicecodeimportjob',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='psc_imp_fac_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='payerservicecodeimportjob',
            index=models.Index(fields=['facility', 'payer', '-created_at'], name='psc_imp_fac_payer_idx'),
        ),
    ]

