# Generated by Django 4.2.10 on 2026-02-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_payerservicecodeimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitybillingsettings',
            name='default_consultation_service',
            field=models.ForeignKey(blank=True, help_text='Default consultation Service to bill for outpatient encounters when no appointment-specific mapping exists.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_default_consultation_for', to='billing.service'),
        ),
        migrations.AddField(
            model_name='facilitybillingsettings',
            name='lab_charge_trigger',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Collected'), ('completed', 'Completed')], default='collected', help_text='When to add lab test charges to draft invoices (NHIS can override to completed).', max_length=20),
        ),
        migrations.AddField(
            model_name='facilitybillingsettings',
            name='ward_stay_service',
            field=models.ForeignKey(blank=True, help_text='Service used for inpatient ward/bed stay (quantity = LOS in days). Unit price can be overridden per ward/bed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_ward_stay_for', to='billing.service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='auto_update_enabled',
            field=models.BooleanField(default=False, help_text='If true, this invoice is a draft that may be auto-updated from clinical events.'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if this line was generated by the auto-billing engine.'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_id',
            field=models.UUIDField(blank=True, help_text='Auto-billing source UUID (e.g. Encounter.id, LabOrderTest.id, SupplyRequest.id).', null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_type',
            field=models.CharField(blank=True, help_text='Auto-billing source type (e.g. consult, lab_test, ward_stay, supply_dispense).', max_length=30),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'is_auto_generated'], name='inv_item_auto_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_auto_generated', True), ('source_id__isnull', False), ('source_type__gt', '')), fields=('invoice', 'source_type', 'source_id'), name='invoice_item_auto_source_uniq'),
        ),
    ]
