export const ROLES = Object.freeze({
  ADMIN: 'admin',
  DOCTOR: 'doctor',
  NURSE: 'nurse',
  RECEPTIONIST: 'receptionist',
  HEAD_NURSE: 'head_nurse',
  NURSE_PRACTITIONER: 'nurse_practitioner',
  INPATIENT_DOCTOR: 'inpatient_doctor',
  PRACTITIONER: 'practitioner',
  PHYSICIAN: 'physician',
  BILLING: 'billing',
  PATIENT: 'patient',
  LAB_TECHNICIAN: 'lab_technician',
  PHARMACIST: 'pharmacist',
  PHARMACY_TECH: 'pharmacy_tech',
  STORE_KEEPER: 'store_keeper',
})

export const combineRoles = (...groups) =>
  Array.from(new Set(groups.flat().filter(Boolean)))

const CLINICAL = [
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.HEAD_NURSE,
  ROLES.NURSE_PRACTITIONER,
  ROLES.INPATIENT_DOCTOR,
  ROLES.PRACTITIONER,
  ROLES.PHYSICIAN,
]

export const ROLE_GROUPS = Object.freeze({
  ADMIN_ONLY: [ROLES.ADMIN],
  CLINICAL,
  CLINICAL_BASIC: [ROLES.DOCTOR, ROLES.NURSE],
  APPOINTMENTS: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.NURSE, ROLES.RECEPTIONIST],
  PATIENT_REGISTRY: [ROLES.ADMIN, ...CLINICAL, ROLES.RECEPTIONIST],
  PATIENT_DETAIL: [ROLES.ADMIN, ...CLINICAL, ROLES.RECEPTIONIST, ROLES.BILLING, ROLES.PATIENT],
  MY_PATIENTS: [...CLINICAL],
  WARDS: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.NURSE],
  ENCOUNTERS: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.NURSE, ROLES.RECEPTIONIST],
  ENCOUNTER_WORKSPACE: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.NURSE, ROLES.PRACTITIONER, ROLES.PHYSICIAN],
  ADMISSIONS: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.NURSE, ROLES.RECEPTIONIST],
  PRACTITIONER_AVAILABILITY: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.PHYSICIAN, ROLES.PRACTITIONER],
  NURSING_DASHBOARD: [ROLES.ADMIN, ROLES.NURSE, ROLES.HEAD_NURSE, ROLES.NURSE_PRACTITIONER],
  LAB_ACCESS: [ROLES.ADMIN, ROLES.LAB_TECHNICIAN, ROLES.DOCTOR, ROLES.NURSE, ROLES.PHYSICIAN, ROLES.PRACTITIONER],
  LAB_TECHS: [ROLES.ADMIN, ROLES.LAB_TECHNICIAN],
  PHARMACY: [ROLES.ADMIN, ROLES.PHARMACIST, ROLES.PHARMACY_TECH],
  BILLING: [ROLES.ADMIN, ROLES.BILLING, ROLES.RECEPTIONIST, ROLES.DOCTOR],
  INVENTORY: [ROLES.ADMIN, ROLES.PHARMACIST, ROLES.STORE_KEEPER],
})
