# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_patient_context_facility(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    RecentPatient = apps.get_model('patients', 'RecentPatient')
    PatientNote = apps.get_model('patients', 'PatientNote')

    fallback = _get_fallback_facility(Facility)

    recents = list(
        RecentPatient.objects.filter(facility__isnull=True)
        .select_related('patient_profile__facility')
    )
    for recent in recents:
        facility = None
        patient = getattr(recent, 'patient_profile', None)
        if patient and getattr(patient, 'facility_id', None):
            facility = patient.facility
        if not facility and fallback:
            facility = fallback
        if facility:
            recent.facility_id = facility.id

    if recents:
        RecentPatient.objects.bulk_update(recents, ['facility'])

    if RecentPatient.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "RecentPatient facility backfill incomplete. "
            "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
        )

    notes = list(
        PatientNote.objects.filter(facility__isnull=True)
        .select_related('patient_profile__facility')
    )
    for note in notes:
        facility = None
        patient = getattr(note, 'patient_profile', None)
        if patient and getattr(patient, 'facility_id', None):
            facility = patient.facility
        if not facility and fallback:
            facility = fallback
        if facility:
            note.facility_id = facility.id

    if notes:
        PatientNote.objects.bulk_update(notes, ['facility'])

    if PatientNote.objects.filter(facility__isnull=True).exists():
        raise RuntimeError(
            "PatientNote facility backfill incomplete. "
            "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpatient',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recent_patient_accesses',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='patient_notes',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_patient_context_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recentpatient',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recent_patient_accesses',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='patient_notes',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='recentpatient',
            index=models.Index(fields=['facility', 'user', '-access_date'], name='pat_recent_fac_user_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='patientnote',
            index=models.Index(fields=['facility', 'patient_profile', '-created_at'], name='pat_note_fac_pat_dt_idx'),
        ),
    ]
