# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('patients', '0002_facility_scoping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnote',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this patient note', on_delete=django.db.models.deletion.PROTECT, related_name='patient_notes', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='recentpatient',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this recent patient access', on_delete=django.db.models.deletion.PROTECT, related_name='recent_patient_accesses', to='core.facility'),
        ),
    ]
