# Generated by Django 4.2.10 on 2026-01-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('patients', '0004_patient_search_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsearch',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this patient search', on_delete=django.db.models.deletion.PROTECT, related_name='patient_searches', to='core.facility'),
        ),
    ]
