# Generated by Django 4.2.10 on 2025-10-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['status', 'admission_date'], name='wards_admis_status_a09274_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['bed', 'status'], name='wards_admis_bed_id_77faa2_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', 'status'], name='wards_admis_patient_79a8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_date'], name='wards_admis_admissi_2b2221_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['fhir_encounter_id'], name='wards_admis_fhir_en_78025a_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'status'], name='wards_bed_ward_id_5cd9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status'], name='wards_bed_status_48156d_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['bed_type'], name='wards_bed_bed_typ_987d8a_idx'),
        ),
    ]
