# Generated by Django 4.2.10 on 2025-10-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_admission_wards_admis_status_a09274_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='bedallocationlog',
            name='new_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bedallocationlog',
            name='previous_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], max_length=20),
        ),
    ]
