# Generated by Django 4.2.10 on 2025-11-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0003_alter_bed_status_alter_bedallocationlog_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='wards.bed'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per day at time of admission', max_digits=10),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased'), ('waiting', 'Waiting List')], default='admitted', max_length=20),
        ),
    ]
