# Generated by Django 4.2.10 on 2025-11-30 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wards', '0005_add_local_encounter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique identifier code for the amenity', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for frontend display (lucide-react)', max_length=50, null=True)),
                ('category', models.CharField(choices=[('medical', 'Medical Equipment'), ('comfort', 'Comfort & Convenience'), ('accessibility', 'Accessibility'), ('safety', 'Safety')], default='medical', max_length=20)),
                ('additional_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charge per night for this amenity', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Bed Amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WardSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order for display (lower numbers first)')),
                ('gender_restriction', models.CharField(choices=[('male_only', 'Male Only'), ('female_only', 'Female Only'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('accommodation_tier', models.CharField(choices=[('open', 'Open Ward (6+ beds)'), ('semi_private', 'Semi-Private (2-4 beds)'), ('private', 'Private (Single room)'), ('vip', 'VIP (Premium amenities)')], default='open', max_length=20)),
                ('rate_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier applied to ward base rate (e.g., 1.5 = 150%)', max_digits=4)),
                ('is_isolation_capable', models.BooleanField(default=False, help_text='Can this section handle isolation cases')),
                ('has_negative_pressure', models.BooleanField(default=False, help_text='Has negative pressure rooms for airborne isolation')),
                ('default_isolation_type', models.CharField(choices=[('none', 'None'), ('contact', 'Contact Isolation'), ('airborne', 'Airborne Isolation'), ('droplet', 'Droplet Isolation'), ('protective', 'Protective Isolation')], default='none', help_text='Default isolation type for this section', max_length=20)),
                ('max_beds', models.PositiveSmallIntegerField(default=0, help_text='Maximum number of beds (0 = unlimited)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ward', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='accommodation_tier',
            field=models.CharField(blank=True, choices=[('open', 'Open Ward'), ('semi_private', 'Semi-Private'), ('private', 'Private'), ('vip', 'VIP')], help_text='Override section accommodation tier if specified', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='current_isolation_type',
            field=models.CharField(choices=[('none', 'None'), ('contact', 'Contact Isolation'), ('airborne', 'Airborne Isolation'), ('droplet', 'Droplet Isolation'), ('protective', 'Protective Isolation')], default='none', help_text='Current isolation status of this bed', max_length=20),
        ),
        migrations.AddField(
            model_name='bed',
            name='has_negative_pressure',
            field=models.BooleanField(default=False, help_text='Has negative pressure for airborne isolation'),
        ),
        migrations.AddField(
            model_name='bed',
            name='is_isolation_capable',
            field=models.BooleanField(default=False, help_text='Can this bed handle isolation cases'),
        ),
        migrations.AddField(
            model_name='ward',
            name='uses_sections',
            field=models.BooleanField(default=False, help_text='If true, beds must be assigned to sections for better organization'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['accommodation_tier'], name='wards_bed_accommo_0539c7_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['current_isolation_type'], name='wards_bed_current_df9403_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['is_isolation_capable'], name='wards_bed_is_isol_d63b8e_idx'),
        ),
        migrations.AddField(
            model_name='wardsection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardsection',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardsection',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='wards.ward'),
        ),
        migrations.AddField(
            model_name='bed',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Amenities/features available with this bed', related_name='beds', to='wards.bedamenity'),
        ),
        migrations.AddField(
            model_name='bed',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section this bed belongs to (optional for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='wards.wardsection'),
        ),
        migrations.AddField(
            model_name='ward',
            name='default_section',
            field=models.ForeignKey(blank=True, help_text='Default section for backward compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_wards', to='wards.wardsection'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['section', 'status'], name='wards_bed_section_376950_idx'),
        ),
        migrations.AddIndex(
            model_name='wardsection',
            index=models.Index(fields=['ward', 'is_active'], name='wards_wards_ward_id_204641_idx'),
        ),
        migrations.AddIndex(
            model_name='wardsection',
            index=models.Index(fields=['gender_restriction'], name='wards_wards_gender__afc2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='wardsection',
            index=models.Index(fields=['accommodation_tier'], name='wards_wards_accommo_2cc2b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wardsection',
            unique_together={('ward', 'name')},
        ),
    ]
