# Generated by Django 4.2.10 on 2025-11-30 01:58

from django.db import migrations
from django.db.utils import ProgrammingError


def create_default_sections(apps, schema_editor):
    """
    Create a default "General" section for each existing ward
    and assign all existing beds to this section.
    """
    Ward = apps.get_model('wards', 'Ward')
    WardSection = apps.get_model('wards', 'WardSection')
    Bed = apps.get_model('wards', 'Bed')

    # Get ward IDs first to avoid ORM field resolution issues
    # Wrap in try/except to handle case where table doesn't exist yet
    try:
        ward_ids = list(Ward.objects.values_list('id', flat=True))
    except ProgrammingError:
        # Table doesn't exist yet (fresh database with complex migration ordering)
        # No wards to migrate, so we can safely return
        return

    for ward_id in ward_ids:
        ward = Ward.objects.get(id=ward_id)

        # Create default section
        default_section = WardSection.objects.create(
            ward=ward,
            name='General',
            description='Default section for existing beds',
            display_order=0,
            gender_restriction='mixed',
            accommodation_tier='open',
            rate_multiplier=1.00,
            is_isolation_capable=False,
            has_negative_pressure=False,
            default_isolation_type='none',
            max_beds=0,  # unlimited
            is_active=True,
        )

        # Update ward to reference this default section
        Ward.objects.filter(id=ward_id).update(
            default_section=default_section,
            uses_sections=False  # Don't force sections yet
        )

        # Assign all existing beds to the default section
        Bed.objects.filter(ward_id=ward_id, section__isnull=True).update(section=default_section)


def reverse_default_sections(apps, schema_editor):
    """
    Reverse the migration by removing default sections.
    """
    WardSection = apps.get_model('wards', 'WardSection')
    # Delete all sections named "General" (our default sections)
    WardSection.objects.filter(name='General').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0006_bedamenity_wardsection_bed_accommodation_tier_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_sections, reverse_default_sections),
    ]
