# Generated by Django 4.2.10 on 2025-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0007_create_default_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='additional_rate',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
