# Generated by Django 4.2.10 on 2025-12-09 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_default_roles(apps, schema_editor):
    """
    Seed default staff roles.

    These are common roles across most healthcare facilities.
    Facilities can customize by adding/editing roles via admin.
    """
    StaffRole = apps.get_model('wards', 'StaffRole')

    default_roles = [
        # Nursing roles
        {'name': 'Staff Nurse', 'code': 'staff_nurse', 'category': 'nursing',
         'description': 'General nursing staff providing direct patient care'},
        {'name': 'Charge Nurse', 'code': 'charge_nurse', 'category': 'nursing',
         'description': 'Senior nurse responsible for ward operations during shift'},
        {'name': 'Nurse Manager', 'code': 'nurse_manager', 'category': 'nursing',
         'description': 'Nursing unit manager overseeing ward operations'},

        # Medical roles
        {'name': 'Attending Physician', 'code': 'attending_physician', 'category': 'medical',
         'description': 'Primary physician responsible for patient care'},
        {'name': 'Resident', 'code': 'resident', 'category': 'medical',
         'description': 'Physician in training'},
        {'name': 'Consultant', 'code': 'consultant', 'category': 'medical',
         'description': 'Specialist providing consultations'},

        # Allied health roles
        {'name': 'Physiotherapist', 'code': 'physiotherapist', 'category': 'allied',
         'description': 'Physical therapy specialist'},
        {'name': 'Respiratory Therapist', 'code': 'respiratory_therapist', 'category': 'allied',
         'description': 'Respiratory care specialist'},
    ]

    for role_data in default_roles:
        StaffRole.objects.get_or_create(
            code=role_data['code'],
            defaults=role_data
        )


def seed_head_nurse_assignments(apps, schema_editor):
    """
    Migrate existing head_nurse relationships to WardStaffAssignment.

    This preserves backward compatibility with wards that already have
    head_nurse assigned.
    """
    Ward = apps.get_model('wards', 'Ward')
    StaffRole = apps.get_model('wards', 'StaffRole')
    WardStaffAssignment = apps.get_model('wards', 'WardStaffAssignment')

    try:
        charge_nurse_role = StaffRole.objects.get(code='charge_nurse')
    except StaffRole.DoesNotExist:
        return  # Role not seeded yet

    for ward in Ward.objects.filter(head_nurse__isnull=False):
        WardStaffAssignment.objects.get_or_create(
            ward=ward,
            practitioner=ward.head_nurse,
            defaults={
                'role': charge_nurse_role,
                'is_active': True,
                'is_primary': True,
            }
        )


def reverse_seed(apps, schema_editor):
    """Reverse migration - just delete seeded roles."""
    StaffRole = apps.get_model('wards', 'StaffRole')
    default_codes = [
        'staff_nurse', 'charge_nurse', 'nurse_manager',
        'attending_physician', 'resident', 'consultant',
        'physiotherapist', 'respiratory_therapist'
    ]
    StaffRole.objects.filter(code__in=default_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_add_user_patient_list'),
        ('wards', '0008_add_fluid_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name (e.g., 'Staff Nurse')", max_length=50, unique=True)),
                ('code', models.CharField(help_text="Unique code (e.g., 'staff_nurse')", max_length=30, unique=True)),
                ('category', models.CharField(choices=[('nursing', 'Nursing'), ('medical', 'Medical'), ('allied', 'Allied Health')], default='nursing', help_text='Role category for filtering', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the role')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role can be assigned')),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WardStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether currently assigned to this ward')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary ward assignment for this staff member')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(help_text='Practitioner assigned to this ward', on_delete=django.db.models.deletion.CASCADE, related_name='ward_assignments', to='users.practitionerprofile')),
                ('role', models.ForeignKey(help_text='Staff role on this ward', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='wards.staffrole')),
                ('ward', models.ForeignKey(help_text='Ward this staff member is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='wards.ward')),
            ],
            options={
                'verbose_name': 'Ward Staff Assignment',
                'verbose_name_plural': 'Ward Staff Assignments',
                'ordering': ['ward', 'role', 'practitioner'],
                'indexes': [models.Index(fields=['ward', 'is_active'], name='wards_wards_ward_id_ea661c_idx'), models.Index(fields=['practitioner', 'is_active'], name='wards_wards_practit_73a4c6_idx'), models.Index(fields=['role', 'is_active'], name='wards_wards_role_id_af0dad_idx')],
                'unique_together': {('ward', 'practitioner')},
            },
        ),
        # Seed default roles
        migrations.RunPython(seed_default_roles, reverse_seed),
        # Migrate existing head_nurse to assignments
        migrations.RunPython(seed_head_nurse_assignments, migrations.RunPython.noop),
    ]
