# Generated by Django 4.2.10 on 2025-12-17 22:16
# NOTE: This migration added facility FK which was later corrected in 0012
# to use department FK instead (hierarchy: Facility → Department → Ward)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_multi_facility_foundation'),
        ('wards', '0010_add_admission_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='The facility this ward belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.facility'),
        ),
    ]
