# Generated by Django 4.2.10 on 2025-12-29 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
        ('wards', '0014_admission_partial_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTeamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('consulting', 'Consulting'), ('co_managing', 'Co-Managing'), ('procedure', 'Procedure Team')], default='consulting', max_length=20)),
                ('consult_reason', models.TextField(blank=True)),
                ('consult_requested_at', models.DateTimeField(blank=True, null=True)),
                ('consult_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('consult_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('active', 'Active'), ('completed', 'Completed'), ('declined', 'Declined')], default='requested', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Care Team Assignment',
                'verbose_name_plural': 'Care Team Assignments',
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='primary_team',
            field=models.ForeignKey(blank=True, help_text='Primary clinical team responsible for this admission', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_admissions', to='organization.clinicalunit'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['primary_team', 'status'], name='wards_admis_primary_75aa06_idx'),
        ),
        migrations.AddField(
            model_name='careteamassignment',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team_assignments', to='wards.admission'),
        ),
        migrations.AddField(
            model_name='careteamassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_care_team_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careteamassignment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_team_assignments', to='organization.clinicalunit'),
        ),
        migrations.AddField(
            model_name='admission',
            name='consulting_teams',
            field=models.ManyToManyField(blank=True, help_text='Consulting teams involved in care', related_name='consulting_admissions', through='wards.CareTeamAssignment', to='organization.clinicalunit'),
        ),
        migrations.AddIndex(
            model_name='careteamassignment',
            index=models.Index(fields=['admission', 'status', 'is_active'], name='wards_caret_admissi_c89a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='careteamassignment',
            index=models.Index(fields=['team', 'status', 'is_active'], name='wards_caret_team_id_c80b51_idx'),
        ),
        migrations.AddConstraint(
            model_name='careteamassignment',
            constraint=models.UniqueConstraint(fields=('admission', 'team'), name='unique_admission_team'),
        ),
    ]
