# Generated by Codex on 2025-01-01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('wards', '0015_add_clinical_unit_fields'),
        ('core', '0006_enable_pg_trgm'),
    ]

    operations = [
        migrations.RunSQL(
            (
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "wards_ward_name_trgm_idx "
                "ON wards_ward USING gin (name gin_trgm_ops);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS wards_ward_name_trgm_idx;"
            ),
        ),
    ]
