# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_ward_facilities(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    Bed = apps.get_model('wards', 'Bed')
    Admission = apps.get_model('wards', 'Admission')
    BedAllocationLog = apps.get_model('wards', 'BedAllocationLog')
    WardTransfer = apps.get_model('wards', 'WardTransfer')

    fallback = _get_fallback_facility(Facility)

    def _assign_facility(model, queryset, resolver, label):
        items = list(queryset)
        for item in items:
            facility = resolver(item)
            if not facility and fallback:
                facility = fallback
            if facility:
                item.facility_id = facility.id
        if items:
            model.objects.bulk_update(items, ['facility'])
        if model.objects.filter(facility__isnull=True).exists():
            raise RuntimeError(
                f"{label} facility backfill incomplete. "
                "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
            )

    _assign_facility(
        Bed,
        Bed.objects.filter(facility__isnull=True)
        .select_related('ward__department__facility'),
        lambda obj: (
            obj.ward.department.facility
            if obj.ward_id and obj.ward.department_id and getattr(obj.ward.department, 'facility_id', None)
            else None
        ),
        'Bed',
    )

    _assign_facility(
        Admission,
        Admission.objects.filter(facility__isnull=True)
        .select_related('patient__facility', 'bed__facility'),
        lambda obj: (
            obj.patient.facility
            if obj.patient_id and getattr(obj.patient, 'facility_id', None)
            else (obj.bed.facility if obj.bed_id else None)
        ),
        'Admission',
    )

    _assign_facility(
        BedAllocationLog,
        BedAllocationLog.objects.filter(facility__isnull=True)
        .select_related('bed__facility'),
        lambda obj: obj.bed.facility if obj.bed_id else None,
        'BedAllocationLog',
    )

    _assign_facility(
        WardTransfer,
        WardTransfer.objects.filter(facility__isnull=True)
        .select_related('patient__facility', 'from_admission__facility'),
        lambda obj: (
            obj.patient.facility
            if obj.patient_id and getattr(obj.patient, 'facility_id', None)
            else (obj.from_admission.facility if obj.from_admission_id else None)
        ),
        'WardTransfer',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('wards', '0016_ward_name_trgm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ward_beds',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='admission',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='admissions',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='bedallocationlog',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bed_allocation_logs',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='wardtransfer',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ward_transfers',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_ward_facilities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bed',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ward_beds',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='admission',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='admissions',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='bedallocationlog',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bed_allocation_logs',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='wardtransfer',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ward_transfers',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['facility', 'status'], name='wards_bed_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['facility', 'status', 'admission_date'], name='wards_admission_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bedallocationlog',
            index=models.Index(fields=['facility', '-timestamp'], name='wards_bedlog_facility_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='wardtransfer',
            index=models.Index(fields=['facility', '-transfer_time'], name='wards_transfer_facility_time_idx'),
        ),
    ]
