# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('wards', '0017_facility_scoping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admission',
            new_name='wards_admis_facilit_e9d05e_idx',
            old_name='wards_admission_facility_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bed',
            new_name='wards_bed_facilit_612e23_idx',
            old_name='wards_bed_facility_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bedallocationlog',
            new_name='wards_bedal_facilit_abc6d4_idx',
            old_name='wards_bedlog_facility_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='wardtransfer',
            new_name='wards_wardt_facilit_c8ca8c_idx',
            old_name='wards_transfer_facility_time_idx',
        ),
        migrations.AlterField(
            model_name='admission',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this admission', on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this bed', on_delete=django.db.models.deletion.PROTECT, related_name='ward_beds', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='bedallocationlog',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this bed allocation log', on_delete=django.db.models.deletion.PROTECT, related_name='bed_allocation_logs', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='wardtransfer',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this ward transfer', on_delete=django.db.models.deletion.PROTECT, related_name='ward_transfers', to='core.facility'),
        ),
    ]
