# Generated by Django 4.2.10 on 2026-01-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_remove_rosterentry_roster_entry_team_or_practitioner_and_more'),
        ('wards', '0018_rename_wards_admission_facility_status_idx_wards_admis_facilit_e9d05e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='consulting_teams',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED: Use encounter.consulting_teams instead.', related_name='consulting_admissions', through='wards.CareTeamAssignment', to='organization.clinicalunit'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='primary_team',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use encounter.primary_team instead. Kept for backward compatibility.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_admissions', to='organization.clinicalunit'),
        ),
    ]
