# Generated by Django 4.2.29 on 2026-03-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0019_alter_admission_consulting_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('pending_discharge', 'Pending Discharge'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased'), ('waiting', 'Waiting List')], default='admitted', max_length=20),
        ),
    ]
