# Generated by Django 4.2.29 on 2026-05-01 14:50

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feature_entitlement_override'),
        ('wards', '0020_alter_admission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardSearchIndex',
            fields=[
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_projection', serialize=False, to='wards.ward')),
                ('search_document', models.TextField(blank=True)),
                ('ward_type', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_search_indexes', to='core.facility')),
            ],
            options={
                'indexes': [models.Index(fields=['facility', 'is_active'], name='ward_search_idx_fac_active_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='ward_search_idx_doc_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSearchIndex',
            fields=[
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_projection', serialize=False, to='wards.admission')),
                ('search_document', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_search_indexes', to='core.facility')),
            ],
            options={
                'indexes': [models.Index(fields=['facility', 'status'], name='adm_search_idx_fac_status_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='adm_search_idx_doc_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
