global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: staging
    client: staging

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: hms-api
    metrics_path: /api/metrics/
    static_configs:
      - targets:
          - metrics-proxy:9188
        labels:
          client: staging
          environment: staging
          service: api

  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
        labels:
          client: staging
          environment: staging
          service: node

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
        labels:
          client: staging
          environment: staging
          service: containers

  - job_name: postgres
    static_configs:
      - targets:
          - postgres-exporter:9187
        labels:
          client: staging
          environment: staging
          service: postgres

  - job_name: redis
    static_configs:
      - targets:
          - redis-exporter:9121
        labels:
          client: staging
          environment: staging
          service: redis

  - job_name: tempo
    static_configs:
      - targets:
          - tempo:3200
        labels:
          client: staging
          environment: staging
          service: tempo
