export * from '@/hooks/useDashboardQueries'
export * from '@/hooks/useDashboardActions'
export * from '@/hooks/useDoctorDashboard'
export * from './useAdminDashboardLiveUpdates'
export * from './useDoctorDashboardLiveUpdates'
export * from './useInpatientDashboardLiveUpdates'
export * from './useReceptionDashboardLiveUpdates'
export * from './useDashboardModuleGates'
