# Generated by Django 4.2.10 on 2026-01-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientfacilitylink',
            new_name='mpi_patient_facilit_e6dc76_idx',
            old_name='mpi_patien_facilit_74bba1_idx',
        ),
        migrations.RenameIndex(
            model_name='patientfacilitylink',
            new_name='mpi_patient_patient_7ea751_idx',
            old_name='mpi_patien_patient_8c8d8a_idx',
        ),
        migrations.RenameIndex(
            model_name='patientidentity',
            new_name='mpi_patient_nhis_id_4bdf69_idx',
            old_name='mpi_patien_nhis_id_7c5ea3_idx',
        ),
        migrations.RenameIndex(
            model_name='patientidentity',
            new_name='mpi_patient_last_na_a2391c_idx',
            old_name='mpi_patien_last_na_b8cb5a_idx',
        ),
    ]
