# Generated by Django 4.2.10 on 2025-12-29 18:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wards', '0014_admission_partial_indexes'),
        ('users', '0010_user_name_trgm_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_cache', models.CharField(blank=True, help_text='Cached full path string: "Hospital > Surgery > Team A"', max_length=1000)),
                ('code', models.CharField(help_text='Short code, unique within parent', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('operating_hours_start', models.TimeField(blank=True, null=True)),
                ('operating_hours_end', models.TimeField(blank=True, null=True)),
                ('operates_24_hours', models.BooleanField(default=False)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('has_own_budget', models.BooleanField(default=False)),
                ('cost_center_code', models.CharField(blank=True, max_length=50)),
                ('accepts_referrals', models.BooleanField(default=True)),
                ('accepts_admissions', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_units', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.clinicalunit')),
                ('root_unit', models.ForeignKey(blank=True, help_text='Cached reference to root/facility for O(1) access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.clinicalunit')),
            ],
            options={
                'verbose_name': 'Clinical Unit',
                'verbose_name_plural': 'Clinical Units',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_primary_leader', models.BooleanField(default=False, help_text='Whether this is considered the primary leadership role for a unit')),
                ('max_per_unit', models.PositiveSmallIntegerField(default=1, help_text='Maximum number of this role per unit')),
                ('can_approve', models.BooleanField(default=False, help_text='Can approve requests, leaves, etc.')),
                ('can_manage_staff', models.BooleanField(default=False, help_text='Can manage staff assignments within the unit')),
                ('can_manage_budget', models.BooleanField(default=False, help_text='Can manage budget and financial matters')),
                ('can_view_all_data', models.BooleanField(default=True, help_text='Can view all clinical data within the unit')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leadership Role Configuration',
                'verbose_name_plural': 'Leadership Role Configurations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignmentTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('requires_primary', models.BooleanField(default=False, help_text='Staff must have a primary unit assignment')),
                ('allows_secondary', models.BooleanField(default=False, help_text='Staff can have secondary unit assignments')),
                ('allows_multiple_primary', models.BooleanField(default=False, help_text='Staff can have multiple primary assignments')),
                ('supports_date_ranges', models.BooleanField(default=False, help_text='Assignments have effective date ranges (rotational)')),
                ('applicable_user_types', models.JSONField(blank=True, default=list, help_text='User types this assignment model applies to (e.g., ["doctor", "nurse"])')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Staff Assignment Type Configuration',
                'verbose_name_plural': 'Staff Assignment Type Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('can_be_root', models.BooleanField(default=False, help_text='Whether units of this type can be root nodes (no parent)')),
                ('depth_level', models.PositiveSmallIntegerField(default=0, help_text='Typical depth in hierarchy (0=root level)')),
                ('can_have_wards', models.BooleanField(default=False, help_text='Whether units of this type can have ward allocations')),
                ('can_admit_patients', models.BooleanField(default=False, help_text='Whether units of this type can be primary teams for admissions')),
                ('can_consult', models.BooleanField(default=False, help_text='Whether units of this type can be consulting teams')),
                ('can_have_budget', models.BooleanField(default=False, help_text='Whether units of this type can have their own budget/cost center')),
                ('attributes_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for validating custom_attributes on units of this type')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_parent_types', models.ManyToManyField(blank=True, help_text='Unit types that can be parents of this type', related_name='allowed_child_types', to='organization.unittypeconfig')),
            ],
            options={
                'verbose_name': 'Unit Type Configuration',
                'verbose_name_plural': 'Unit Type Configurations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitLeadership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leadership_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.leadershiproleconfig')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_assignments', to='organization.clinicalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit Leadership',
                'verbose_name_plural': 'Unit Leadership Assignments',
            },
        ),
        migrations.CreateModel(
            name='StaffUnitAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text="This is the staff member's primary unit")),
                ('is_secondary', models.BooleanField(default=False, help_text='This is a secondary assignment')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('role_description', models.CharField(blank=True, help_text='Specific role within the unit (e.g., "Senior Resident")', max_length=100)),
                ('fte_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Full-time equivalent percentage (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to=settings.AUTH_USER_MODEL)),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.staffassignmenttypeconfig')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_assignments', to='users.practitionerprofile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='organization.clinicalunit')),
            ],
            options={
                'verbose_name': 'Staff Unit Assignment',
                'verbose_name_plural': 'Staff Unit Assignments',
            },
        ),
        migrations.AddField(
            model_name='leadershiproleconfig',
            name='applicable_unit_types',
            field=models.ManyToManyField(blank=True, help_text='Unit types that can have this leadership role', related_name='available_leadership_roles', to='organization.unittypeconfig'),
        ),
        migrations.CreateModel(
            name='CrossCoverageSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('coverage_type', models.CharField(choices=[('on_call', 'On Call'), ('backup', 'Backup'), ('primary', 'Primary Coverage')], default='on_call', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('covered_unit', models.ForeignKey(help_text='The unit being covered', on_delete=django.db.models.deletion.CASCADE, related_name='coverage_schedules', to='organization.clinicalunit')),
                ('covering_practitioner', models.ForeignKey(blank=True, help_text='The practitioner providing coverage', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_assignments', to='users.practitionerprofile')),
                ('covering_unit', models.ForeignKey(blank=True, help_text='The unit providing coverage (alternative to individual practitioner)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_covered', to='organization.clinicalunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coverage_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cross Coverage Schedule',
                'verbose_name_plural': 'Cross Coverage Schedules',
            },
        ),
        migrations.AddField(
            model_name='clinicalunit',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='organization.unittypeconfig'),
        ),
        migrations.AddField(
            model_name='clinicalunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UnitWardAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocation_type', models.CharField(choices=[('dedicated', 'Dedicated Beds'), ('shared', 'Shared Pool'), ('overflow', 'Overflow Only')], default='dedicated', max_length=20)),
                ('allocated_beds', models.PositiveIntegerField(default=0, help_text='Number of dedicated beds')),
                ('max_beds', models.PositiveIntegerField(blank=True, help_text='Maximum beds for shared allocation', null=True)),
                ('min_beds', models.PositiveIntegerField(default=0, help_text='Minimum reserved beds')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower number = higher priority for bed assignment')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Days of week this allocation applies (0=Monday, 6=Sunday)', null=True, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ward_allocations', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_allocations', to='organization.clinicalunit')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_allocations', to='wards.ward')),
            ],
            options={
                'verbose_name': 'Unit Ward Allocation',
                'verbose_name_plural': 'Unit Ward Allocations',
                'indexes': [models.Index(fields=['unit', 'is_active'], name='organizatio_unit_id_ae2c5f_idx'), models.Index(fields=['ward', 'is_active'], name='organizatio_ward_id_0eeec1_idx'), models.Index(fields=['unit', 'is_active', 'effective_from', 'effective_until'], name='organizatio_unit_id_74d4ba_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='unitwardallocation',
            constraint=models.UniqueConstraint(fields=('unit', 'ward', 'effective_from'), name='unique_unit_ward_allocation'),
        ),
        migrations.AddIndex(
            model_name='unitleadership',
            index=models.Index(fields=['unit', 'role', 'is_active'], name='organizatio_unit_id_64bffe_idx'),
        ),
        migrations.AddIndex(
            model_name='unitleadership',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_763f03_idx'),
        ),
        migrations.AddIndex(
            model_name='unitleadership',
            index=models.Index(fields=['unit', 'is_active', 'effective_from', 'effective_until'], name='organizatio_unit_id_0e3e67_idx'),
        ),
        migrations.AddIndex(
            model_name='staffunitassignment',
            index=models.Index(fields=['unit', 'is_active'], name='organizatio_unit_id_5ff7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='staffunitassignment',
            index=models.Index(fields=['practitioner', 'is_active'], name='organizatio_practit_db00f1_idx'),
        ),
        migrations.AddIndex(
            model_name='staffunitassignment',
            index=models.Index(fields=['is_primary', 'is_active'], name='organizatio_is_prim_98c1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='staffunitassignment',
            index=models.Index(fields=['unit', 'is_active', 'effective_from', 'effective_until'], name='organizatio_unit_id_12d203_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscoverageschedule',
            index=models.Index(fields=['covered_unit', 'is_active', 'start_datetime', 'end_datetime'], name='organizatio_covered_47ce70_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscoverageschedule',
            index=models.Index(fields=['covering_practitioner', 'is_active'], name='organizatio_coverin_d5245a_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscoverageschedule',
            index=models.Index(fields=['covering_unit', 'is_active'], name='organizatio_coverin_4f0eed_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalunit',
            index=models.Index(fields=['code'], name='organizatio_code_fd72a8_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalunit',
            index=models.Index(fields=['unit_type', 'is_active'], name='organizatio_unit_ty_41e36c_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalunit',
            index=models.Index(fields=['parent', 'is_active'], name='organizatio_parent__9aa4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalunit',
            index=models.Index(fields=['root_unit', 'is_active'], name='organizatio_root_un_48db88_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalunit',
            index=models.Index(fields=['tree_id', 'lft'], name='organization_clinicalunit_277d'),
        ),
        migrations.AddConstraint(
            model_name='clinicalunit',
            constraint=models.UniqueConstraint(fields=('parent', 'code'), name='unique_code_within_parent'),
        ),
        migrations.AddConstraint(
            model_name='clinicalunit',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('code',), name='unique_root_code'),
        ),
    ]
