# Generated by Codex on 2025-01-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalunit',
            name='staffing_mode',
            field=models.CharField(
                choices=[('clinical_only', 'Clinical (Practitioner Only)'), ('ops_only', 'Operations (Non-Clinical Only)')],
                default='clinical_only',
                help_text='Controls which staff assignments are allowed for this unit',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='UnitMemberAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text="This is the staff member's primary unit")),
                ('is_secondary', models.BooleanField(default=False, help_text='This is a secondary assignment')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('role_description', models.CharField(blank=True, help_text='Specific role within the unit (e.g., "Billing Lead")', max_length=100)),
                ('fte_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Full-time equivalent percentage (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL)),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_assignments', to='organization.staffassignmenttypeconfig')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to='users.staff')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='organization.clinicalunit')),
            ],
            options={
                'verbose_name': 'Unit Member Assignment',
                'verbose_name_plural': 'Unit Member Assignments',
            },
        ),
        migrations.AddIndex(
            model_name='unitmemberassignment',
            index=models.Index(fields=['unit', 'is_active'], name='organizatio_unit_me_0ed1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmemberassignment',
            index=models.Index(fields=['staff', 'is_active'], name='organizatio_unit_me_94b04b_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmemberassignment',
            index=models.Index(fields=['is_primary', 'is_active'], name='organizatio_unit_me_7fc316_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmemberassignment',
            index=models.Index(fields=['unit', 'is_active', 'effective_from', 'effective_until'], name='organizatio_unit_me_aa62a9_idx'),
        ),
    ]
