# Generated by Codex on 2025-01-01

from django.db import migrations, models


def backfill_mixed_staffing_mode(apps, schema_editor):
    ClinicalUnit = apps.get_model('organization', 'ClinicalUnit')
    ClinicalUnit.objects.filter(
        unit_type__code__in=['facility', 'department', 'division'],
        staffing_mode='clinical_only'
    ).update(staffing_mode='mixed')


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_unit_staffing_mode_and_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalunit',
            name='staffing_mode',
            field=models.CharField(
                choices=[
                    ('clinical_only', 'Clinical (Practitioner Only)'),
                    ('mixed', 'Mixed (Clinical + Operations)'),
                    ('ops_only', 'Operations (Non-Clinical Only)'),
                ],
                default='clinical_only',
                help_text='Controls which staff assignments are allowed for this unit',
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_mixed_staffing_mode, migrations.RunPython.noop),
    ]
