# Generated by Django 4.2.10 on 2025-12-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_staffing_mode_mixed'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='unitmemberassignment',
            new_name='organizatio_unit_id_33ff56_idx',
            old_name='organizatio_unit_me_0ed1d3_idx',
        ),
        migrations.RenameIndex(
            model_name='unitmemberassignment',
            new_name='organizatio_staff_i_dc3f19_idx',
            old_name='organizatio_unit_me_94b04b_idx',
        ),
        migrations.RenameIndex(
            model_name='unitmemberassignment',
            new_name='organizatio_is_prim_d6f254_idx',
            old_name='organizatio_unit_me_7fc316_idx',
        ),
        migrations.RenameIndex(
            model_name='unitmemberassignment',
            new_name='organizatio_unit_id_afbaa0_idx',
            old_name='organizatio_unit_me_aa62a9_idx',
        ),
    ]
