# Generated by Django 4.2.10 on 2026-01-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_organizatio_unit_me_0ed1d3_idx_organizatio_unit_id_33ff56_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clinicalunit',
            name='organization_clinicalunit_277d',
        ),
    ]
