# Generated by Django 4.2.10 on 2026-01-12 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('users', '0017_alter_patientprofile_facility_alter_user_facilities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0005_remove_clinicalunit_organization_clinicalunit_277d'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name (e.g., "Day Shift")', max_length=100)),
                ('code', models.CharField(help_text='Short code (e.g., "DAY", "EVE", "NIGHT")', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False, help_text='True if shift ends after midnight (e.g., night shift 23:00-07:00)')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_definitions', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(help_text='Facility this shift belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shift_definitions', to='core.facility')),
            ],
            options={
                'verbose_name': 'Shift Definition',
                'verbose_name_plural': 'Shift Definitions',
                'ordering': ['display_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DutyRosterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('custom_start_time', models.TimeField(blank=True, null=True)),
                ('custom_end_time', models.TimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admitting', 'Admitting'), ('covering', 'Covering'), ('consulting', 'Consulting'), ('clinic', 'Clinic'), ('on_call', 'On Call')], default='admitting', max_length=20)),
                ('context', models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient'), ('emergency', 'Emergency'), ('all', 'All Contexts')], default='inpatient', max_length=20)),
                ('seniority_level', models.CharField(choices=[('attending', 'Attending'), ('fellow', 'Fellow'), ('resident', 'Resident'), ('intern', 'Intern')], default='attending', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary on-duty practitioner for this shift')),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_roster_templates', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_templates', to='core.facility')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_templates', to='users.practitionerprofile')),
                ('shift', models.ForeignKey(blank=True, help_text='Predefined shift (use this OR custom times)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='organization.shiftdefinition')),
                ('unit', models.ForeignKey(help_text='Clinical unit this template applies to', on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_templates', to='organization.clinicalunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_duty_roster_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duty Roster Template',
                'verbose_name_plural': 'Duty Roster Templates',
                'ordering': ['unit', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('role', models.CharField(choices=[('admitting', 'Admitting'), ('covering', 'Covering'), ('consulting', 'Consulting'), ('clinic', 'Clinic'), ('on_call', 'On Call')], default='admitting', max_length=20)),
                ('context', models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient'), ('emergency', 'Emergency'), ('all', 'All Contexts')], default='inpatient', max_length=20)),
                ('seniority_level', models.CharField(choices=[('attending', 'Attending'), ('fellow', 'Fellow'), ('resident', 'Resident'), ('intern', 'Intern')], default='attending', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('template', 'Generated from Template'), ('manual', 'Manually Created'), ('swap', 'Duty Swap')], default='manual', max_length=20)),
                ('swap_reason', models.TextField(blank=True, help_text='Reason for the swap')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_roster_entries', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_entries', to='core.facility')),
                ('original_practitioner', models.ForeignKey(blank=True, help_text='Original practitioner (for swaps)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swapped_duty_entries', to='users.practitionerprofile')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_entries', to='users.practitionerprofile')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_entries', to='organization.shiftdefinition')),
                ('template', models.ForeignKey(blank=True, help_text='Template this entry was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_entries', to='organization.dutyrostertemplate')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_entries', to='organization.clinicalunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_duty_roster_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duty Roster Entry',
                'verbose_name_plural': 'Duty Roster Entries',
                'ordering': ['date', 'start_time', 'seniority_level'],
            },
        ),
        migrations.AddIndex(
            model_name='shiftdefinition',
            index=models.Index(fields=['facility', 'is_active'], name='organizatio_facilit_1f3f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftdefinition',
            index=models.Index(fields=['facility', 'display_order'], name='organizatio_facilit_80f292_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftdefinition',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='unique_shift_code_per_facility'),
        ),
        migrations.AddIndex(
            model_name='dutyrostertemplate',
            index=models.Index(fields=['unit', 'is_active'], name='organizatio_unit_id_c2500a_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyrostertemplate',
            index=models.Index(fields=['practitioner', 'is_active'], name='organizatio_practit_88b98d_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyrostertemplate',
            index=models.Index(fields=['unit', 'day_of_week', 'is_active'], name='organizatio_unit_id_5a9a22_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyrostertemplate',
            index=models.Index(fields=['facility', 'is_active', 'effective_from', 'effective_until'], name='organizatio_facilit_30a6ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='dutyrostertemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('custom_end_time__isnull', True), ('custom_start_time__isnull', True), ('shift__isnull', False)), models.Q(('custom_end_time__isnull', False), ('custom_start_time__isnull', False), ('shift__isnull', True)), _connector='OR'), name='template_shift_or_custom_times'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['unit', 'date', 'start_time', 'end_time', 'is_active'], name='organizatio_unit_id_798421_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['practitioner', 'date', 'is_active'], name='organizatio_practit_495a29_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['facility', 'date', 'is_active'], name='organizatio_facilit_fc4be0_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['unit', 'date', 'role', 'context', 'is_active'], name='organizatio_unit_id_a249fa_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['unit', 'date', 'is_primary', 'is_active'], name='organizatio_unit_id_69d347_idx'),
        ),
    ]
