# Generated by Django 4.2.10 on 2026-01-13 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0006_add_duty_roster_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('operating_hours_start', models.TimeField(blank=True, null=True)),
                ('operating_hours_end', models.TimeField(blank=True, null=True)),
                ('operates_24_hours', models.BooleanField(default=False)),
                ('accepts_walk_ins', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinics', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Clinical unit that owns this clinic', on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='organization.clinicalunit')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='core.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['facility', 'is_active'], name='organizatio_facilit_1ca7a2_idx'), models.Index(fields=['department', 'is_active'], name='organizatio_departm_445c10_idx'), models.Index(fields=['code'], name='organizatio_code_637d8b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='unique_clinic_code_per_facility'),
        ),
    ]
