# Generated by Django 4.2.10 on 2026-01-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_clinicalunit_core_department_clinicschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicalunit',
            new_name='organizatio_core_de_a71fbd_idx',
            old_name='organizatio_core_de_5c14fd_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicschedule',
            new_name='organizatio_facilit_85807a_idx',
            old_name='organizatio_facility_f9f403_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicschedule',
            new_name='organizatio_departm_5637db_idx',
            old_name='organizatio_departme_5c5b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicschedule',
            new_name='organizatio_clinic__7b4bc2_idx',
            old_name='organizatio_clinic_237153_idx',
        ),
    ]
