# Generated by Django 4.2.10 on 2026-01-20 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_department_roster_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRosterPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Roster Pattern',
                'verbose_name_plural': 'Department Roster Patterns',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='rosterpatternslot',
            name='unique_roster_slot_per_day',
        ),
        migrations.RemoveIndex(
            model_name='rosterpatternslot',
            name='organization_roster_slot_day_idx',
        ),
        migrations.RemoveIndex(
            model_name='rosterpatternslot',
            name='organization_roster_slot_duty_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalunit',
            new_name='organizatio_ward_as_b4fceb_idx',
            old_name='organizatio_ward_p_a26a4c_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentdutytype',
            new_name='organizatio_departm_19f736_idx',
            old_name='organization_department_duty_type_active_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentdutytype',
            new_name='organizatio_departm_d2d829_idx',
            old_name='organization_department_duty_type_order_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentrosterplan',
            new_name='organizatio_departm_7a6110_idx',
            old_name='organization_department_roster_plan_status_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentrosterplan',
            new_name='organizatio_departm_e28463_idx',
            old_name='organization_department_roster_plan_dates_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentstation',
            new_name='organizatio_departm_0bd4ff_idx',
            old_name='organization_department_station_active_idx',
        ),
        migrations.RenameIndex(
            model_name='dutyroster',
            new_name='organizatio_unit_id_ff16f2_idx',
            old_name='organizatio_dutyroster_on_40ea2a_idx',
        ),
        migrations.RenameIndex(
            model_name='rosteroverride',
            new_name='organizatio_plan_id_fe8a5e_idx',
            old_name='organization_roster_override_date_idx',
        ),
        migrations.RenameIndex(
            model_name='rosteroverride',
            new_name='organizatio_plan_id_23fdd1_idx',
            old_name='organization_roster_override_duty_idx',
        ),
        migrations.RenameIndex(
            model_name='rosterpatternslot',
            new_name='organizatio_team_id_cefb76_idx',
            old_name='organization_roster_slot_team_idx',
        ),
        migrations.RenameIndex(
            model_name='teamrosterentry',
            new_name='organizatio_team_id_13bce6_idx',
            old_name='organization_team_roster_entry_date_idx',
        ),
        migrations.RenameIndex(
            model_name='teamrosterentry',
            new_name='organizatio_team_id_14efa9_idx',
            old_name='organization_team_roster_entry_duty_idx',
        ),
        migrations.RenameIndex(
            model_name='teamrosterentry',
            new_name='organizatio_practit_a5fa02_idx',
            old_name='organization_team_roster_entry_pract_idx',
        ),
        migrations.RenameIndex(
            model_name='teamrosterplan',
            new_name='organizatio_team_id_e1c8c0_idx',
            old_name='organization_team_roster_plan_status_idx',
        ),
        migrations.RenameIndex(
            model_name='teamrosterplan',
            new_name='organizatio_team_id_4da6e2_idx',
            old_name='organization_team_roster_plan_dates_idx',
        ),
        migrations.AddField(
            model_name='departmentdutytype',
            name='default_context_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='departmentdutytype',
            name='default_role_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='departmentrosterpattern',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='organization.departmentrosterplan'),
        ),
        migrations.AddField(
            model_name='rosterpatternslot',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='organization.departmentrosterpattern'),
        ),
        migrations.AddIndex(
            model_name='departmentrosterpattern',
            index=models.Index(fields=['plan', 'is_active'], name='organizatio_plan_id_727b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentrosterpattern',
            index=models.Index(fields=['plan', 'display_order'], name='organizatio_plan_id_8a084f_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentrosterpattern',
            constraint=models.UniqueConstraint(fields=('plan', 'name'), name='unique_roster_pattern_per_plan'),
        ),
        migrations.AddIndex(
            model_name='rosterpatternslot',
            index=models.Index(fields=['plan', 'pattern', 'day_offset'], name='organizatio_plan_id_bfc82d_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterpatternslot',
            index=models.Index(fields=['plan', 'pattern', 'duty_type'], name='organizatio_plan_id_4eb0d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='rosterpatternslot',
            constraint=models.UniqueConstraint(fields=('plan', 'pattern', 'day_offset', 'duty_type'), name='unique_roster_slot_per_pattern_day'),
        ),
    ]
