# Generated by Django 4.2.10 on 2026-01-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_roster_redesign'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rosterentry',
            name='roster_entry_team_or_practitioner',
        ),
        migrations.RenameIndex(
            model_name='rosterentry',
            new_name='organizatio_departm_627876_idx',
            old_name='organizat_departe_2d084d_idx',
        ),
        migrations.RenameIndex(
            model_name='rosterentry',
            new_name='organizatio_departm_55370d_idx',
            old_name='organizat_departe_6f0a4c_idx',
        ),
        migrations.RenameIndex(
            model_name='rosterentry',
            new_name='organizatio_team_id_0645c9_idx',
            old_name='organizat_team_da_8ed1f1_idx',
        ),
        migrations.RenameIndex(
            model_name='rosterentry',
            new_name='organizatio_date_505d7b_idx',
            old_name='organizat_date_st_5efba5_idx',
        ),
        migrations.RenameIndex(
            model_name='rotationrule',
            new_name='organizatio_departm_697946_idx',
            old_name='organizat_departe_1d0f1f_idx',
        ),
        migrations.RenameIndex(
            model_name='rotationrule',
            new_name='organizatio_departm_0ff2eb_idx',
            old_name='organizat_departe_5d5d2d_idx',
        ),
        migrations.AlterField(
            model_name='rotationrule',
            name='department',
            field=models.ForeignKey(help_text='Department this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rotation_rules', to='organization.clinicalunit'),
        ),
        migrations.AddConstraint(
            model_name='rosterentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('practitioner__isnull', True), ('team__isnull', False)), models.Q(('practitioner__isnull', False), ('team__isnull', True)), _connector='OR'), name='roster_entry_team_or_practitioner'),
        ),
    ]
