# Generated by Django 4.2.10 on 2026-01-23 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0014_remove_rosterentry_roster_entry_team_or_practitioner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('no_consecutive_days', 'No Consecutive Days'), ('day_pair_exclusion', 'Day Pair Exclusion'), ('team_day_exclusion', 'Team Day Exclusion'), ('max_per_period', 'Max Duties Per Period')], max_length=30)),
                ('params', models.JSONField(default=dict, help_text='Rule-specific parameters (see RULE_TEMPLATES for schema)')),
                ('apply_days', models.JSONField(blank=True, default=list, help_text='Days of week to apply rule (0=Mon, 6=Sun). Empty = all days.')),
                ('scope', models.CharField(choices=[('duty_type', 'Specific Duty Type'), ('department', 'Entire Department')], default='duty_type', max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='error', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='organization.clinicalunit')),
                ('duty_type', models.ForeignKey(blank=True, help_text='Leave blank to apply to all duty types in department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='organization.departmentdutytype')),
            ],
            options={
                'verbose_name': 'Roster Validation Rule',
                'verbose_name_plural': 'Roster Validation Rules',
                'db_table': 'organization_roster_validation_rule',
                'ordering': ['department', 'duty_type', 'name'],
            },
        ),
    ]
