# Generated by Django 4.2.10 on 2026-01-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_roster_validation_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rostervalidationrule',
            name='rule_type',
            field=models.CharField(choices=[('no_consecutive_days', 'No Consecutive Days'), ('linked_duty_no_consecutive', 'Linked Duties No Consecutive'), ('day_pair_exclusion', 'Day Pair Exclusion'), ('team_day_exclusion', 'Team Day Exclusion'), ('max_per_period', 'Max Duties Per Period')], max_length=30),
        ),
    ]
