# Generated by Django 4.2.10 on 2026-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_alter_rostervalidationrule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalunit',
            name='unit_category',
            field=models.CharField(choices=[('clinical', 'Clinical (Patient-Facing)'), ('ancillary', 'Ancillary (Support Services)'), ('administrative', 'Administrative')], default='clinical', help_text='Primary function of this unit', max_length=20),
        ),
    ]
