# Generated by Django 4.2.10 on 2026-01-24 10:00

from django.db import migrations


def populate_unit_category(apps, schema_editor):
    """
    Set unit_category based on existing data:
    - ops_only staffing_mode (except facility) -> ops_only
    - Units with codes like LAB, RAD, PHAR, PATH -> ancillary
    - Everything else (including facility) -> clinical (default)
    """
    ClinicalUnit = apps.get_model('organization', 'ClinicalUnit')
    UnitTypeConfig = apps.get_model('organization', 'UnitTypeConfig')

    # Get facility unit type to exclude it
    facility_type = UnitTypeConfig.objects.filter(code='facility').first()

    # ops_only category: ops_only staffing mode, but NOT facilities
    if facility_type:
        ClinicalUnit.objects.filter(
            staffing_mode='ops_only'
        ).exclude(
            unit_type=facility_type
        ).update(unit_category='ops_only')
    else:
        ClinicalUnit.objects.filter(staffing_mode='ops_only').update(unit_category='ops_only')

    # Ancillary: Lab, Radiology, Pharmacy, Pathology by code pattern
    ancillary_codes = ['LAB', 'RAD', 'PHAR', 'PATH', 'XRAY', 'MRI', 'CT']
    for code in ancillary_codes:
        ClinicalUnit.objects.filter(
            code__icontains=code,
            staffing_mode__in=['clinical_only', 'mixed']
        ).update(unit_category='ancillary')

    # Also check by name for common ancillary services
    ancillary_names = ['laboratory', 'radiology', 'pharmacy', 'pathology', 'imaging']
    for name in ancillary_names:
        ClinicalUnit.objects.filter(
            name__icontains=name,
            staffing_mode__in=['clinical_only', 'mixed'],
            unit_category='clinical'  # Don't override if already set
        ).update(unit_category='ancillary')


def reverse_populate(apps, schema_editor):
    """Reset all to default."""
    ClinicalUnit = apps.get_model('organization', 'ClinicalUnit')
    ClinicalUnit.objects.all().update(unit_category='clinical')


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_add_unit_category'),
    ]

    operations = [
        migrations.RunPython(populate_unit_category, reverse_populate),
    ]
