# Generated by Django 4.2.10 on 2026-01-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_populate_unit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalunit',
            name='unit_category',
            field=models.CharField(choices=[('clinical', 'Clinical (Patient-Facing)'), ('ancillary', 'Ancillary (Support Services)'), ('ops_only', 'Operations Only')], default='clinical', help_text='Primary function of this unit', max_length=20),
        ),
    ]
