# Generated by Django 4.2.10 on 2026-01-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_add_duty_type_category'),
        ('organization', '0019_alter_clinicalunit_unit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdutytype',
            name='breaks',
            field=models.JSONField(blank=True, default=list, help_text='Break periods during the duty, e.g. [{"start": "12:00", "end": "13:00"}]'),
        ),
        migrations.AddField(
            model_name='departmentdutytype',
            name='category',
            field=models.CharField(choices=[('clinic', 'Clinic Session'), ('ward', 'Ward Duty'), ('on_call', 'On-Call'), ('theatre', 'Theatre/Procedure'), ('admin', 'Administrative')], default='ward', help_text='Category determines if this duty type generates appointment slots', max_length=20),
        ),
        migrations.AddField(
            model_name='departmentdutytype',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Associated clinic for this duty type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_types', to='organization.clinic'),
        ),
        migrations.AddField(
            model_name='departmentdutytype',
            name='default_appointment_type',
            field=models.ForeignKey(blank=True, help_text='Default appointment type for slots generated from this duty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_types', to='appointments.appointmenttype'),
        ),
        migrations.AddField(
            model_name='departmentdutytype',
            name='max_patients_per_slot',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Maximum patients that can be booked per slot', null=True),
        ),
        migrations.AddField(
            model_name='departmentdutytype',
            name='slot_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duration of each appointment slot in minutes (required for clinic category)', null=True),
        ),
    ]
