# Generated by Django 4.2.10 on 2026-02-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_add_duty_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='assignment_timing',
            field=models.CharField(choices=[('booking', 'At Booking'), ('check_in', 'At Check-In')], default='booking', help_text='When to lock the final practitioner assignment.', max_length=24),
        ),
        migrations.AddField(
            model_name='clinic',
            name='booking_mode',
            field=models.CharField(choices=[('clinic_pool', 'Clinic Pool'), ('practitioner_direct', 'Practitioner Direct')], default='practitioner_direct', help_text='Clinic pool = book to session; practitioner direct = book to a named clinician.', max_length=24),
        ),
        migrations.AddField(
            model_name='clinic',
            name='late_reschedule_cutoff_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='Cutoff before session start after which cancellation is considered late.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='no_show_grace_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Minutes after appointment start before no-show is applied.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='overbook_hard_cap',
            field=models.PositiveSmallIntegerField(default=0, help_text='Absolute max overbooked appointments allowed per session.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='overbook_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentage-based overbook allowance for clinic pool sessions.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='soft_preassignment_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Lead time for soft prep assignment before session start.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='standard_reschedule_window_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Standard reschedule window before session start.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='waitlist_enabled',
            field=models.BooleanField(default=True, help_text='Enable waitlist promotions when a session is full.'),
        ),
    ]
