# Generated by Django 4.2.29 on 2026-03-24 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0025_alter_patientprofile_medical_record_number_and_more'),
        ('encounters', '0011_rename_wards_encou_admitted_2d3a66_idx_wards_encou_admitte_7702a2_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_seed_core_singletons'),
        ('organization', '0021_clinic_assignment_timing_clinic_booking_mode_and_more'),
        ('wards', '0020_alter_admission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('awaiting_clearance', 'Awaiting Clearance'), ('ready_for_activation', 'Ready for Activation'), ('intake_in_progress', 'Intake In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_clearance', max_length=32)),
                ('admission_source', models.CharField(blank=True, max_length=50)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergent', 'Emergent')], default='routine', max_length=20)),
                ('requested_admission_type', models.CharField(choices=[('emergency', 'Emergency'), ('elective', 'Elective'), ('maternity', 'Maternity'), ('newborn', 'Newborn')], default='elective', max_length=20)),
                ('requested_for_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_activation_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('expected_length_of_stay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_case', to='wards.admission')),
                ('admitting_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_cases', to='users.practitionerprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_cases', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_cases', to='users.patientprofile')),
                ('primary_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_cases', to='organization.clinicalunit')),
                ('requested_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_admission_cases', to='wards.bed')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_admission_cases', to=settings.AUTH_USER_MODEL)),
                ('requested_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_cases', to='wards.ward')),
                ('source_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_admission_cases', to='encounters.encounter')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('medical_admission_order', 'Medical Admission Order'), ('placement', 'Placement'), ('registration_completion', 'Registration Completion'), ('financial_clearance', 'Financial Clearance'), ('nursing_intake', 'Nursing Intake'), ('admission_documentation', 'Admission Documentation'), ('pharmacy_med_rec', 'Pharmacy Medication Reconciliation'), ('baseline_lab_followup', 'Baseline Lab Follow-up'), ('infection_control', 'Infection Control'), ('dietary', 'Dietary'), ('social_work', 'Social Work'), ('transport', 'Transport'), ('documents', 'Documents'), ('other', 'Other')], max_length=40)),
                ('phase', models.CharField(choices=[('pre_activation', 'Pre-Activation'), ('post_activation', 'Post-Activation')], max_length=24)),
                ('assigned_role', models.CharField(blank=True, max_length=30)),
                ('blocking', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_required', 'Not Required'), ('acknowledged_unresolved', 'Acknowledged Unresolved'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_admission_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admissions.admissioncase')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_admission_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['phase', '-blocking', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BedReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_reservations', to='wards.bed')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_reservations', to='admissions.admissioncase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bed_reservations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bed_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reserved_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='admissions__case_id_3948fe_idx'), models.Index(fields=['bed', 'status'], name='admissions__bed_id_41a1e4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bedreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('bed',), name='admission_active_bed_reservation_unique'),
        ),
        migrations.AddConstraint(
            model_name='bedreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('case',), name='admission_active_case_reservation_unique'),
        ),
        migrations.AddIndex(
            model_name='admissiontask',
            index=models.Index(fields=['case', 'phase', 'blocking', 'status'], name='admissions__case_id_0386ea_idx'),
        ),
        migrations.AddIndex(
            model_name='admissiontask',
            index=models.Index(fields=['assigned_role', 'status'], name='admissions__assigne_13abaa_idx'),
        ),
        migrations.AddIndex(
            model_name='admissiontask',
            index=models.Index(fields=['task_type', 'status'], name='admissions__task_ty_e29624_idx'),
        ),
        migrations.AddConstraint(
            model_name='admissiontask',
            constraint=models.UniqueConstraint(fields=('case', 'task_type'), name='admission_case_task_type_uniq'),
        ),
        migrations.AddIndex(
            model_name='admissioncase',
            index=models.Index(fields=['facility', 'status', '-requested_at'], name='admissions__facilit_2869dd_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncase',
            index=models.Index(fields=['patient', '-requested_at'], name='admissions__patient_d719dc_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncase',
            index=models.Index(fields=['requested_bed', 'status'], name='admissions__request_c2f9d4_idx'),
        ),
    ]
