# Generated by Django 4.2.10 on 2026-01-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consentaccesstoken',
            new_name='consent_con_target__6c093f_idx',
            old_name='consent_con_target__ab2b6d_idx',
        ),
        migrations.RenameIndex(
            model_name='consentgrant',
            new_name='consent_con_patient_93b442_idx',
            old_name='consent_con_patient_50c2b2_idx',
        ),
        migrations.RenameIndex(
            model_name='consentgrant',
            new_name='consent_con_source__2cd0cc_idx',
            old_name='consent_con_source__c5e98c_idx',
        ),
        migrations.RenameIndex(
            model_name='consentgrant',
            new_name='consent_con_expires_c1a83b_idx',
            old_name='consent_con_expires_5b2b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='crossfacilityreferral',
            new_name='consent_cro_patient_1a863b_idx',
            old_name='consent_cro_patient_7fe5f8_idx',
        ),
        migrations.RenameIndex(
            model_name='crossfacilityreferral',
            new_name='consent_cro_source__f1d12f_idx',
            old_name='consent_cro_source__2f1121_idx',
        ),
    ]
