# Generated by Django 4.2.10 on 2025-10-31 08:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_patientprofile_users_patie_medical_73a802_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(35.0), django.core.validators.MaxValueValidator(45.0)])),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate in beats per minute', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, help_text='Systolic blood pressure in mmHg', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, help_text='Diastolic blood pressure in mmHg', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)])),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Respiratory rate per minute', null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(60)])),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='Oxygen saturation percentage (SpO2)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('pain_level', models.PositiveIntegerField(blank=True, help_text='Pain level on scale of 0-10', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='users.patientprofile')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to='users.practitionerprofile')),
            ],
            options={
                'verbose_name': 'Vital Sign',
                'verbose_name_plural': 'Vital Signs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_date', models.DateField(default=django.utils.timezone.now)),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift')], max_length=10)),
                ('patient_condition', models.TextField(help_text='Current patient condition and status')),
                ('ongoing_issues', models.TextField(blank=True, help_text='Ongoing concerns or issues', null=True)),
                ('pending_tasks', models.TextField(blank=True, help_text='Tasks pending for next shift', null=True)),
                ('medication_changes', models.TextField(blank=True, help_text='Recent medication changes', null=True)),
                ('key_events', models.TextField(blank=True, help_text='Significant events during the shift', null=True)),
                ('care_plan_updates', models.TextField(blank=True, null=True)),
                ('family_updates', models.TextField(blank=True, help_text='Communication with family members', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_handoffs', to=settings.AUTH_USER_MODEL)),
                ('from_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_given', to='users.practitionerprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_handoffs', to='users.patientprofile')),
                ('to_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_received', to='users.practitionerprofile')),
            ],
            options={
                'ordering': ['-shift_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('medication', 'Medication Administration'), ('assessment', 'Patient Assessment'), ('vitals', 'Vital Signs Monitoring'), ('wound_care', 'Wound Care'), ('hygiene', 'Hygiene Care'), ('nutrition', 'Nutrition/Feeding'), ('mobility', 'Mobility Assistance'), ('documentation', 'Documentation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='users.practitionerprofile')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='users.practitionerprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nursing_tasks', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_tasks', to='users.patientprofile')),
            ],
            options={
                'ordering': ['scheduled_time', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='NursingAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('vital_signs', 'Critical Vital Signs'), ('medication', 'Medication Due'), ('task_overdue', 'Task Overdue'), ('patient_fall', 'Patient Fall Risk'), ('deterioration', 'Patient Deterioration'), ('equipment', 'Equipment Issue'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='users.practitionerprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_alerts', to='users.patientprofile')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='nursing.nursingtask')),
                ('related_vital_signs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='nursing.vitalsigns')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(help_text='e.g., Oral, IV, IM, SC', max_length=50)),
                ('frequency', models.CharField(help_text='e.g., Once daily, TID, PRN', max_length=100)),
                ('scheduled_time', models.DateTimeField()),
                ('administered_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('administered', 'Administered'), ('missed', 'Missed'), ('refused', 'Refused by Patient'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('administration_notes', models.TextField(blank=True, null=True)),
                ('reason_not_given', models.TextField(blank=True, help_text='Required if status is missed, refused, or held', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to='users.practitionerprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_med_administrations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='users.patientprofile')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to='users.practitionerprofile')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.AddIndex(
            model_name='vitalsigns',
            index=models.Index(fields=['patient', '-recorded_at'], name='nursing_vit_patient_527eef_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsigns',
            index=models.Index(fields=['is_critical', '-recorded_at'], name='nursing_vit_is_crit_54c812_idx'),
        ),
        migrations.AddIndex(
            model_name='shifthandoff',
            index=models.Index(fields=['patient', '-shift_date'], name='nursing_shi_patient_550ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='shifthandoff',
            index=models.Index(fields=['shift_date', 'shift_type'], name='nursing_shi_shift_d_27f8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='shifthandoff',
            index=models.Index(fields=['from_nurse', 'to_nurse'], name='nursing_shi_from_nu_452f73_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingtask',
            index=models.Index(fields=['patient', 'status', 'scheduled_time'], name='nursing_nur_patient_9532d3_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingtask',
            index=models.Index(fields=['assigned_to', 'status'], name='nursing_nur_assigne_28a8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingtask',
            index=models.Index(fields=['priority', 'scheduled_time'], name='nursing_nur_priorit_222f76_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingalert',
            index=models.Index(fields=['patient', 'is_acknowledged', '-created_at'], name='nursing_nur_patient_d1e518_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingalert',
            index=models.Index(fields=['severity', 'is_acknowledged'], name='nursing_nur_severit_c60e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingalert',
            index=models.Index(fields=['alert_type', '-created_at'], name='nursing_nur_alert_t_5dd0da_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['patient', 'scheduled_time', 'status'], name='nursing_med_patient_0ab22c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['status', 'scheduled_time'], name='nursing_med_status_4fa123_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['administered_by', 'administered_time'], name='nursing_med_adminis_1e60df_idx'),
        ),
    ]
