# Generated by Django 4.2.10 on 2025-11-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0005_add_local_encounter_model'),
        ('encounters', '0001_initial'),
        ('nursing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='The clinical encounter/visit during which these vitals were recorded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='encounters.Encounter'),
        ),
    ]
