# Generated by Django 4.2.10 on 2025-11-27 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical_notes', '0006_add_template_visibility_and_category'),
        ('nursing', '0003_require_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mar_entries', to='clinical_notes.prescription'),
        ),
    ]
