# Generated by Django 4.2.10 on 2025-12-03 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0007_create_default_sections'),
        ('users', '0006_add_user_patient_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical_notes', '0008_add_note_entry_version'),
        ('nursing', '0004_add_prescription_dispensing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentSheetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duration in days. Null means until discontinued.', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('total_doses_ordered', models.PositiveIntegerField(default=0, help_text='Total number of doses generated in MAR')),
                ('total_doses_dispensed', models.PositiveIntegerField(default=0, help_text='Total doses dispensed by pharmacy')),
                ('total_doses_administered', models.PositiveIntegerField(default=0, help_text='Total doses actually administered to patient')),
                ('discontinued_at', models.DateTimeField(blank=True, null=True)),
                ('discontinuation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_entries', to='wards.admission')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_entries', to=settings.AUTH_USER_MODEL)),
                ('discontinued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discontinued_orders', to='users.practitionerprofile')),
                ('encounter', models.ForeignKey(help_text='The clinical encounter during which this was ordered', on_delete=django.db.models.deletion.PROTECT, to='wards.encounter')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_orders', to='users.practitionerprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sheet_entries', to='users.patientprofile')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_entries', to='clinical_notes.prescription')),
            ],
            options={
                'verbose_name': 'Treatment Sheet Entry',
                'verbose_name_plural': 'Treatment Sheet Entries',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.PositiveIntegerField(help_text='Number of doses requested')),
                ('quantity_dispensed', models.PositiveIntegerField(blank=True, help_text='Actual quantity dispensed (may differ from requested)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_supplies', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='users.practitionerprofile')),
                ('treatment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='nursing.treatmentsheetentry')),
            ],
            options={
                'verbose_name': 'Supply Request',
                'verbose_name_plural': 'Supply Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='treatment_entry',
            field=models.ForeignKey(blank=True, help_text='Parent treatment sheet entry for inpatient medications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dose_administrations', to='nursing.treatmentsheetentry'),
        ),
        migrations.AddIndex(
            model_name='treatmentsheetentry',
            index=models.Index(fields=['admission', 'status'], name='nursing_tre_admissi_07940e_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsheetentry',
            index=models.Index(fields=['patient', 'status', '-start_datetime'], name='nursing_tre_patient_84b850_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsheetentry',
            index=models.Index(fields=['status', '-start_datetime'], name='nursing_tre_status_941ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['status', '-requested_at'], name='nursing_sup_status_24a6df_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['treatment_entry', '-requested_at'], name='nursing_sup_treatme_1f0d05_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['requested_by', 'status'], name='nursing_sup_request_98180d_idx'),
        ),
    ]
