# Generated by Django 4.2.10 on 2025-12-09 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_add_user_patient_list'),
        ('wards', '0008_add_fluid_balance'),
        ('nursing', '0005_treatmentsheetentry_supplyrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluidBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('intake', 'Intake'), ('output', 'Output')], max_length=10)),
                ('category', models.CharField(help_text='Category based on entry type (oral/iv/etc for intake, urine/vomit/etc for output)', max_length=20)),
                ('subcategory', models.CharField(blank=True, help_text='Optional subcategory, e.g., Water, Normal Saline, Foley, JP Drain', max_length=50, null=True)),
                ('volume_ml', models.PositiveIntegerField(help_text='Volume in milliliters', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, help_text='Admission for inpatient tracking. Null for outpatient.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fluid_balance_records', to='wards.admission')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fluid_balance_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_balance_records', to='users.patientprofile')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_fluid_entries', to='users.practitionerprofile')),
            ],
            options={
                'verbose_name': 'Fluid Balance Entry',
                'verbose_name_plural': 'Fluid Balance Entries',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='nursing_flu_patient_11ba1e_idx'), models.Index(fields=['patient', 'entry_type', '-recorded_at'], name='nursing_flu_patient_69906f_idx'), models.Index(fields=['admission', '-recorded_at'], name='nursing_flu_admissi_0f5d6f_idx')],
            },
        ),
    ]
