# Generated by Django 4.2.10 on 2025-12-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing', '0006_add_fluid_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluidbalance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fluid_balance_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_fluid_balance_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fluidbalance',
            index=models.Index(fields=['is_deleted', '-recorded_at'], name='nursing_flu_is_dele_53dd05_idx'),
        ),
    ]
