# Generated by Django 4.2.10 on 2025-12-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0007_add_fluid_balance_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluidbalance',
            name='colour',
            field=models.CharField(blank=True, help_text="Colour description for output entries (e.g., 'dark amber', 'clear', 'bloody')", max_length=100, null=True),
        ),
    ]
