# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_nursing_facilities(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    VitalSigns = apps.get_model('nursing', 'VitalSigns')
    NursingTask = apps.get_model('nursing', 'NursingTask')
    NursingAlert = apps.get_model('nursing', 'NursingAlert')
    MedicationAdministration = apps.get_model('nursing', 'MedicationAdministration')
    ShiftHandoff = apps.get_model('nursing', 'ShiftHandoff')
    TreatmentSheetEntry = apps.get_model('nursing', 'TreatmentSheetEntry')
    SupplyRequest = apps.get_model('nursing', 'SupplyRequest')
    FluidBalance = apps.get_model('nursing', 'FluidBalance')

    fallback = _get_fallback_facility(Facility)

    def _assign_facility(model, queryset, resolver, label):
        items = list(queryset)
        for item in items:
            facility = resolver(item)
            if not facility and fallback:
                facility = fallback
            if facility:
                item.facility_id = facility.id
        if items:
            model.objects.bulk_update(items, ['facility'])
        if model.objects.filter(facility__isnull=True).exists():
            raise RuntimeError(
                f"{label} facility backfill incomplete. "
                "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
            )

    _assign_facility(
        VitalSigns,
        VitalSigns.objects.filter(facility__isnull=True)
        .select_related('encounter__facility', 'patient__facility'),
        lambda obj: (
            obj.encounter.facility
            if obj.encounter_id and getattr(obj.encounter, 'facility_id', None)
            else (obj.patient.facility if obj.patient_id else None)
        ),
        'VitalSigns',
    )

    _assign_facility(
        NursingTask,
        NursingTask.objects.filter(facility__isnull=True).select_related('patient__facility'),
        lambda obj: obj.patient.facility if obj.patient_id else None,
        'NursingTask',
    )

    _assign_facility(
        NursingAlert,
        NursingAlert.objects.filter(facility__isnull=True).select_related('patient__facility'),
        lambda obj: obj.patient.facility if obj.patient_id else None,
        'NursingAlert',
    )

    _assign_facility(
        MedicationAdministration,
        MedicationAdministration.objects.filter(facility__isnull=True)
        .select_related('patient__facility', 'treatment_entry__facility'),
        lambda obj: (
            obj.patient.facility
            if obj.patient_id and getattr(obj.patient, 'facility_id', None)
            else (obj.treatment_entry.facility if obj.treatment_entry_id else None)
        ),
        'MedicationAdministration',
    )

    _assign_facility(
        ShiftHandoff,
        ShiftHandoff.objects.filter(facility__isnull=True).select_related('patient__facility'),
        lambda obj: obj.patient.facility if obj.patient_id else None,
        'ShiftHandoff',
    )

    _assign_facility(
        TreatmentSheetEntry,
        TreatmentSheetEntry.objects.filter(facility__isnull=True)
        .select_related('encounter__facility', 'patient__facility'),
        lambda obj: (
            obj.encounter.facility
            if obj.encounter_id and getattr(obj.encounter, 'facility_id', None)
            else (obj.patient.facility if obj.patient_id else None)
        ),
        'TreatmentSheetEntry',
    )

    _assign_facility(
        SupplyRequest,
        SupplyRequest.objects.filter(facility__isnull=True)
        .select_related('treatment_entry__facility', 'treatment_entry__patient__facility'),
        lambda obj: (
            obj.treatment_entry.facility
            if obj.treatment_entry_id and getattr(obj.treatment_entry, 'facility_id', None)
            else None
        ),
        'SupplyRequest',
    )

    _assign_facility(
        FluidBalance,
        FluidBalance.objects.filter(facility__isnull=True)
        .select_related('patient__facility'),
        lambda obj: obj.patient.facility if obj.patient_id else None,
        'FluidBalance',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('encounters', '0002_add_facility_scoping'),
        ('nursing', '0009_add_medication_patient_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='vital_sign_records',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='nursingtask',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='nursing_tasks',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='nursingalert',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='nursing_alerts',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='medication_administrations',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='shifthandoff',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='shift_handoffs',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='treatmentsheetentry',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='treatment_sheet_entries',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='supply_requests',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='fluid_balance_entries',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_nursing_facilities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vitalsigns',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='vital_sign_records',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='nursingtask',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='nursing_tasks',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='nursingalert',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='nursing_alerts',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='medication_administrations',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='shifthandoff',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='shift_handoffs',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='treatmentsheetentry',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='treatment_sheet_entries',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='supply_requests',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='fluidbalance',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='fluid_balance_entries',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='vitalsigns',
            index=models.Index(fields=['facility', '-recorded_at'], name='nursing_vitals_facility_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingtask',
            index=models.Index(fields=['facility', 'status', 'scheduled_time'], name='nursing_task_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingalert',
            index=models.Index(fields=['facility', 'is_acknowledged', '-created_at'], name='nursing_alert_facility_ack_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['facility', 'status', 'scheduled_time'], name='nursing_med_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shifthandoff',
            index=models.Index(fields=['facility', '-shift_date'], name='nursing_handoff_facility_date_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsheetentry',
            index=models.Index(fields=['facility', 'status', '-start_datetime'], name='nursing_treatment_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['facility', 'status', '-requested_at'], name='nursing_supply_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fluidbalance',
            index=models.Index(fields=['facility', 'entry_type', '-recorded_at'], name='nursing_fluid_facility_entry_idx'),
        ),
    ]
