# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('nursing', '0010_facility_scoping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fluidbalance',
            new_name='nursing_flu_facilit_0b41ab_idx',
            old_name='nursing_fluid_facility_entry_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationadministration',
            new_name='nursing_med_facilit_8675ed_idx',
            old_name='nursing_med_facility_status_idx',
        ),
        migrations.RenameIndex(
            model_name='nursingalert',
            new_name='nursing_nur_facilit_8340c2_idx',
            old_name='nursing_alert_facility_ack_idx',
        ),
        migrations.RenameIndex(
            model_name='nursingtask',
            new_name='nursing_nur_facilit_0822d0_idx',
            old_name='nursing_task_facility_status_idx',
        ),
        migrations.RenameIndex(
            model_name='shifthandoff',
            new_name='nursing_shi_facilit_ca3c99_idx',
            old_name='nursing_handoff_facility_date_idx',
        ),
        migrations.RenameIndex(
            model_name='supplyrequest',
            new_name='nursing_sup_facilit_c7d525_idx',
            old_name='nursing_supply_facility_status_idx',
        ),
        migrations.RenameIndex(
            model_name='treatmentsheetentry',
            new_name='nursing_tre_facilit_3a5fa5_idx',
            old_name='nursing_treatment_facility_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vitalsigns',
            new_name='nursing_vit_facilit_23db77_idx',
            old_name='nursing_vitals_facility_ts_idx',
        ),
        migrations.AlterField(
            model_name='fluidbalance',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this fluid balance entry', on_delete=django.db.models.deletion.PROTECT, related_name='fluid_balance_entries', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this medication administration', on_delete=django.db.models.deletion.PROTECT, related_name='medication_administrations', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='nursingalert',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this nursing alert', on_delete=django.db.models.deletion.PROTECT, related_name='nursing_alerts', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='nursingtask',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this nursing task', on_delete=django.db.models.deletion.PROTECT, related_name='nursing_tasks', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='shifthandoff',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this shift handoff', on_delete=django.db.models.deletion.PROTECT, related_name='shift_handoffs', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this supply request', on_delete=django.db.models.deletion.PROTECT, related_name='supply_requests', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='treatmentsheetentry',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this treatment sheet entry', on_delete=django.db.models.deletion.PROTECT, related_name='treatment_sheet_entries', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this vital sign record', on_delete=django.db.models.deletion.PROTECT, related_name='vital_sign_records', to='core.facility'),
        ),
    ]
