# Generated by Django 4.2.10 on 2026-01-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_storage_location_model'),
        ('nursing', '0011_rename_nursing_fluid_facility_entry_idx_nursing_flu_facilit_0b41ab_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='batch_used',
            field=models.ForeignKey(blank=True, help_text='Batch/lot used for this administration (FEFO tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_administrations', to='inventory.expirytracker'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='dispensing_location',
            field=models.ForeignKey(blank=True, help_text='Location from which medication was dispensed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_medications', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Linked inventory item for this medication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_administrations', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='treatmentsheetentry',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Linked inventory item for stock depletion on dispense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_entries', to='inventory.inventoryitem'),
        ),
    ]
