# Generated by Django 4.2.29 on 2026-03-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0012_add_inventory_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingtask',
            name='task_type',
            field=models.CharField(choices=[('medication', 'Medication Administration'), ('assessment', 'Patient Assessment'), ('vitals', 'Vital Signs Monitoring'), ('wound_care', 'Wound Care'), ('hygiene', 'Hygiene Care'), ('nutrition', 'Nutrition/Feeding'), ('mobility', 'Mobility Assistance'), ('documentation', 'Documentation'), ('discharge', 'Discharge Finalization'), ('other', 'Other')], max_length=20),
        ),
    ]
