# Generated by Django 4.2.10 on 2025-11-26 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_passwordresettoken'),
        ('wards', '0005_add_local_encounter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='Unique order identifier (auto-generated)', max_length=20, unique=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('collected', 'Specimen Collected'), ('received', 'Received in Lab'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical indication or notes for lab')),
                ('fasting_required', models.BooleanField(default=False, help_text='Whether patient must be fasting')),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('fhir_id', models.CharField(blank=True, help_text='FHIR ServiceRequest resource ID', max_length=100, null=True, unique=True)),
                ('fhir_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='encounters.Encounter')),
                ('ordering_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_labs', to='users.practitionerprofile')),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('collected', 'Specimen Collected'), ('received', 'Received in Lab'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tests', to='laboratory.laborder')),
            ],
            options={
                'verbose_name': 'Lab Order Test',
                'verbose_name_plural': 'Lab Order Tests',
            },
        ),
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Internal test code (e.g., 'CBC', 'BMP')", max_length=20, unique=True)),
                ('loinc_code', models.CharField(blank=True, help_text='LOINC standard code for interoperability', max_length=20, null=True)),
                ('name', models.CharField(help_text="Full test name (e.g., 'Complete Blood Count')", max_length=255)),
                ('short_name', models.CharField(help_text="Abbreviated name (e.g., 'CBC')", max_length=50)),
                ('category', models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Chemistry'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology'), ('urinalysis', 'Urinalysis'), ('coagulation', 'Coagulation'), ('serology', 'Serology'), ('molecular', 'Molecular/PCR'), ('pathology', 'Pathology'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('specimen_type', models.CharField(help_text="Required specimen type (e.g., 'Whole Blood', 'Serum', 'Urine')", max_length=50)),
                ('container_type', models.CharField(help_text="Container/tube type (e.g., 'Lavender Top', 'Red Top', 'Sterile Cup')", max_length=50)),
                ('volume_required', models.CharField(blank=True, help_text="Minimum volume needed (e.g., '5 mL', '2-3 mL')", max_length=50)),
                ('special_instructions', models.TextField(blank=True, help_text='Special handling or collection instructions')),
                ('reference_ranges', models.JSONField(default=dict, help_text='Reference ranges by population (e.g., {"adult_male": {"low": 4.5, "high": 5.5, "unit": "million/uL"}})')),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=30)),
                ('tat_hours', models.PositiveIntegerField(help_text='Expected turnaround time in hours')),
                ('price', models.DecimalField(decimal_places=2, help_text='Test price', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether test is currently available for ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Test Catalog',
                'ordering': ['category', 'short_name'],
                'indexes': [models.Index(fields=['code'], name='laboratory__code_7c1f6a_idx'), models.Index(fields=['loinc_code'], name='laboratory__loinc_c_49fa24_idx'), models.Index(fields=['category', 'is_active'], name='laboratory__categor_8709ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabSpecimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(help_text='Specimen barcode identifier', max_length=50, unique=True)),
                ('specimen_type', models.CharField(max_length=50)),
                ('container_type', models.CharField(max_length=50)),
                ('volume_collected', models.CharField(blank=True, help_text='Actual volume collected', max_length=30)),
                ('collection_site', models.CharField(blank=True, help_text='Anatomical site of collection', max_length=100)),
                ('collected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('in_transit', 'In Transit'), ('received', 'Received in Lab'), ('processing', 'Processing'), ('stored', 'Stored'), ('disposed', 'Disposed'), ('rejected', 'Rejected')], default='collected', max_length=20)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for specimen rejection (e.g., hemolyzed, insufficient volume)')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, help_text="Storage location in lab (e.g., 'Freezer A-12')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_specimens', to='users.practitionerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='laboratory.laborder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_specimens', to='users.practitionerprofile')),
            ],
            options={
                'verbose_name': 'Lab Specimen',
                'verbose_name_plural': 'Lab Specimens',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(help_text='Result value (numeric or text)', max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=4, help_text='Lower reference range', max_digits=10, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=4, help_text='Upper reference range', max_digits=10, null=True)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical_low', 'Critical Low'), ('critical_high', 'Critical High'), ('abnormal', 'Abnormal')], default='normal', max_length=20)),
                ('interpretation', models.TextField(blank=True, help_text='Additional interpretation or comments')),
                ('performed_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False, help_text='Whether result has been verified by supervisor/pathologist')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('fhir_id', models.CharField(blank=True, help_text='FHIR Observation resource ID', max_length=100, null=True, unique=True)),
                ('fhir_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.labordertest')),
                ('performed_by', models.ForeignKey(help_text='Lab technician who performed the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_results', to='users.practitionerprofile')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labspecimen')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to='users.practitionerprofile')),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Panel code (e.g., 'CMP', 'LFT')", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Panel name (e.g., 'Comprehensive Metabolic Panel')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Panel price (usually discounted vs individual tests)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tests', models.ManyToManyField(help_text='Tests included in this panel', related_name='panels', to='laboratory.labtestcatalog')),
            ],
            options={
                'verbose_name': 'Lab Panel',
                'verbose_name_plural': 'Lab Panels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labordertest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tests', to='laboratory.labtestcatalog'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='panels',
            field=models.ManyToManyField(blank=True, related_name='orders', to='laboratory.labpanel'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='tests',
            field=models.ManyToManyField(related_name='orders', through='laboratory.LabOrderTest', to='laboratory.labtestcatalog'),
        ),
        migrations.AddIndex(
            model_name='labspecimen',
            index=models.Index(fields=['barcode'], name='laboratory__barcode_6708c5_idx'),
        ),
        migrations.AddIndex(
            model_name='labspecimen',
            index=models.Index(fields=['order', 'status'], name='laboratory__order_i_beeb19_idx'),
        ),
        migrations.AddIndex(
            model_name='labspecimen',
            index=models.Index(fields=['status', 'is_rejected'], name='laboratory__status_67ebe0_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['order_test'], name='laboratory__order_t_56398f_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['flag', 'is_verified'], name='laboratory__flag_63e6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['performed_at'], name='laboratory__perform_ead5e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labordertest',
            unique_together={('order', 'test')},
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'status'], name='laboratory__patient_a022a2_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['order_number'], name='laboratory__order_n_0aa245_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', 'priority'], name='laboratory__status_94761c_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['ordered_at'], name='laboratory__ordered_0d3d89_idx'),
        ),
    ]
