# Generated by Django 4.2.10 on 2025-11-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpanel',
            name='is_facility_modified',
            field=models.BooleanField(default=False, help_text='True if facility has customized this system panel'),
        ),
        migrations.AddField(
            model_name='labpanel',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='True if this panel was seeded from the system catalog'),
        ),
        migrations.AddField(
            model_name='labpanel',
            name='system_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Original system values (price) for reset capability'),
        ),
        migrations.AddField(
            model_name='labtestcatalog',
            name='is_facility_modified',
            field=models.BooleanField(default=False, help_text='True if facility has customized this system test'),
        ),
        migrations.AddField(
            model_name='labtestcatalog',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='True if this test was seeded from the system catalog'),
        ),
        migrations.AddField(
            model_name='labtestcatalog',
            name='system_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Original system values (price, reference_ranges, tat_hours) for reset capability'),
        ),
        migrations.AlterField(
            model_name='labtestcatalog',
            name='category',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Chemistry'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology'), ('urinalysis', 'Urinalysis'), ('coagulation', 'Coagulation'), ('serology', 'Serology'), ('molecular', 'Molecular/PCR'), ('pathology', 'Pathology'), ('toxicology', 'Toxicology'), ('endocrine', 'Endocrine'), ('cardiac', 'Cardiac Markers'), ('other', 'Other')], max_length=30),
        ),
    ]
