# Generated by Django 4.2.10 on 2025-12-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_add_facility_customization_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labtestcatalog',
            index=models.Index(fields=['name'], name='laboratory__name_f2ab94_idx'),
        ),
    ]
