# Generated by Django 4.2.10 on 2025-12-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_user_first_name_gin_idx_and_more'),
        ('laboratory', '0003_add_name_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='performed_by',
            field=models.ForeignKey(help_text='Lab technician who performed the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_results', to='users.staff'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to='users.staff'),
        ),
        migrations.AlterField(
            model_name='labspecimen',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_specimens', to='users.staff'),
        ),
        migrations.AlterField(
            model_name='labspecimen',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_specimens', to='users.staff'),
        ),
    ]
