# Generated by Django 4.2.10 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _get_fallback_facility(Facility):
    facilities = Facility.objects.order_by('id')
    if facilities.count() == 1:
        return facilities.first()
    default_code = getattr(settings, 'DEFAULT_FACILITY_CODE', None)
    if default_code:
        return facilities.filter(code=default_code.strip().upper()).first()
    return None


def backfill_lab_facilities(apps, schema_editor):
    Facility = apps.get_model('core', 'Facility')
    LabOrder = apps.get_model('laboratory', 'LabOrder')
    LabOrderTest = apps.get_model('laboratory', 'LabOrderTest')
    LabSpecimen = apps.get_model('laboratory', 'LabSpecimen')
    LabResult = apps.get_model('laboratory', 'LabResult')

    fallback = _get_fallback_facility(Facility)

    def _assign_facility(model, queryset, resolver, label):
        items = list(queryset)
        for item in items:
            facility = resolver(item)
            if not facility and fallback:
                facility = fallback
            if facility:
                item.facility_id = facility.id
        if items:
            model.objects.bulk_update(items, ['facility'])
        if model.objects.filter(facility__isnull=True).exists():
            raise RuntimeError(
                f"{label} facility backfill incomplete. "
                "Ensure patient facilities or DEFAULT_FACILITY_CODE are set."
            )

    _assign_facility(
        LabOrder,
        LabOrder.objects.filter(facility__isnull=True)
        .select_related('patient__facility', 'encounter__facility'),
        lambda obj: (
            obj.patient.facility
            if obj.patient_id and getattr(obj.patient, 'facility_id', None)
            else (obj.encounter.facility if obj.encounter_id else None)
        ),
        'LabOrder',
    )

    _assign_facility(
        LabOrderTest,
        LabOrderTest.objects.filter(facility__isnull=True).select_related('order__facility'),
        lambda obj: obj.order.facility if obj.order_id else None,
        'LabOrderTest',
    )

    _assign_facility(
        LabSpecimen,
        LabSpecimen.objects.filter(facility__isnull=True).select_related('order__facility'),
        lambda obj: obj.order.facility if obj.order_id else None,
        'LabSpecimen',
    )

    _assign_facility(
        LabResult,
        LabResult.objects.filter(facility__isnull=True)
        .select_related('order_test__facility', 'specimen__facility'),
        lambda obj: (
            obj.order_test.facility
            if obj.order_test_id and getattr(obj.order_test, 'facility_id', None)
            else (obj.specimen.facility if obj.specimen_id else None)
        ),
        'LabResult',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_break_user_9c0c9d_idx_core_breakg_user_id_194f83_idx_and_more'),
        ('users', '0016_patient_facility'),
        ('encounters', '0002_add_facility_scoping'),
        ('laboratory', '0004_change_staff_fk_from_practitioner_to_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lab_orders',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lab_order_tests',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='labspecimen',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lab_specimens',
                to='core.facility',
            ),
        ),
        migrations.AddField(
            model_name='labresult',
            name='facility',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lab_results',
                to='core.facility',
            ),
        ),
        migrations.RunPython(backfill_lab_facilities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='laborder',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lab_orders',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='labordertest',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lab_order_tests',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='labspecimen',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lab_specimens',
                to='core.facility',
            ),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lab_results',
                to='core.facility',
            ),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['facility', 'status', 'ordered_at'], name='lab_order_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='labordertest',
            index=models.Index(fields=['facility', 'status'], name='lab_order_test_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='labspecimen',
            index=models.Index(fields=['facility', 'status', 'collected_at'], name='lab_specimen_facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['facility', 'performed_at'], name='lab_result_facility_perf_idx'),
        ),
    ]
