# Generated by Django 4.2.10 on 2026-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('laboratory', '0005_facility_scoping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='laborder',
            new_name='laboratory__facilit_1863e5_idx',
            old_name='lab_order_facility_status_idx',
        ),
        migrations.RenameIndex(
            model_name='labordertest',
            new_name='laboratory__facilit_bd4556_idx',
            old_name='lab_order_test_facility_status_idx',
        ),
        migrations.RenameIndex(
            model_name='labresult',
            new_name='laboratory__facilit_ac3d2e_idx',
            old_name='lab_result_facility_perf_idx',
        ),
        migrations.RenameIndex(
            model_name='labspecimen',
            new_name='laboratory__facilit_7e91fe_idx',
            old_name='lab_specimen_facility_status_idx',
        ),
        migrations.AlterField(
            model_name='laborder',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this lab order', on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='labordertest',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this lab order test', on_delete=django.db.models.deletion.PROTECT, related_name='lab_order_tests', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this lab result', on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='labspecimen',
            name='facility',
            field=models.ForeignKey(help_text='Facility context for this specimen', on_delete=django.db.models.deletion.PROTECT, related_name='lab_specimens', to='core.facility'),
        ),
    ]
