# Generated by Django 4.2.10 on 2026-01-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_status_fields'),
        ('laboratory', '0007_facility_scope_catalog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='labtestcatalog',
            name='laboratory__code_7c1f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='labpanel',
            new_name='laboratory__facilit_89dcce_idx',
            old_name='lab_panel_facility_code_idx',
        ),
        migrations.RenameIndex(
            model_name='labpanel',
            new_name='laboratory__facilit_719106_idx',
            old_name='lab_panel_facility_active_idx',
        ),
        migrations.RenameIndex(
            model_name='labtestcatalog',
            new_name='laboratory__facilit_68b79b_idx',
            old_name='lab_test_facility_code_idx',
        ),
        migrations.RenameIndex(
            model_name='labtestcatalog',
            new_name='laboratory__facilit_5fcbcb_idx',
            old_name='lab_test_facility_active_idx',
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this lab panel', on_delete=django.db.models.deletion.PROTECT, related_name='lab_panels', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='labtestcatalog',
            name='facility',
            field=models.ForeignKey(help_text='Facility that owns this test catalog entry', on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='core.facility'),
        ),
    ]
